### ISSUE TITLE
make gethostname in Java work without --request-network

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1075]
_From @percyliang on January 28, 2017 16:8_

Currently, the following program fails:

import java.io.*;
import java.util.*;
import java.net.*;

public class A {
  public static void main(String[] args) throws Exception {
    System.out.println(InetAddress.getLocalHost());
  }
}

with an exception:

Exception in thread "main" java.net.UnknownHostException: b1967f4a15f8: b1967f4a15f8: unknown error
	at java.net.InetAddress.getLocalHost(InetAddress.java:1484)
	at A.main(A.java:7)
Caused by: java.net.UnknownHostException: b1967f4a15f8: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1479)

This is because /etc/hosts doesn't have the line `127.0.0.1 b1967f4a15f8`.  This is fixed if you specify `--request-network`, but seems like we ought make it work even if you don't request network since there's no actual network usage here.

_Copied from original issue: codalab/codalab-worksheets#249_

**Comment by w0nche0l** [comment]
_From @percyliang on December 26, 2017 5:23_

@fabeschan Does your docker network PR change this in anyway?

**Comment by bkgoksel** [comment]
@percyliang Is this still relevant/useful as an issue?

**Comment by percyliang** [comment]
Probably still an issue, but probably low enough priority that we can close it.
