### ISSUE TITLE
Non-ASCII unicode character error on bundle manager

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1103]
Non-ASCII Unicode characters still seem to be causing issues.
This from prod bundle manager on 3/18/19:

```
2019-03-19 06:12:56,390 Re-staging run bundle 0x3c74adf0dc1841d5bb6ab421727156ff
Traceback (most recent call last):
  File "/opt/codalab-cli/codalab/worker/bundle_manager.py", line 68, in run
    self._run_iteration()
  File "/opt/codalab-cli/codalab/worker/bundle_manager.py", line 88, in _run_iteration
    self._schedule_run_bundles()
  File "/opt/codalab-cli/codalab/worker/default_bundle_manager.py", line 37, in _schedule_run_bundles
    self._schedule_run_bundles_on_workers(workers, user_owned=False)
  File "/opt/codalab-cli/codalab/worker/bundle_manager.py", line 319, in _schedule_run_bundles_on_workers
    if self._try_start_bundle(workers, worker, bundle):
  File "/opt/codalab-cli/codalab/worker/bundle_manager.py", line 422, in _try_start_bundle
    worker['socket_id'], self._construct_run_message(worker, bundle), 0.2
  File "/opt/codalab-cli/codalab/model/worker_model.py", line 371, in send_json_message
    sock.sendall(json.dumps(message))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 9: invalid start byte
```

Related #961 #502 #960

**Comment by bkgoksel** [comment]
Note from debugging, all the offending bundles had `git clonehttps://github.com/[REDACTED]/[REDACTED].git` as the command. There were a few instances of the bundle with the same command but with a space between `clone` and `https`. Perhaps the offending bundles had some non-ASCII whitespace character between `clone` and `https`. 

For now I manually removed the offending bundles, waiting for the server to go through the queue of bundles staged through this outage for now.
