### ISSUE TITLE
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by LeejwUniverse** [codalab/codalab-worksheets#1106]
hi.. I tried to use docker this image tensorflow/tensorflow:1.12.0-gpu-py3 
but I meet error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run/run_squad.py", line 26, in <module>
    import modeling
  File "/0x7890aa7842674d3c84e5c3695b90522e_dependencies/run/modeling.py", line 28, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

how to solve this issue.. please advise.

**Comment by ymcui** [comment]
Did you add `--request-gpus 1`?

**Comment by LeejwUniverse** [comment]
thanks bro. but unfortunately, after using --request-gpus 1,  My state is still staying 'staged;... it is not worked.. staying the 'staged'

**Comment by bkgoksel** [comment]
Hi @LeejwUniverse,
Could you share the UUID of the bundle that's stuck staged so we can inspect?
Thanks

**Comment by LeejwUniverse** [comment]
@bkgoksel UUID: 0xbba77a  , if not use  '--request-gpus 1' this command, i met above error. and if I use this command, my bundle is staying 'staged' status

**Comment by LeejwUniverse** [comment]
@bkgoksel and 0x382281 this UUID is failed

**Comment by LeejwUniverse** [comment]
@bkgoksel  sorry.. I found my mistake. thank you for your service. I apologize to you sorry..

**Comment by bkgoksel** [comment]
Hi @LeejwUniverse no worries, let us know if you run into any other issues!
