### ISSUE TITLE
Fail to upload large dataset

### ISSUE THREAD

**Issue by tonyyyang** [codalab/codalab-worksheets#113]
Tried uploading IMAGENET validation dataset (9.8G) to www.codalab.org/bundleservice for several times. In all cases, after uploading a part of the dataset (2.8G, for example), got `500 Internal Server Error`.

Stack traceback:

```
$: cl upload dataset data/ -n imagenet-validation
Uploading /user/.codalab/temp/tmpbvbMSB.zip to https://www.codalab.org/bundleservice: 2.8GTraceback (most recent call last):
  File "/opt/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 66, in <module>
    run_cli()
  File "/opt/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 57, in run_cli
    cli.do_command(sys.argv[1:])
  File "/opt/codalab-cli/codalab/lib/bundle_cli.py", line 357, in do_command
    command_fn(remaining_args, parser)
  File "/opt/codalab-cli/codalab/lib/bundle_cli.py", line 513, in do_upload_command
    print client.upload_bundle(args.path, {'bundle_type': args.bundle_type, 'metadata': metadata}, worksheet_uuid, args.follow_symlinks, args.exclude_patterns, True)
  File "/opt/codalab-cli/codalab/client/remote_bundle_client.py", line 173, in upload_bundle
    file_util.copy(source, dest, autoflush=False, print_status='Uploading %s%s to %s' % (zip_path, ' ('+info['uuid']+')' if 'uuid' in info else '', self.address))
  File "/opt/codalab-cli/codalab/lib/file_util.py", line 22, in copy
    dest.write(buffer)
  File "/opt/codalab-cli/codalab/server/rpc_file_handle.py", line 29, in write
    self.proxy.write_file(self.file_uuid, binary)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for www.codalab.org/bundleservice: 500 Internal Server Error>
```

```
$: cl upload dataset data/ -n imagenet-validation
Uploading /user/.codalab/temp/tmpIpu3uW.zip to https://www.codalab.org/bundleservice: 3.9GTraceback (most recent call last):
  File "/opt/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 66, in <module>
    run_cli()
  File "/opt/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 57, in run_cli
    cli.do_command(sys.argv[1:])
  File "/opt/codalab-cli/codalab/lib/bundle_cli.py", line 357, in do_command
    command_fn(remaining_args, parser)
  File "/opt/codalab-cli/codalab/lib/bundle_cli.py", line 513, in do_upload_command
    print client.upload_bundle(args.path, {'bundle_type': args.bundle_type, 'metadata': metadata}, worksheet_uuid, args.follow_symlinks, args.exclude_patterns, True)
  File "/opt/codalab-cli/codalab/client/remote_bundle_client.py", line 173, in upload_bundle
    file_util.copy(source, dest, autoflush=False, print_status='Uploading %s%s to %s' % (zip_path, ' ('+info['uuid']+')' if 'uuid' in info else '', self.address))
  File "/opt/codalab-cli/codalab/lib/file_util.py", line 22, in copy
    dest.write(buffer)
  File "/opt/codalab-cli/codalab/server/rpc_file_handle.py", line 29, in write
    self.proxy.write_file(self.file_uuid, binary)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for www.codalab.org/bundleservice: 500 Internal Server Error>
```

```
$: cl upload dataset data/ -n imagenet-validation
Uploading /user/.codalab/temp/tmp6kyWuX.zip to https://www.codalab.org/bundleservice: 3.8GTraceback (most recent call last):
  File "/opt/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 66, in <module>
    run_cli()
  File "/opt/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 57, in run_cli
    cli.do_command(sys.argv[1:])
  File "/opt/codalab-cli/codalab/lib/bundle_cli.py", line 357, in do_command
    command_fn(remaining_args, parser)
  File "/opt/codalab-cli/codalab/lib/bundle_cli.py", line 513, in do_upload_command
    print client.upload_bundle(args.path, {'bundle_type': args.bundle_type, 'metadata': metadata}, worksheet_uuid, args.follow_symlinks, args.exclude_patterns, True)
  File "/opt/codalab-cli/codalab/client/remote_bundle_client.py", line 173, in upload_bundle
    file_util.copy(source, dest, autoflush=False, print_status='Uploading %s%s to %s' % (zip_path, ' ('+info['uuid']+')' if 'uuid' in info else '', self.address))
  File "/opt/codalab-cli/codalab/lib/file_util.py", line 22, in copy
    dest.write(buffer)
  File "/opt/codalab-cli/codalab/server/rpc_file_handle.py", line 29, in write
    self.proxy.write_file(self.file_uuid, binary)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/opt/codalab-cli/codalab/client/remote_bundle_client.py", line 54, in send_content
    xmlrpclib.SafeTransport.send_content(self, connection, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1178, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
```

**Comment by percyliang** [comment]
Should be fixed by #262 and the new server.
