### ISSUE TITLE
Dependency symlink [File exists] issue in worker

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1154]
Many workers went offline on the same day with the following error message:
```
2019-06-03 19:53:31,621 http://localhost:None "GET /v1.35/images/theerit/quac_flowqa_submission:latest/json HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/opt/worker/codalabworker/worker.py", line 51, in start
    self._run_manager.process_runs()
  File "/opt/worker/codalabworker/local_run/local_run_manager.py", line 171, in process_runs
    self._runs[bundle_uuid] = self._run_state_manager.transition(run_state)
  File "/opt/worker/codalabworker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/worker/codalabworker/local_run/local_run_state.py", line 221, in _transition_from_PREPARING
    os.symlink(docker_dependency_path, child_path)
OSError: [Errno 17] File exists

```

Unclear as of yet why this could be happening.

**Comment by bkgoksel** [comment]
This means there's already a file under the same name as the _child path_ of the dependency in the bundle folder. Need to think more carefully about how that could happen.

**Comment by bkgoksel** [comment]
Here's the offending worksheet with some of the offending bundles:
https://worksheets.codalab.org/worksheets/0x172b8d074ab340348d37fdfd3c585ae8
Somehow we're still allowing unkeyed dependencies.
Need to:
1-) Not allow this client AND server-side
2-) Make worker more resilient to these somehow
