### ISSUE TITLE
Dashboard (on worksheets-dev) doesn't load

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1193]
Click the dashboard icon.  It goes to the page, but get in the console:
 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by bkgoksel** [comment]
Also works for me (Firefox on Windows)

**Comment by percyliang** [comment]
I think it depends on what's on your dashboard.  I see this in the docker logs:

```Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 148, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-worksheets/venv/local/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/opt/codalab-worksheets/codalab/server/json_api_plugin.py", line 18, in wrapper
    result = callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/rest/interpret.py", line 178, in fetch_interpreted_worksheet
    worksheet_info['items'] = expand_raw_items(worksheet_info['items'])
  File "/opt/codalab-worksheets/codalab/rest/interpret.py", line 572, in expand_raw_items
    return list(chain.from_iterable([expand_raw_item(raw_item) for raw_item in raw_items]))
  File "/opt/codalab-worksheets/codalab/rest/interpret.py", line 604, in expand_raw_item
    bundle_infos = rest_util.get_bundle_infos(bundle_uuids)
  File "/opt/codalab-worksheets/codalab/rest/util.py", line 65, in get_bundle_infos
    bundles = local.model.batch_get_bundles(uuid=uuids)
  File "/opt/codalab-worksheets/codalab/model/bundle_model.py", line 644, in batch_get_bundles
    for bundle_value in sorted_values
  File "/opt/codalab-worksheets/codalab/model/orm_object.py", line 17, in __init__
    self.update_in_memory(dict(row), strict=strict)
  File "/opt/codalab-worksheets/codalab/objects/bundle.py", line 62, in update_in_memory
    self.metadata = Metadata(self.METADATA_SPECS, metadata)
  File "/opt/codalab-worksheets/codalab/objects/metadata.py", line 13, in __init__
    metadata_dict = self.collapse_dicts(metadata_specs, metadata_dict)
  File "/opt/codalab-worksheets/codalab/objects/metadata.py", line 89, in collapse_dicts
    metadata_dict[key] = spec.get_constructor()(value)
  File "/opt/codalab-worksheets/codalab/objects/metadata_spec.py", line 26, in unicode_constructor
    s = unicode(s, encoding='utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 0: unexpected end of data```

**Comment by percyliang** [comment]
For some reason, there's no email sent out about these errors...

**Comment by percyliang** [comment]
Can't reproduce.  Might be fixed with recent fixes to Unicode.
