### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Cuijie12358** [codalab/codalab-worksheets#1223]
Hi, I am a new CodaLab user here. The thing is when I upload all the files in one directory and run the python file, it says IOError: [Errno 2] No such file or directory. However I have uploaded the file.

`Traceback (most recent call last):
  File "hasty_student/evaluate_hasty.py", line 96, in <module>
    main()
  File "hasty_student/evaluate_hasty.py", line 81, in main
    model.load_state_dict(torch.load(load_model))
  File "/usr/local/lib/python2.7/dist-packages/torch-1.1.0-py2.7-linux-x86_64.egg/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: './hasty_student_epoch_6_0.600230_acc.pth'
`

**Comment by Cuijie12358** [comment]
The evaluate_hasty.py and the hasty_student_epoch_6_0.600230_acc.pth are in the same directory.
