### ISSUE TITLE
[codalab_service.py] python: can't open file 'scripts/create-root-user.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by cooelf** [codalab/codalab-worksheets#1290]
Hi! I am building my own CodaLab Server following the [instructions](https://github.com/codalab/codalab-worksheets/wiki/Server-Setup), but when I proceed to the following command, 

`./codalab_service.py start`

an error occured,

```
(py2) coulson@asteroid-System-Product-Name:~/codalab-worksheets$ ./codalab_service.py start
[CodaLab] Bringing up mysql
(cd /home/coulson/codalab-worksheets/docker/compose_files; CODALAB_REST_PORT=2900 CODALAB_WORKER_DIR=/home/coulson/codalab-worksheets/codalab-worker-scratch CODALAB_MYSQL_PWD=codalab CODALAB_VERSION=latest CODALAB_MYSQL_USER=codalab CODALAB_HTTP_PORT=80 CODALAB_ROOT_PWD=codalab CODALAB_SERVICE_HOME=/home/codalab CODALAB_ROOT_USER=codalab CODALAB_WORKER_NETWORK_NAME=codalab-worker-network CODALAB_MYSQL_ROOT_PWD=codalab CODALAB_UID=1001:1001 docker-compose -p codalab -f docker-compose.yml -f docker-compose.no_home_mount.yml -f docker-compose.mysql.yml -f docker-compose.worker.yml up -d --no-deps mysql)
codalab_mysql_1 is up-to-date

[CodaLab] Configuring the service
(cd /home/coulson/codalab-worksheets/docker/compose_files; CODALAB_REST_PORT=2900 CODALAB_WORKER_DIR=/home/coulson/codalab-worksheets/codalab-worker-scratch CODALAB_MYSQL_PWD=codalab CODALAB_VERSION=latest CODALAB_MYSQL_USER=codalab CODALAB_HTTP_PORT=80 CODALAB_ROOT_PWD=codalab CODALAB_SERVICE_HOME=/home/codalab CODALAB_ROOT_USER=codalab CODALAB_WORKER_NETWORK_NAME=codalab-worker-network CODALAB_MYSQL_ROOT_PWD=codalab CODALAB_UID=1001:1001 docker-compose -p codalab -f docker-compose.yml -f docker-compose.no_home_mount.yml -f docker-compose.mysql.yml -f docker-compose.worker.yml run --no-deps --rm --entrypoint="" --user=0:0 rest-server bash -c "/opt/wait-for-it.sh mysql:3306 -- cl config server/engine_url mysql://codalab:codalab@mysql:3306/codalab_bundles && cl config cli/default_address http://rest-server:2900 && cl config server/rest_host 0.0.0.0")
wait-for-it.sh: waiting 15 seconds for mysql:3306
wait-for-it.sh: mysql:3306 is available after 0 seconds

[CodaLab] Creating root user
(cd /home/coulson/codalab-worksheets/docker/compose_files; CODALAB_REST_PORT=2900 CODALAB_WORKER_DIR=/home/coulson/codalab-worksheets/codalab-worker-scratch CODALAB_MYSQL_PWD=codalab CODALAB_VERSION=latest CODALAB_MYSQL_USER=codalab CODALAB_HTTP_PORT=80 CODALAB_ROOT_PWD=codalab CODALAB_SERVICE_HOME=/home/codalab CODALAB_ROOT_USER=codalab CODALAB_WORKER_NETWORK_NAME=codalab-worker-network CODALAB_MYSQL_ROOT_PWD=codalab CODALAB_UID=1001:1001 docker-compose -p codalab -f docker-compose.yml -f docker-compose.no_home_mount.yml -f docker-compose.mysql.yml -f docker-compose.worker.yml run --no-deps --rm --entrypoint="" --user=0:0 rest-server bash -c "/opt/wait-for-it.sh mysql:3306 -- python scripts/create-root-user.py codalab")
wait-for-it.sh: waiting 15 seconds for mysql:3306
wait-for-it.sh: mysql:3306 is available after 0 seconds
python: can't open file 'scripts/create-root-user.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./codalab_service.py", line 673, in <module>
    main()
  File "./codalab_service.py", line 55, in main
    service_manager.execute()
  File "./codalab_service.py", line 536, in execute
    self.start_services()
  File "./codalab_service.py", line 632, in start_services
    root=True,
  File "./codalab_service.py", line 600, in run_service_cmd
    + (' bash -c "%s"' % cmd)
  File "./codalab_service.py", line 583, in _run_compose_cmd
    command_string, cwd=self.compose_cwd, env=self.compose_env, shell=True
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker-compose -p codalab -f docker-compose.yml -f docker-compose.no_home_mount.yml -f docker-compose.mysql.yml -f docker-compose.worker.yml run --no-deps --rm --entrypoint="" --user=0:0 rest-server bash -c "/opt/wait-for-it.sh mysql:3306 -- python scripts/create-root-user.py codalab"' returned non-zero exit status 2
```
It seems to be a path issue. I cloned the latest repo today via `git clone https://github.com/codalab/codalab-worksheets` and I am in the worksheet folder and the file `scripts/create-root-user.py ` exists. 

Not sure why this issue appears. Do you have any idea?

**Comment by percyliang** [comment]
We haven't pushed the latest docker images so what's on Docker Hub is out of date.  You can add the `-b` flag to build the up to date images locally.

**Comment by cooelf** [comment]
Thanks, it works well now!
