### ISSUE TITLE
[Python 3] Running "cl" by itself in a venv (not docker) gives an error

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1332]
```
Traceback (most recent call last):
  File "/home/epicfaace/codalab/codalab-worksheets/venv/bin/cl", line 11, in <module>
    load_entry_point('codalab', 'console_scripts', 'cl')()
  File "/home/epicfaace/codalab/codalab-worksheets/codalab/bin/cl.py", line 120, in main
    cli.do_command([os.fsencode(arg).decode() for arg in sys.argv[1:]])
  File "/home/epicfaace/codalab/codalab-worksheets/codalab/lib/bundle_cli.py", line 847, in do_command
    structured_result = command_fn()
  File "/home/epicfaace/codalab/codalab-worksheets/codalab/lib/bundle_cli.py", line 841, in <lambda>
    command_fn = lambda: args.function(self, args)
AttributeError: 'Namespace' object has no attribute 'function'
```

See https://github.com/powerline/powerline/issues/1120

**Comment by epicfaace** [comment]
@percyliang aagh, this was a python 2->3 unintentionally backwards-incompatible change https://bugs.python.org/issue16308

**Comment by epicfaace** [comment]
I've added a fix to this in a commit on the python3 branch.

It seems like the `error()` method on the `CodaLabArgumentParser` _was_ overridden to have this behavior (of printing "help" on "cl"), though. No idea why the code here stopped running properly in Python 3:

https://github.com/codalab/codalab-worksheets/blob/f664347652249842147f3ceb2671785dfa7101f4/codalab/lib/bundle_cli.py#L174-L180

Probably due to another change in how argparser works in Python 3. It's worth investigating another time.
