### ISSUE TITLE
Can't run "black format" when var directory exists

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1339]
The new changes to dockerfiles have created a `var` folder in the root directory. Running "black format" gives me the following error; I have to delete the `var` folder before doing so.

```
epicfaace@epic-machine-linux:~/codalab/codalab-worksheets$ sudo black .
Traceback (most recent call last):
  File "/home/epicfaace/.local/bin/black", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/epicfaace/.local/lib/python3.6/site-packages/black.py", line 338, in main
    gen_python_files_in_dir(p, root, include_regex, exclude_regex, report)
  File "/home/epicfaace/.local/lib/python3.6/site-packages/black.py", line 3138, in gen_python_files_in_dir
    yield from gen_python_files_in_dir(child, root, include, exclude, report)
  File "/home/epicfaace/.local/lib/python3.6/site-packages/black.py", line 3138, in gen_python_files_in_dir
    yield from gen_python_files_in_dir(child, root, include, exclude, report)
  File "/home/epicfaace/.local/lib/python3.6/site-packages/black.py", line 3138, in gen_python_files_in_dir
    yield from gen_python_files_in_dir(child, root, include, exclude, report)
  [Previous line repeated 81 more times]
  File "/home/epicfaace/.local/lib/python3.6/site-packages/black.py", line 3130, in gen_python_files_in_dir
    if child.is_dir():
  File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
    return self._accessor.stat(self)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 40] Too many levels of symbolic links: 'var/codalab/home/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default/partitions/default'
```

**Comment by percyliang** [comment]
Is there the equivalent of a "gitignore" for black?  We just want it to go through certain files/directories...this is already done on travis.

**Comment by percyliang** [comment]
With `pre-commit.sh`, this is not really an issue.
