### ISSUE TITLE
Permission denied when writes files to docker container.

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1382]
Some of the commands in the documentation don't work, as the user doesn't have write permission outside the docker container.
```
Jings-MacBook-Pro:codalab-worksheets jingge$ docker exec codalab_rest-server_1 alembic revision --autogenerate -m "description of your migration"
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Generating /opt/codalab-worksheets/alembic/versions/2019091011_description_of_your_migration_64f13ac1e4f8.py ... FAILED
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 10, in <module>
...
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 26, in template_to_file
    with open(dest, 'wb') as f:
IOError: [Errno 13] Permission denied: '/opt/codalab-worksheets/alembic/versions/2019091011_description_of_your_migration_64f13ac1e4f8.py'
```
When I log in to the container, it shows the following file stats:
```
Jings-MacBook-Pro:codalab-worksheets jingge$ docker exec -it codalab_rest-server_1 bash
I have no name!@18071862c41a:/opt/codalab-worksheets$ whoami
whoami: cannot find name for user ID 501
I have no name!@18071862c41a:/opt/codalab-worksheets$ id
uid=501 gid=20(dialout) groups=20(dialout)
I have no name!@18071862c41a:/opt/codalab-worksheets$ ls -ltr
total 152
-rw-r--r-- 1 root root   109 Jul 15 20:58 requirements.txt
-rw-r--r-- 1 root root  1159 Jul 19 21:14 alembic.ini
-rw-r--r-- 1 root root  1900 Aug 19 07:40 setup.py
-rw-r--r-- 1 root root    13 Aug 19 07:40 requirements.docs.txt
-rw-r--r-- 1 root root   650 Aug 19 07:40 mkdocs.yml
-rw-r--r-- 1 root root 61118 Aug 26 07:10 test_cli.py
-rw-r--r-- 1 root root  9989 Aug 26 07:10 monitor.py
-rwxr-xr-x 1 root root 22665 Aug 26 07:10 codalab_service.py
-rw-r--r-- 1 root root   169 Sep  8 06:34 requirements-server.txt
drwxr-xr-x 1 root root  4096 Sep 10 11:23 alembic
drwxr-xr-x 1 root root  4096 Sep 10 11:23 docs
drwxr-xr-x 1 root root  4096 Sep 10 11:23 codalab
drwxr-xr-x 1 root root  4096 Sep 10 11:23 scripts
drwxr-xr-x 1 root root  4096 Sep 10 11:23 worker
drwxr-xr-x 1 root root  4096 Sep 10 11:23 views
drwxr-xr-x 1 root root  4096 Sep 10 11:23 tests
drwxr-xr-x 1 root root  4096 Sep 10 11:23 codalab.egg-info
```

**Comment by percyliang** [comment]
You need to make sure you own all the files.  Run `chown -R 501:501 .` in your `codalab-worksheets` directory.

**Comment by percyliang** [comment]
Has this been resolved?

**Comment by candicegjing** [comment]
Not yet. I tried to set the user and group to be 501 in `codalab-worksheets` directory, but I still get the permission error. I'll check more in detail to see the root cause of it.

**Comment by candicegjing** [comment]
So I did more checks and found the following file stats:
1. Entered into rest-server container and checked the permission of all files.
```
Jings-MacBook-Pro:codalab-worksheets jingge$ docker exec -it codalab_rest-server_1 bash
I have no name!@24290946ad70:/opt/codalab-worksheets$ ls -la
total 160
drwxr-xr-x 1 root root  4096 Sep 17 05:34 .
drwxr-xr-x 1 root root  4096 Sep 11 10:01 ..
drwxr-xr-x 1 root root  4096 Sep 13 07:00 alembic
-rw-r--r-- 1 root root  1159 Sep  5 07:22 alembic.ini
drwxr-xr-x 1 root root  4096 Sep 17 05:34 codalab
drwxr-xr-x 1 root root  4096 Sep 17 05:34 codalab.egg-info
-rwxr-xr-x 1 root root 24064 Sep 15 09:53 codalab_service.py
drwxr-xr-x 1 root root  4096 Sep 17 05:34 docs
-rw-r--r-- 1 root root   650 Sep  5 07:22 mkdocs.yml
-rw-r--r-- 1 root root 10031 Sep 15 09:53 monitor.py
-rw-r--r-- 1 root root   253 Sep 13 06:52 requirements-server.txt
-rw-r--r-- 1 root root    13 Sep  5 07:22 requirements.docs.txt
-rw-r--r-- 1 root root   200 Sep 13 06:52 requirements.txt
drwxr-xr-x 1 root root  4096 Sep 17 05:34 scripts
-rw-r--r-- 1 root root  1495 Sep 17 01:11 setup.py
-rw-r--r-- 1 root root 63820 Sep 16 14:02 test_cli.py
drwxr-xr-x 1 root root  4096 Sep 17 05:34 tests
drwxr-xr-x 1 root root  4096 Sep 17 05:34 views
```
2. Wrote a file to `/opt/codalab-worksheets/alembic/versions/` directory
``` 
I have no name!@24290946ad70:/opt/codalab-worksheets$ touch file_to_test alembic/versions/
touch: cannot touch 'file_to_test': Permission denied
touch: setting times of 'alembic/versions/': Permission denied
```
3. Checked the default user id in Docker container:
```
I have no name!@24290946ad70:/opt/codalab-worksheets$ id
uid=501 gid=20(dialout) groups=20(dialout)
```
4. Checked the `id` for `root` user in Docker container, as all files are under `root:root`.
```
I have no name!@f6a9de081a84:/opt/codalab-worksheets$ id root
uid=0(root) gid=0(root) groups=0(root)
```
So the user behavior seems to be `user (501)` was trying to write a file to a directory which is owned by `user (0)` and got permission denied.

**Comment by candicegjing** [comment]
I think `user (501)` is considered as `other user` who doesn't have `write` permission within the container. Do we want to 
1. change all the files within the docker container to be owned by `user (501)` or
2. change login user to be `root` or
3. give write permission to `other users`?

**Comment by percyliang** [comment]
The problem is that all your files are owned by root.  Running `sudo chown
-R 501:501 .` outside docker on your codalab-worksheets directory should
fix that.  When you do that, does that work or is there an error?

**Comment by candicegjing** [comment]
Outside of the docker container looks like this:
```
Jings-MacBook-Pro:codalab-worksheets jingge$ ls -ltr
total 296
-rw-r--r--   1 jingge  staff    568 Sep  6 17:31 LICENSE.txt
-rw-r--r--   1 jingge  staff     43 Sep  6 17:31 MANIFEST.in
-rw-r--r--   1 jingge  staff    746 Sep  6 17:31 README.md
-rw-r--r--   1 jingge  staff   1159 Sep  6 17:31 alembic.ini
drwxr-xr-x   5 jingge  staff    160 Sep  6 17:31 docker
-rw-r--r--   1 jingge  staff    650 Sep  6 17:31 mkdocs.yml
-rw-r--r--   1 jingge  staff    249 Sep  6 17:31 pyproject.toml
-rw-r--r--   1 jingge  staff   1025 Sep  6 17:31 rc
-rw-r--r--   1 jingge  staff     13 Sep  6 17:31 requirements.docs.txt
-rw-r--r--   1 jingge  staff    109 Sep  6 17:31 requirements.txt
drwxr-xr-x  10 jingge  staff    320 Sep  6 17:31 tests
drwxr-xr-x   3 jingge  staff     96 Sep  8 13:33 var
drwxr-xr-x   9 jingge  staff    288 Sep  8 16:42 views
drwxr-xr-x  13 jingge  staff    416 Sep  8 16:42 codalab
-rw-r--r--   1 jingge  staff    253 Sep  8 16:42 requirements-server.txt
drwxr-xr-x  13 jingge  staff    416 Sep  8 16:42 scripts
-rw-r--r--   1 jingge  staff   1900 Sep  8 16:42 setup.py
drwxr-xr-x   6 jingge  staff    192 Sep  8 16:42 worker
drwxr-xr-x   7 jingge  staff    224 Sep  9 19:19 alembic
drwxr-xr-x   7 jingge  staff    224 Sep 11 20:30 venv
-rwxr-xr-x   1 jingge  staff  24064 Sep 13 15:01 codalab_service.py
drwxr-xr-x  17 jingge  staff    544 Sep 13 15:01 docs
drwxr-xr-x  11 jingge  staff    352 Sep 13 15:01 frontend
-rw-r--r--   1 jingge  staff  10031 Sep 13 15:01 monitor.py
-rwxr-xr-x   1 jingge  staff    849 Sep 13 15:01 pre-commit.sh
-rw-r--r--   1 jingge  staff  63290 Sep 17 13:37 test_cli.py
```
After I changed owner and group to be 501, it looks like:
```
Jings-MacBook-Pro:codalab-worksheets jingge$ sudo chown -R 501:501 .
Password:
Jings-MacBook-Pro:codalab-worksheets jingge$ ls -ltr
total 296
-rw-r--r--   1 jingge  501    568 Sep  6 17:31 LICENSE.txt
-rw-r--r--   1 jingge  501     43 Sep  6 17:31 MANIFEST.in
-rw-r--r--   1 jingge  501    746 Sep  6 17:31 README.md
-rw-r--r--   1 jingge  501   1159 Sep  6 17:31 alembic.ini
drwxr-xr-x   5 jingge  501    160 Sep  6 17:31 docker
-rw-r--r--   1 jingge  501    650 Sep  6 17:31 mkdocs.yml
-rw-r--r--   1 jingge  501    249 Sep  6 17:31 pyproject.toml
-rw-r--r--   1 jingge  501   1025 Sep  6 17:31 rc
-rw-r--r--   1 jingge  501     13 Sep  6 17:31 requirements.docs.txt
-rw-r--r--   1 jingge  501    109 Sep  6 17:31 requirements.txt
drwxr-xr-x  10 jingge  501    320 Sep  6 17:31 tests
drwxr-xr-x   3 jingge  501     96 Sep  8 13:33 var
drwxr-xr-x   9 jingge  501    288 Sep  8 16:42 views
drwxr-xr-x  13 jingge  501    416 Sep  8 16:42 codalab
-rw-r--r--   1 jingge  501    253 Sep  8 16:42 requirements-server.txt
drwxr-xr-x  13 jingge  501    416 Sep  8 16:42 scripts
-rw-r--r--   1 jingge  501   1900 Sep  8 16:42 setup.py
drwxr-xr-x   6 jingge  501    192 Sep  8 16:42 worker
drwxr-xr-x   7 jingge  501    224 Sep  9 19:19 alembic
drwxr-xr-x   7 jingge  501    224 Sep 11 20:30 venv
-rwxr-xr-x   1 jingge  501  24064 Sep 13 15:01 codalab_service.py
drwxr-xr-x  17 jingge  501    544 Sep 13 15:01 docs
drwxr-xr-x  11 jingge  501    352 Sep 13 15:01 frontend
-rw-r--r--   1 jingge  501  10031 Sep 13 15:01 monitor.py
-rwxr-xr-x   1 jingge  501    849 Sep 13 15:01 pre-commit.sh
-rw-r--r--   1 jingge  501  63290 Sep 17 13:37 test_cli.py
```
Then I ran the autogenerate command:
```
Jings-MacBook-Pro:codalab-worksheets jingge$ docker exec codalab_rest-server_1 alembic revision --autogenerate -m "description of your migration"
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Generating /opt/codalab-worksheets/alembic/versions/2019091713_description_of_your_migration_5e2a78675b6b.py ... FAILED
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/alembic/config.py", line 486, in main
    CommandLine(prog=prog).main(argv=argv)
....
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/pyfiles.py", line 26, in template_to_file
    with open(dest, 'wb') as f:
PermissionError: [Errno 13] Permission denied: '/opt/codalab-worksheets/alembic/versions/2019091713_description_of_your_migration_5e2a78675b6b.py'
```

**Comment by percyliang** [comment]
Can you try any other commands that try to write inside docker?

Also, should do `sudo chown -R jingge:staff .` instead.

**Comment by candicegjing** [comment]
`jingge:staff` is the default user group setting on my laptop. I tried another command to write a file inside the docker container (rebuilt one with original settings) as following:
```
I have no name!@128fadfa49b2:/opt/codalab-worksheets$ cat mkdocs.yml > alembic/versions/mkdocs.bak
bash: alembic/versions/mkdocs.bak: Permission denied
```

**Comment by JiexingQi** [comment]
I have face the same problem, could you give me some suggestions about it?Thank you.
