### ISSUE TITLE
Dev - unicode error for stress-test.pl

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1385]
Email logs
```
>> timeout 60s cl upload scripts/stress-test.pl (exit code 1, time 0.89s [limit: 15s,60s]; avg 0.00s; max 0.89s)
Preparing upload archive...
Uploading stress-test.pl (0xbacd89e98b654633bd0b658339724a85) to http://rest-server:2900

Sent 0.00MiB / 0.00MiB (100.0%) [0.74MiB/sec]    			
Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/client/json_api_client.py", line 15, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/client/json_api_client.py", line 645, in upload_contents_blob
    progress_callback=progress_callback,
  File "/opt/codalab-worksheets/worker/codalabworker/rest_client.py", line 156, in _upload_with_chunked_encoding
    StringIO(response.read().decode()),
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cl", line 11, in 
    load_entry_point('codalab', 'console_scripts', 'cl')()
  File "/opt/codalab-worksheets/codalab/bin/cl.py", line 117, in main
    cli.do_command(sys.argv[1:])
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 854, in do_command
    structured_result = command_fn()
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 848, in 
    command_fn = lambda: args.function(self, args)
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 1229, in do_upload_command
    progress_callback=progress.update,
  File "/opt/codalab-worksheets/codalab/client/json_api_client.py", line 18, in wrapper
    error_body = e.read().decode()
AttributeError: 'str' object has no attribute 'decode'

```

Another email:

```
>> timeout 60s cl run stress-test.pl: perl stress-test.pl 5 10 10 (exit code 1, time 0.76s [limit: 15s,60s]; avg 0.00s; max 0.76s)
Traceback (most recent call last):
  File "/usr/local/bin/cl", line 11, in 
    load_entry_point('codalab', 'console_scripts', 'cl')()
  File "/opt/codalab-worksheets/codalab/bin/cl.py", line 117, in main
    cli.do_command(sys.argv[1:])
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 854, in do_command
    structured_result = command_fn()
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 848, in 
    command_fn = lambda: args.function(self, args)
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 1523, in do_run_command
    targets = self.resolve_key_targets(client, worksheet_uuid, args.target_spec)
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 600, in resolve_key_targets
    client, worksheet_uuid, target_spec, allow_remote=False
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 578, in resolve_target
    bundle_uuid = BundleCLI.resolve_bundle_uuid(client, worksheet_uuid, bundle_spec)
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 612, in resolve_bundle_uuid
    if spec_util.UUID_REGEX.match(bundle_spec):
TypeError: expected string or bytes-like object
```

**Comment by epicfaace** [comment]
Get the following errors when doing `docker exec -it codalab_monitor_1 /bin/bash` and then running `cl upload`:
```
root@fcf5e1c23d8e:/opt/codalab-worksheets# cl upload scripts/stress-test.pl
Preparing upload archive...
Uploading stress-test.pl (0x647243f1a25a4e5ebf8221cc0a851ed1) to http://rest-server:2900
Sent 0.00MiB / 0.00MiB (100.0%) [0.83MiB/sec]    
UsageError: Error while parsing chunked transfer body
```

(Note: this worked fine when running it locally; it just failed on the dev server @percyliang )

**Comment by epicfaace** [comment]
Diff: (left - local, working. right - dev, not working) https://www.diffchecker.com/xiRuqZiu

**Comment by epicfaace** [comment]
Probably has to do with this: https://github.com/bottlepy/bottle/issues/700

**Comment by epicfaace** [comment]
Diff between local and dev (headers, chunked_body): https://www.diffchecker.com/itN6PGaC

**Comment by epicfaace** [comment]
Fixed by @percyliang -- there was an extra symlink from `/data/data` to `/data` just on the dev server.
