### ISSUE TITLE
[USER ISSUE] netcat not working

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#1398]
**Describe the bug**
The netcat/netcurl tool, where you can send HTTP requests to running bundles, does not seem to work.

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 0x9e497fa5583a4064b7bc9de0d8e0f6d0
- *UUID of problem bundle (please don't delete)*: 0xb5def7a5b9ca4a64a2070c4d29480d16
- *Error message received from Codalab (if applicable)*:
First issue: I was told that going to http://worksheets.codalab.org/0xb5def7a5b9ca4a64a2070c4d29480d16/netcat/8000/ should work, but instead it gives me a ERR_CONNECTION_REFUSED

Second issue: I tried running `cl netcat 0xb5def7a5b9ca4a64a2070c4d29480d16 8000 ''` as in the documentation, but this hangs for 2 minutes and then returns the following error message:
```
Traceback (most recent call last):
  File "/home/robinjia/.local/bin/cl", line 10, in <module>
    sys.exit(main())
  File "/home/robinjia/.local/lib/python2.7/site-packages/codalab/bin/cl.py", line 117, in main
    cli.do_command(sys.argv[1:])
  File "/home/robinjia/.local/lib/python2.7/site-packages/codalab/lib/bundle_cli.py", line 843, in do_command
    structured_result = command_fn()
  File "/home/robinjia/.local/lib/python2.7/site-packages/codalab/lib/bundle_cli.py", line 837, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/home/robinjia/.local/lib/python2.7/site-packages/codalab/lib/bundle_cli.py", line 2207, in do_netcat_command
    info = client.netcat(bundle_uuid, port=args.port, data={"message": args.message})
  File "/home/robinjia/.local/lib/python2.7/site-packages/codalab/client/json_api_client.py", line 36, in wrapper
    sys.exc_info()[2],
  File "/home/robinjia/.local/lib/python2.7/site-packages/codalab/client/json_api_client.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/home/robinjia/.local/lib/python2.7/site-packages/codalab/client/json_api_client.py", line 446, in netcat
    return self._make_request('PUT', request_path, data=data)
  File "/home/robinjia/.local/lib/python2.7/site-packages/codalabworker/rest_client.py", line 91, in _make_request
    with closing(urllib2.urlopen(request)) as response:
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
codalab.client.json_api_client.JsonApiException: Unable to netcat 0xb5def7a5b9ca4a64a2070c4d29480d16: Internal Server Error - Internal Server Error
```
After running this command, the status of the bundle also changes from "running" to "worker_offline".

 - *OS (if on CLI)*: Ubuntu 18.04
 - *Codalab CLI Version (if on CLI)*: 0.3.3
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Start a bundle that runs a HTTP server, such as 0xb5def7a5b9ca4a64a2070c4d29480d16
2. Visit the URL `http://worksheets.codalab.org/<uuid>/netcat/<port>/` in browser
3. Run `cl netcat <uuid> <port> ''`

**Expected behavior**
It should return HTML showing contents of the working directory, since that's what python's SimpleHTTPServer does.

**Comment by percyliang** [comment]
Fixed by #1407

**Comment by percyliang** [comment]
@robinjia This should be deployed - do you want to give it a try:
https://worksheets.codalab.org/rest/bundles/UUID/netcurl/PORT/
(the trailing slash is important)

**Comment by robinjia** [comment]
This works now, thanks!

**Comment by robinjia** [comment]
One nit: if you visit the URL when the bundle is staged, it gives a 500 error. I'll make another issue about this, but it's not a big deal.
