### ISSUE TITLE
[USER ISSUE] uninformative error message when exceeding disk quota

### ISSUE THREAD

**Issue by jayelm** [codalab/codalab-worksheets#1400]
**Describe the bug**
I uploaded a bundle which ended up being too big for my disk quota. The error message is uninformative because the client tries to `decode` a `str` that's already been decoded. Probably Python 2 leftovers?

*Codalab CLI Version (if on CLI)*:  0.40

**To Reproduce**
Upload a too-big bundle.

```
cl upload filelists
Preparing upload archive...
Uploading filelists.tar.gz (0x018f36c1d02b467e8cf04c0e8eb568a4) to https://worksheets.codalab.org
Sent 4133.13MiB [2.99MiB/sec]
Traceback (most recent call last):
  File "/Users/jayelm/miniconda3/envs/py37/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 15, in wrapper
    return f(*args, **kwargs)
  File "/Users/jayelm/miniconda3/envs/py37/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 645, in upload_contents_blob
    progress_callback=progress_callback,
  File "/Users/jayelm/Git/codalab-worksheets/worker/codalabworker/rest_client.py", line 156, in _upload_with_chunked_encoding
    StringIO(response.read().decode()),
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jayelm/miniconda3/envs/py37/bin/cl", line 10, in <module>
    sys.exit(main())
  File "/Users/jayelm/miniconda3/envs/py37/lib/python3.7/site-packages/codalab/bin/cl.py", line 117, in main
    cli.do_command(sys.argv[1:])
  File "/Users/jayelm/miniconda3/envs/py37/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 854, in do_command
    structured_result = command_fn()
  File "/Users/jayelm/miniconda3/envs/py37/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 848, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/Users/jayelm/miniconda3/envs/py37/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 1229, in do_upload_command
    progress_callback=progress.update,
  File "/Users/jayelm/miniconda3/envs/py37/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    error_body = e.read().decode()
AttributeError: 'str' object has no attribute 'decode'
```

website failure message:
```
Upload failed: Can't save bundle, bundle size 4334927602 greater than user's disk quota left: 2100700844.0
```

**Comment by epicfaace** [comment]
Looks like this is indeed due to the python 3 migration. We are assuming that the error body is bytes, but it can sometimes be a string -- as, in particular, here: https://github.com/codalab/codalab-worksheets/blob/2f9dfdd7f0546469cb1f4dd83d358015422642ec/codalab/rest/bundles.py#L690

**Comment by percyliang** [comment]
@candicegjing is this fixed now?

**Comment by candicegjing** [comment]
> @candicegjing is this fixed now?

This is fixed. Verified at a local instance, see the following results:
```
>>> codalab-worksheets % dcl work   
Currently on worksheet: http://rest-server:2900/worksheets/0xdc4394068b5e4bc796ed107ee1b41033 (codalab-image)
stanford@Stanfords-MacBook-Pro codalab-worksheets % dcl upload scripts
Preparing upload archive...
Uploading scripts.tar.gz (0x2fd94759f26a4e6dbe296993b5c5733a) to http://rest-server:2900
Sent 0.03MiB [10.80MiB/sec]     		
UsageError: Upload failed: Can't save bundle, bundle size 88954 greater than user's disk quota left: 1.0
```
When bundle size exceeds the user disk quota left, the program will print an usageerror without the exception reported in this ticket.
