### ISSUE TITLE
MySQL tries to write to wrong directory

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1419]
I get this error when starting:

```
process:     return Connection(*args, **kwargs)
process:   File "/usr/local/lib/python3.6/dist-packages/MySQLdb/connections.py", line 164, in __init__
process:     super(Connection, self).__init__(*args, **kwargs2)
process: MySQLdb._exceptions.OperationalError: (2005, "Unknown MySQL server host 'mysql' (0)")
process: 
process: The above exception was the direct cause of the following exception:
process: 
process: Traceback (most recent call last):
process:   File "scripts/create-root-user.py", line 15, in <module>
process:     model = manager.model()
process:   File "/opt/codalab-worksheets/codalab/lib/codalab_manager.py", line 60, in inner
process:     self.cache[fn.__name__] = fn(self)
process:   File "/opt/codalab-worksheets/codalab/lib/codalab_manager.py", line 341, in model
process:     default_user_info=self.default_user_info(),
process:   File "/opt/codalab-worksheets/codalab/model/mysql_model.py", line 52, in __init__
process:     super(MySQLModel, self).__init__(engine, default_user_info)
process:   File "/opt/codalab-worksheets/codalab/model/bundle_model.py", line 72, in __init__
process:     self.create_tables()
process:   File "/opt/codalab-worksheets/codalab/model/bundle_model.py", line 96, in create_tables
process:     db_metadata.create_all(self.engine)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/schema.py", line 3687, in create_all
process:     tables=tables)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1855, in _run_visitor
process:     with self._optional_conn_ctx_manager(connection) as conn:
process:   File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
process:     return next(self.gen)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1848, in _optional_conn_ctx_manager
process:     with self.contextual_connect() as conn:
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/threadlocal.py", line 64, in contextual_connect
process:     self.pool.connect, connection),
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
process:     e, dialect, self)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
process:     exc_info
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
process:     reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
process:     raise value.with_traceback(tb)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
process:     return fn()
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 376, in connect
process:     return _ConnectionFairy._checkout(self)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 713, in _checkout
process:     fairy = _ConnectionRecord.checkout(pool)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 480, in checkout
process:     rec = pool._do_get()
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 1060, in _do_get
process:     self._dec_overflow()
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
process:     compat.reraise(exc_type, exc_value, exc_tb)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in reraise
process:     raise value
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 1057, in _do_get
process:     return self._create_connection()
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 323, in _create_connection
process:     return _ConnectionRecord(self)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 449, in __init__
process:     self.connection = self.__connect()
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 607, in __connect
process:     connection = self.__pool._invoke_creator(self)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/strategies.py", line 97, in connect
process:     return dialect.connect(*cargs, **cparams)
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
process:     return self.dbapi.connect(*cargs, **cparams)
process:   File "/usr/local/lib/python3.6/dist-packages/MySQLdb/__init__.py", line 84, in Connect
process:     return Connection(*args, **kwargs)
process:   File "/usr/local/lib/python3.6/dist-packages/MySQLdb/connections.py", line 164, in __init__
process:     super(Connection, self).__init__(*args, **kwargs2)
process: sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'mysql' (0)")
```

When doing `docker logs codalab_mysql_1` I get:

```
190924 20:46:47 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
190924 20:46:47 [Note] mysqld (mysqld 5.5.53) starting as process 1 ...
190924 20:46:47 [Warning] Can't create test file /var/lib/mysql/ad269df3e7ed.lower-test
190924 20:46:47 [Warning] Can't create test file /var/lib/mysql/ad269df3e7ed.lower-test
190924 20:46:47 [Note] Plugin 'FEDERATED' is disabled.
mysqld: Can't find file: './mysql/plugin.frm' (errno: 13)
190924 20:46:47 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
190924 20:46:47 InnoDB: The InnoDB memory heap is disabled
190924 20:46:47 InnoDB: Mutexes and rw_locks use GCC atomic builtins
190924 20:46:47 InnoDB: Compressed tables use zlib 1.2.3
190924 20:46:47 InnoDB: Using Linux native AIO
190924 20:46:47 InnoDB: Initializing buffer pool, size = 128.0M
190924 20:46:47 InnoDB: Completed initialization of buffer pool
190924 20:46:47  InnoDB: Operating system error number 13 in a file operation.
InnoDB: The error means mysqld does not have the access rights to
InnoDB: the directory.
InnoDB: File name ./ibdata1
InnoDB: File operation call: 'open'.
InnoDB: Cannot continue operation.
```

It looks like the issue might be that it's trying to write to `/var/lib/mysql` -- so it looks like CODALAB_MYSQL_MOUNT is not being passed to this line?:

https://github.com/codalab/codalab-worksheets/blob/27dd6c8e1cc8cd23625535607f3b7f7553b6a6b8/docker/compose_files/docker-compose.yml#L89

**Comment by epicfaace** [comment]
Never mind, deleting the /var directory made it work. Seems to be some kind of permissions issue
