### ISSUE TITLE
500 error when displaying image

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#1431]
**Describe the bug**
One of my worksheets has stopped loading, and I see that there is a 500 error under the hood.

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 0xc86d3ebe69a3427d91f9aaa63f7d1e7d
- *UUID of problem bundle (please don't delete)*: N/A
- *Error message received from Codalab (if applicable)*: codalab just shows a blank worksheet. Looking at the developer console, there is a 500 error on https://worksheets.codalab.org/rest/interpret/worksheet/0xc86d3ebe69a3427d91f9aaa63f7d1e7d?_=1569552359045
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Chrome (tested normally and in incognito), Firefox

**To Reproduce**
Steps to reproduce the behavior :
1. Go to https://worksheets.codalab.org/worksheets/0xc86d3ebe69a3427d91f9aaa63f7d1e7d/

**Expected behavior**
A full worksheet with a picture and many bundles loads.

**Screenshots**

**Additional context**
Would be great if this can be fixed, as it is the official worksheet for one of my previous papers. Someone recently e-mailed me with a question about the paper, and I want to point them to the worksheet.

**Comment by epicfaace** [comment]
Stack trace on server from the above request:


```
cleanup: data /home/azureuser/codalab-worksheets/var/codalab/home/partitions/codalab9/bundles/0x703dedcef9034b46abf4888d8c298cbf
cleanup: data /home/azureuser/codalab-worksheets/var/codalab/home/partitions/codalab9/bundles/0x94efe0f33a6e47be8ce5556d5f600b9a
2019-09-27 03:34:33,851 Error on request by codalab(0):

GET /interpret/worksheet/0xc86d3ebe69a3427d91f9aaa63f7d1e7d

Query params:
_='1569555266124'

Form params:


JSON body:
<none>

Local variables:
o=b'iVBORw0KGgoAAAANSUhEUgAACJgAAAV4CAYAAADmffVBAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAFxGAABcRgEUlENBAAAAB3RJTUUH4QcVFSM70WTm5AAAgABJREFUeNrs3Xd4FFX78PF70gMklFBD7yBVqdKkSu9dRVCKiIKoICCPgqAiIEgv0gQEFaRXEenSe5XeQyC0ACF9z/sHv+RN2JnJbrLJBvL9XNd9QaacPXOmbJl7ztGUUgIAAAAAAAAAAAAAAAAYcXF2BQAAAAAAAAAAAAAAAJC6kWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAUySYAAAAAAAAAAAAAAAAwBQJJgAAAAAAAAAAAAAAADBFggkAAAAAAAAAAAAAAABMkWACAAAAAAAAAAAAAAAAU27OrgDStpCQEJUhQwZnVwMAAAAAAAAAAADAC0gppTm7DkBaoSmlnF0HpHGapnEQAgAAAAAAAAAAALAbCSZAymGIHAAAAAAAAAAAAAAAAJhiiBykKmQYAgAAAAAAAAAAADDC6AiA89CDCQAAAAAAAAAAAAAAAEyRYAIAAAAAAAAAAAAAAABTJJgAAAAAAAAAAAAAAADAFAkmAAAAAAAAAAAAAAAAMEWCCQAAAAAAAAAAAAAAAEyRYAIAAAAAAAAAAAAAAABTJJgAAAAAAAAAAAAAAADAFAkmAAAAAAAAAAAAAAAAMEWCCQAAAAAAAAAAAAAAAEyRYAIAAAAAAAAAAAAAAABTJJgAAAAAAAAAAAAAAADAFAkmAAAAAAAAAAAAAAAAMEWCCQAAAAAAAAAAAAAAAEyRYAIAAAAAAAAAAAAAAABTJJgAAAAAAAAAAAAAAADAFAkmAAAAAAAAAAAAAAAAMEWCCQAAAAAAAAAAAAAAAEyRYAIAAAAAAAAAAAAAAABTJJgAAAAAAAAAAAAAAADAFAkmAAAAAAAAAAAAAAAAMEWCCQAAAAAAAAAAAAAAAEyRYAIAAAAAAAAAAAAAAABTJJgAAAAAAAAAAAAAAADAFAkmAAAAAAAAAAAAAAAAMEWCCQAAAAAAAAAAAAAAAEyRYAIAAAAAAAAAAAAAAABTJJgAAAAAAAAAAAAAAADAFAkmAAAAAAAAAAAAAAAAMEWCCQAAAAAAAAAAAAAAAEyRYAIAAAAAAAAAAAAAAABTJJgAAAAAAAAAAAAAAADAFAkmAAAAAAAAAAAAAAAAMEWCCQAAAAAAAAAAAAAAAEyRYAIAAAAAAAAAAAAAAABTJJgAAAAAAAAAAAAAAADAFAkmAAAAAAAAAAAAAAAAMEWCCQAAAAAAAAAAAAAAAEyRYAIAAAAA(...truncated...)bt269OKLL0ZExLBhw6KqqqrQDwEAAACgQxOYAAAAAEVvwIABzX7NokWL4uDBg6m6ujrdfffdceTIkYiIePnll6OsrMzlcQAAAAAySlJKhV4HLnElJSU/7YQpJT/QAwAAoNXmz5+fZsyY0erb3XPPPbF06dIoKSnx/SgAAEAROPGzxQifL8KFJDCh4AQmAAAAnK/6+vo0fvz4+Oqrr1p8m4qKivj666+jX79+vhcFAAAoEgITKByXyAEAAACKXllZWcmSJUti3LhxLfr60aNHx5o1a8QlAAAAAC0kMAEAAAAuChUVFSWff/55vPvuu3HjjTee8WvGjBkTb7/9dqxduzauuuoqcQkAAABAC7lEDgXnEjkAAAC0h6NHj6Zvvvkmamtr48orr4zrrrvOGUsAAACKnEvkQOEITCg4gQkAAAAAAADQEgITKByXyAEAAAAAAAAAIEtgAgAAAAAAAABAlsAEAAAAAAAAAIAsgQkAAAAAAAAAAFkCEwAAAAAAAAAAsgQmAAAAAAAAAABkCUwAAAAAAAAAAMgSmAAAAAAAAAAAkCUwAQAAAAAAAAAgS2ACAAAAAAAAAECWwAQAAAAAAAAAgCyBCQAAAAAAAAAAWQITAAAAAAAAAACyBCYAAAAAAAAAAGQJTAAAAAAAAAAAyBKYAAAAAAAAAACQJTABAAAAAAAAACBLYAIAAAAAAAAAQJbABAAAAAAAAACALIEJAAAAAAAAAABZAhMAAAAAAAAAALIEJgAAAAAAAAAAZAlMAAAAAAAAAADIEpgAAAAAAAAAAJAlMAEAAAAAAAAAIEtgAgAAAAAAAABAlsAEAAAAAAAAAIAsgQkAAAAAAAAAAFkCEwAAAAAAAAAAsgQmAAAAAAAAAABkCUwAAAAAAAAAAMgSmAAAAAAAAAAAkCUwAQAAAAAAAAAgS2ACAAAAAAAAAECWwAQAAAAAAAAAgCyBCQAAAAAAAAAAWQITAAAAAAAAAACyBCYAAAAAAAAAAGQJTAAAAAAAAAAAyBKYAAAAAAAAAACQJTABAAAAAAAAACBLYAIAAAAAAAAAQJbABAAAAAAAAACALIEJAAAAAAAAAABZAhMAAAAAAAAAALIEJgAAAAAAAAAAZAlMAAAAAAAAAADIEpgAAAAAAAAAAJAlMAEAAAAAAAAAIEtgAgAAAAAAAABAlsAEAAAAAAAAAIAsgQkAAAAAAAAAAFkCEwAAAAAAAAAAsgQmAAAAAAAAAABkCUwAAAAAAAAAAMgSmAAAAAAAAAAAkCUwAQAAAAAAAAAgS2ACAAAAAAAAAECWwAQAAAAAAAAAgCyBCQAAAAAAAAAAWQITAAAAAAAAAACyBCYAAAAAAAAAAGQJTAAAAAAAAAAAyBKYAAAAAAAAAACQJTABAAAAAAAAACBLYAIAAAAAAAAAQJbABAAAAAAAAACALIEJAAAAAAAAAABZAhMAAAAAAAAAALIEJgAAAAAAAAAAZAlMAAAAAAAAAADIEpgAAAAAAAAAAJAlMAEAAAAAAAAAIKu00CvApe3w4cPpxD+XlJSkc70vAAAAAAAAAKB9lKTk83wKS1QCAAAAAAAAnIuUUkmh1wEuFS6RAwAAAAAAAABAlsAEAAAAAAAAAIAsl8gBAAAAAAAAACDLGUwAAAAAAAAAAMgSmAAAAAAAAAAAkCUwAQAAAAAAAAAgS2ACAAAAAAAAAECWwAQAAAAAAAAAgCyBCQAAAAAAAAAAWQITAAAAAAAAAACyBCYAAAAAAAAAAGQJTAAAAAAAAAAAyBKYAAAAAAAAAACQJTABAAAAAAAAACBLYAIAAAAAAAAAQJbABAAAAAAAAACALIEJAAAAAAAAAABZAhMAAAAAAAAAALIEJgAAAAAAAAAAZAlMAAAAAAAAAADIEpgAAAAAAAAAAJAlMAEAAAAAAAAAIEtgAgAAAAAAAABAlsAEAAAAAAAAAIAsgQkAAAAAAAAAAFkCEwAAAAAAAAAAsgQmAAAAAAAAAABkCUwAAAAAAAAAAMgSmAAAAAAAAAAAkCUwAQAAAAAAAAAgS2ACAAAAAAAAAECWwAQAAAAAAAAAgCyBCQAAAAAAAAAAWQITAAAAAAAAAACyBCYAAAAAAAAAAGQJTAAAAAAAAAAAyBKYAAAAAAAAAACQJTABAAAAAAAAACBLYAIAAAAAAAAAQJbABAAAAAAAAACALIEJAAAAAAAAAABZAhMAAAAAAAAAALIEJgAAAAAAAAAAZAlMAAAAAAAAAADIEpgAAAAAAAAAAJD1P+WKfgZ4+fvnAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE3LTA3LTIxVDE0OjM1OjQ2LTA3OjAwoaMtUwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxNy0wNy0yMVQxNDozNTo0Ni0wNzowMND+le8AAAAASUVORK5CYII='
self=<codalab.server.rest_server.DatetimeEncoder object at 0x7ff0f6fe3d30>

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 106, in wrapper
    return callback(*args, **kwargs)
  File "/usr/local/bin/bottle.py", line 1738, in wrapper
    json_response = dumps(rv)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 197, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 106, in wrapper
    return callback(*args, **kwargs)
  File "/usr/local/bin/bottle.py", line 1738, in wrapper
    json_response = dumps(rv)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 197, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 72, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 91, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/server/oauth2_provider.py", line 517, in decorated
    return f(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/server/cookie.py", line 99, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/server/authenticated_plugin.py", line 28, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/server/authenticated_plugin.py", line 44, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 112, in wrapper
    self.report_exception(e)
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 169, in report_exception
    self.send_email(exc, message)
  File "/opt/codalab-worksheets/codalab/lib/server_util.py", line 75, in rate_limited_function
    raise RateLimitExceededError
codalab.lib.server_util.RateLimitExceededError
```

**Comment by epicfaace** [comment]
The issue seems to be caused by displaying the image -- minimal code to reproduce this:

```
% display image / width=800
[dataset worksheets-schema.png]{0x466cd19aeb204b59a13b213289de795a}
```

**Comment by epicfaace** [comment]
@robinjia the fix is deployed to prod, so the above worksheet should now be working. Thanks for reporting the issue!
