### ISSUE TITLE
worker crashing due to container_start_time not existing

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1495]
On prod gpuworker-1, am getting:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 51, in start
    self._run_manager.process_runs()
  File "/opt/codalab/worker/local_run/local_run_manager.py", line 173, in process_runs
    self._runs[bundle_uuid] = self._run_state_manager.transition(run_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/local_run/local_run_state.py", line 386, in _transition_from_RUNNING
    run_state = check_resource_utilization(run_state)
  File "/opt/codalab/worker/local_run/local_run_state.py", line 320, in check_resource_utilization
    container_time_total = time.time() - run_state.container_start_time
AttributeError: 'RunState' object has no attribute 'container_start_time'

**Comment by percyliang** [comment]
Related to @bkgoksel 's commit 294d5f35418ede2909bdfc416d00f6f13c7f8fea?

**Comment by yipenghe** [comment]
It was caused by the workers having out-of-date run-state.json after upgrading, not sure why it wasn't cleaned for last deployment, they tried to resume jobs with out-of-date run-state.json but crushed because the mismatch fields.  I checked the prod workers' run-state.json just now and they are having the correct run-state.json and this error should be gone now.
