### ISSUE TITLE
Failing worker: 'RunState' object has no attribute 'container_start_time'

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1497]
Here is the error message from worker machine (gpu1):
```
2019-10-11 17:42:03,179 http://localhost:None "GET /v1.35/containers/f65b648c192d6b1ba6105ee976472588ba8abd01a06335cb13e2f436c651f41f/json HTTP/1.1" 404 98
2019-10-11 17:42:03,179 Error getting the container for the run: 404 Client Error: Not Found ("No such container: f65b648c192d6b1ba6105ee976472588ba8abd01a06335cb13e2f436c651f41f")
2019-10-11 17:42:03,179 Starting docker image manager
2019-10-11 17:42:03,185 Starting local dependency manager
Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 51, in start
    self._run_manager.process_runs()
  File "/opt/codalab/worker/local_run/local_run_manager.py", line 173, in process_runs
    self._runs[bundle_uuid] = self._run_state_manager.transition(run_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/local_run/local_run_state.py", line 386, in _transition_from_RUNNING
    run_state = check_resource_utilization(run_state)
  File "/opt/codalab/worker/local_run/local_run_state.py", line 320, in check_resource_utilization
    container_time_total = time.time() - run_state.container_start_time
AttributeError: 'RunState' object has no attribute 'container_start_time'
2019-10-11 17:42:03,334 Sleeping for 1 hour due to exception...please help me!
```

From gpu2:
```
2019-10-11 15:41:55,839 Sleeping for 1 hour due to exception...please help me!
Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 53, in start
    self._checkin()
  File "/opt/codalab/worker/worker.py", line 93, in _checkin
    'runs': self._run_manager.all_runs,
  File "/opt/codalab/worker/local_run/local_run_manager.py", line 338, in all_runs
    for bundle_uuid, run_state in self._runs.items()
  File "/opt/codalab/worker/local_run/local_run_manager.py", line 338, in <dictcomp>
    for bundle_uuid, run_state in self._runs.items()
AttributeError: 'RunState' object has no attribute 'bundle_start_time'
2019-10-11 16:41:56,075 Sleeping for 1 hour due to exception...please help me!
```

From gpu6:
```
Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 51, in start
    self._run_manager.process_runs()
  File "/opt/codalab/worker/local_run/local_run_manager.py", line 173, in process_runs
    self._runs[bundle_uuid] = self._run_state_manager.transition(run_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/local_run/local_run_state.py", line 268, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/opt/codalab/worker/docker_utils.py", line 32, in wrapper
    raise DockerException(message + ': ' + str(e))
codalab.worker.docker_utils.DockerException: Unable to start Docker container: Minimum memory must be 4m (4194304 bytes)
2019-10-11 17:18:53,908 Sleeping for 1 hour due to exception...please help me!
```

**Comment by candicegjing** [comment]
Debugged gpu1 worker in function `_transition_from_RUNNING`:
```
2019-10-11 18:21:52,775  Check: run_state = check_and_report_finished(run_state)
2019-10-11 18:21:52,775 RunState(stage='LOCAL_RUN.RUNNING', run_status='Running job in Docker container', bundle={'data_hash': None, 'uuid': '0x15d69e56052448b0ac226e9f26bc345c', 'is_anonymous': False, 'args': 'run src:0xdb199ff7cdda4598bb1ce5128c292f6d cl:0xa7d9e1032f66421c8e5a35c5b6cf3282 data-mnli:0x5258e3771b974983abfb10bfa75e207d "bash cl/link_data.sh; bash cl/run_credit_assignment.sh" --request-memory 32g --request-cpus 1 --request-gpus 1 --request-docker-image bbbert/influence:5', 'state': 'starting', 'dependencies': [{'parent_path': '', 'child_uuid': '0x15d69e56052448b0ac226e9f26bc345c', 'parent_uuid': '0xdb199ff7cdda4598bb1ce5128c292f6d', 'child_path': 'src', 'parent_name': 'src'}, {'parent_path': '', 'child_uuid': '0x15d69e56052448b0ac226e9f26bc345c', 'parent_uuid': '0xa7d9e1032f66421c8e5a35c5b6cf3282', 'child_path': 'cl', 'parent_name': 'cl'}, {'parent_path': '', 'child_uuid': '0x15d69e56052448b0ac226e9f26bc345c', 'parent_uuid': '0x5258e3771b974983abfb10bfa75e207d', 'child_path': 'data-mnli', 'parent_name': 'data-mnli'}], 'command': 'bash cl/link_data.sh; bash cl/run_credit_assignment.sh', 'bundle_type': 'run', 'owner_id': '0xe18f396561f44762b7d0bdb11b7d51da', 'metadata': {'allow_failed_dependencies': False, 'last_updated': 1570361554, 'description': '', 'request_network': False, 'request_memory': '32g', 'tags': [], 'request_docker_image': 'bbbert/influence:5', 'actions': [], 'created': 1570160646, 'request_time': '', 'request_queue': '', 'request_cpus': 1, 'request_disk': '', 'request_priority': 0, 'request_gpus': 1, 'name': 'credit-assignment'}}, bundle_path='/mnt/scratch/bundles/runs/0x15d69e56052448b0ac226e9f26bc345c', resources={'request_time': 0, 'request_network': False, 'request_memory': 34359738368, 'request_cpus': 1, 'request_disk': 0, 'docker_image': 'bbbert/influence:5', 'request_gpus': 1}, start_time=1570361664.635176, container=None, container_id=None, docker_image='bbbert/influence@sha256:5cb982722176c3eb4b9186671d55307990a5b49899451b65b23eea7d5a557113', is_killed=False, has_contents=True, cpuset={'0'}, gpuset={'GPU-91e16e4e-ff09-b3d4-6957-e935a32bd772'}, time_used=75939.26582098007, max_memory=0, disk_utilization=54992338, info={'finished': False, 'failure_message': None, 'exitcode': None})
2019-10-11 18:21:52,781 Check run_state = check_resource_utilization(run_state)
2019-10-11 18:21:52,781 RunState(stage='LOCAL_RUN.RUNNING', run_status='Running job in Docker container', bundle={'data_hash': None, 'uuid': '0x15d69e56052448b0ac226e9f26bc345c', 'is_anonymous': False, 'args': 'run src:0xdb199ff7cdda4598bb1ce5128c292f6d cl:0xa7d9e1032f66421c8e5a35c5b6cf3282 data-mnli:0x5258e3771b974983abfb10bfa75e207d "bash cl/link_data.sh; bash cl/run_credit_assignment.sh" --request-memory 32g --request-cpus 1 --request-gpus 1 --request-docker-image bbbert/influence:5', 'state': 'starting', 'dependencies': [{'parent_path': '', 'child_uuid': '0x15d69e56052448b0ac226e9f26bc345c', 'parent_uuid': '0xdb199ff7cdda4598bb1ce5128c292f6d', 'child_path': 'src', 'parent_name': 'src'}, {'parent_path': '', 'child_uuid': '0x15d69e56052448b0ac226e9f26bc345c', 'parent_uuid': '0xa7d9e1032f66421c8e5a35c5b6cf3282', 'child_path': 'cl', 'parent_name': 'cl'}, {'parent_path': '', 'child_uuid': '0x15d69e56052448b0ac226e9f26bc345c', 'parent_uuid': '0x5258e3771b974983abfb10bfa75e207d', 'child_path': 'data-mnli', 'parent_name': 'data-mnli'}], 'command': 'bash cl/link_data.sh; bash cl/run_credit_assignment.sh', 'bundle_type': 'run', 'owner_id': '0xe18f396561f44762b7d0bdb11b7d51da', 'metadata': {'allow_failed_dependencies': False, 'last_updated': 1570361554, 'description': '', 'request_network': False, 'request_memory': '32g', 'tags': [], 'request_docker_image': 'bbbert/influence:5', 'actions': [], 'created': 1570160646, 'request_time': '', 'request_queue': '', 'request_cpus': 1, 'request_disk': '', 'request_priority': 0, 'request_gpus': 1, 'name': 'credit-assignment'}}, bundle_path='/mnt/scratch/bundles/runs/0x15d69e56052448b0ac226e9f26bc345c', resources={'request_time': 0, 'request_network': False, 'request_memory': 34359738368, 'request_cpus': 1, 'request_disk': 0, 'docker_image': 'bbbert/influence:5', 'request_gpus': 1}, start_time=1570361664.635176, container=None, container_id=None, docker_image='bbbert/influence@sha256:5cb982722176c3eb4b9186671d55307990a5b49899451b65b23eea7d5a557113', is_killed=False, has_contents=True, cpuset={'0'}, gpuset={'GPU-91e16e4e-ff09-b3d4-6957-e935a32bd772'}, time_used=75939.26582098007, max_memory=0, disk_utilization=54992338, info={'finished': True, 'failure_message': 'Docker container not found', 'exitcode': None})
```
There is no attr `container_start_time` in `RunState` object.
