### ISSUE TITLE
desugar_command:  error concatenating 'NoneType' and 'str' 

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1500]
```
POST /cli/command

Query params:


Form params:


JSON body:
{
    "command": "cl run : :src 'python src/predict.py < valid_image_paths.csv'",
    "worksheet_uuid": "0x5b880b4b3bf44d56911789b4adeca28b"
}

Local variables:
subpath=None
bundle=None
_=None
val=''
key=None
dep=':'
val2key={'': None}
target_spec=[]
key2val={None: ''}

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 106, in wrapper
    return callback(*args, **kwargs)
  File "/usr/local/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/opt/codalab-worksheets/codalab/server/json_api_plugin.py", line 18, in wrapper
    result = callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/rest/cli.py", line 48, in post_worksheets_command
    return general_command(query['worksheet_uuid'], query['command'])
  File "/opt/codalab-worksheets/codalab/rest/cli.py", line 149, in general_command
    structured_result = cli.do_command(args)
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 852, in do_command
    structured_result = command_fn()
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 846, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 1518, in do_run_command
    args.target_spec, args.command = desugar_command(args.target_spec, args.command)
  File "/opt/codalab-worksheets/codalab/lib/cli_util.py", line 118, in desugar_command
    get(spec)
  File "/opt/codalab-worksheets/codalab/lib/cli_util.py", line 113, in get
    target_spec.append(key + ':' + val)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by candicegjing** [comment]
The user has a dependency specified in his/her command which didn't have a valid value around ":", which caused the problem. Currently, the error was caught by https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/rest_server.py#L113.

**Comment by yipenghe** [comment]
> The user has a dependency specified in his/her command which didn't have a valid value around ":", which caused the problem. Currently, the error was caught by https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/rest_server.py#L113.

So essentially it was due to a incorrectly inputted cmd?

**Comment by yipenghe** [comment]
Looks more like a command line input error rather than on our side

**Comment by percyliang** [comment]
We should fail more gracefully...return a nice message to the user and not throw an exception that causes an email to be sent.

**Comment by bkgoksel** [comment]
Wow, I worked on this back in the day, and I think I added cases for where either side of the colon would be omitted, but never imagined someone would add a single colon that's empty on both sides...
