### ISSUE TITLE
Support Unicode in paths for cl upload

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#153]
ASCII limitations on bundle names are fine, but we should be able to upload a file at any path.

Currently:
`>> cl upload dataset 濛嶺.doc -n mmm.doc`

```
 BundleStore.upload: moving /Users/sckoo/.codalab/temp/bfb5ba178c954f498d3e37bab4ff07e3 to /Users/sckoo/.codalab/data/0x63eb97b12de30a477f255d3573709c3b2f2f55e9
Traceback (most recent call last):
  File "/Users/sckoo/Developer/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 66, in <module>
    run_cli()
  File "/Users/sckoo/Developer/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 57, in run_cli
    cli.do_command(sys.argv[1:])
  File "/Users/sckoo/Developer/codalab-cli/codalab/lib/bundle_cli.py", line 359, in do_command
    command_fn(remaining_args, parser)
  File "/Users/sckoo/Developer/codalab-cli/codalab/lib/bundle_cli.py", line 515, in do_upload_command
    print client.upload_bundle(args.path, {'bundle_type': args.bundle_type, 'metadata': metadata}, worksheet_uuid, args.follow_symlinks, args.exclude_patterns, True)
  File "/Users/sckoo/Developer/codalab-cli/codalab/client/local_bundle_client.py", line 55, in decorate
    return func(self, *args, **kwargs)
  File "/Users/sckoo/Developer/codalab-cli/codalab/client/local_bundle_client.py", line 209, in upload_bundle
    self.model.save_bundle(bundle)
  File "/Users/sckoo/Developer/codalab-cli/codalab/model/bundle_model.py", line 587, in save_bundle
    bundle_value = bundle.to_dict()
  File "/Users/sckoo/Developer/codalab-cli/codalab/objects/bundle.py", line 82, in to_dict
    result['metadata'] = self.metadata.to_dicts(self.METADATA_SPECS)
  File "/Users/sckoo/Developer/codalab-cli/codalab/objects/metadata.py", line 96, in to_dicts
    'metadata_value': unicode(value),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 55: ordinal not in range(128)
```

**Comment by percyliang** [comment]
This works now...weird characters are replaced with _.
