### ISSUE TITLE
[USER ISSUE] Strange failure message with slurm worker on one specific bundle

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#1535]
**Describe the bug**
I consistently encounter a strange slurm worker bug when I try to run one very specific bundle. A very similar bundle used to work in the past.

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 0x71683307485546dc8a41dea246f7cea2
- *UUID of problem bundle (please don't delete)*: 0x6be2345a401f4c659c4c51421f979c0c
- *Error message received from Codalab (if applicable)*:
```
2019-10-17 20:45:09,830 http://localhost:None "POST /v1.35/containers/d1e5d469fb969ba14f9280ec1a703718263cf9ae18d69
ce3d6fb551206be81c9/start HTTP/1.1" 500 776
2019-10-17 20:45:09,831 Cannot start Docker container: Unable to start Docker container: 500 Server Error: Internal
 Server Error ("OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux
.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/l
dconfig.real --device=GPU-00803a7c-75e8-0a5d-1c31-533536873fa6 --compute --utility --require=cuda>=10.1 brand=tesla
,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 --pid=2138 /jagupard17/scr1/docker/overlay2/5c72ee7c77825b8d0794e9a64e9b227673ea375dff3d062bf3f3beb2c32993b9/merged]\\\\nnvidia-containe
r-cli: requirement error: invalid expression\\\\n\\\"\"": unknown")
2019-10-17 20:45:09,839 Traceback (most recent call last):
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/api/client.py", line 256, 
in _raise_for_status
    response.raise_for_status()
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/requests/models.py", line 940, in
 raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/conta
iners/d1e5d469fb969ba14f9280ec1a703718263cf9ae18d69ce3d6fb551206be81c9/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/codalab/worker/docker_utils.py", 
line 30, in wrapper
    return f(*args, **kwargs)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 161, in start_bundle_container
    stdin_open=tty,
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/models/containers.py", lin
e 791, in run
    container.start()
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/models/containers.py", lin
e 392, in start
    return self.client.api.start(self.id, **kwargs)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/utils/decorators.py", line
 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/api/container.py", line 10
91, in start
    self._raise_for_status(res)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/api/client.py", line 258, 
in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/errors.py", line 31, in cr
eate_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("OCI runtime create failed: container_linux.go:344
: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running pr
estart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-contai
ner-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=GPU-00803a7c-75e8-0a5d-1c31-533536873fa6 --
compute --utility --require=cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=
tesla,driver>=410,driver<411 --pid=2138 /jagupard17/scr1/docker/overlay2/5c72ee7c77825b8d0794e9a64e9b227673ea375dff
3d062bf3f3beb2c32993b9/merged]\\\\nnvidia-container-cli: requirement error: invalid expression\\\\n\\\"\"": unknown")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/codalab/worker/local_run/local_ru
n_state.py", line 268, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/codalab/worker/docker_utils.py", 
line 34, in wrapper
    raise DockerException(message + ': ' + str(e))
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 500 Server Error: Internal Server Er
ror ("OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: c
ontainer init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, 
stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.re
al --device=GPU-00803a7c-75e8-0a5d-1c31-533536873fa6 --compute --utility --require=cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 --pid=2138 /jagupard17/scr1/doc
ker/overlay2/5c72ee7c77825b8d0794e9a64e9b227673ea375dff3d062bf3f3beb2c32993b9/merged]\\\\nnvidia-container-cli: req
uirement error: invalid expression\\\\n\\\"\"": unknown")

Traceback (most recent call last):
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/api/client.py", line 256, 
in _raise_for_status
    response.raise_for_status()
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/requests/models.py", line 940, in
 raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/conta
iners/d1e5d469fb969ba14f9280ec1a703718263cf9ae18d69ce3d6fb551206be81c9/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/codalab/worker/docker_utils.py", 
line 30, in wrapper
    return f(*args, **kwargs)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 161, in start_bundle_container
    stdin_open=tty,
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/models/containers.py", line 791, in run
    container.start()
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/models/containers.py", lin
e 392, in start
    return self.client.api.start(self.id, **kwargs)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/utils/decorators.py", line
 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/api/container.py", line 10
91, in start
    self._raise_for_status(res)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/api/client.py", line 258, 
in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/docker/errors.py", line 31, in cr
eate_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("OCI runtime create failed: container_linux.go:344
: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-contai
ner-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=GPU-00803a7c-75e8-0a5d-1c31-533536873fa6 --
compute --utility --require=cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=
tesla,driver>=410,driver<411 --pid=2138 /jagupard17/scr1/docker/overlay2/5c72ee7c77825b8d0794e9a64e9b227673ea375dff
3d062bf3f3beb2c32993b9/merged]\\\\nnvidia-container-cli: requirement error: invalid expression\\\\n\\\"\"": unknown
")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/codalab/worker/worker.py", line 5
5, in start
    self._run_manager.process_runs()
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/codalab/worker/local_run/local_ru
n_manager.py", line 174, in process_runs
    self._runs[bundle_uuid] = self._run_state_manager.transition(run_state)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/codalab/worker/fsm.py", line 35, 
in transition
    return self._transition_functions[state.stage](state)
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/codalab/worker/local_run/local_ru
n_state.py", line 268, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/u/nlp/anaconda/ubuntu_16/envs/py368-robinjia/lib/python3.6/site-packages/codalab/worker/docker_utils.py", 
line 34, in wrapper
    raise DockerException(message + ': ' + str(e))
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 500 Server Error: Internal Server Er
ror ("OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, 
stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.re
al --device=GPU-00803a7c-75e8-0a5d-1c31-533536873fa6 --compute --utility --require=cuda>=10.1 brand=tesla,driver>=3
84,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 --pid=2138 /jagupard17/scr1/doc
ker/overlay2/5c72ee7c77825b8d0794e9a64e9b227673ea375dff3d062bf3f3beb2c32993b9/merged]\\\\nnvidia-container-cli: req
uirement error: invalid expression\\\\n\\\"\"": unknown")
2019-10-17 20:45:09,842 Sleeping for 1 hour due to exception...please help me!
```

 - *OS (if on CLI)*: I'm on the Stanford NLP cluster jagupard machines (happened both on jagupard17 and jagupard25)
 - *Codalab CLI Version (if on CLI)*: 0.4.5
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :
1. Start a slurm worker on jagupard machines
2. Run the provided bundle on that worker

**Expected behavior**
It should just run normally.

**Additional context**
As mentioned above, I found this on two different machines. I also tried clearing the `codalab-worker-scratch` directory but that did not help.

**Comment by percyliang** [comment]
Slurm worker will be completely changed, so closing this for now.
