### ISSUE TITLE
Issue during release of 0.4.6 version: KeyError exception on workers

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1547]
```
Traceback (most recent call last):
  File "/usr/local/bin/cl-worker", line 11, in <module>
    load_entry_point('codalab', 'console_scripts', 'cl-worker')()
  File "/opt/codalab/worker/main.py", line 218, in main
    worker.start()
  File "/opt/codalab/worker/worker.py", line 50, in start
    self._run_manager.start()
  File "/opt/codalab/worker/local_run/local_run_manager.py", line 127, in start
    self.load_state()
  File "/opt/codalab/worker/local_run/local_run_manager.py", line 120, in load_state
    resources=RunResources.from_dict(run_state.resources),
  File "/opt/codalab/worker/bundle_state.py", line 146, in from_dict
    cpus=int(dct["cpus"]),
KeyError: 'cpus'
```

**Comment by bkgoksel** [comment]
4.6 would also be a breaking change to the worker system, so the workers should be created fresh (with no ongoing runs or cached state files)
If there are issues after updating both and setting them fresh, we should look into this more.

**Comment by candicegjing** [comment]
Yes, I tested 4.6 locally and didn't find anything wrong. But when it was released to staging/prod, it started to crash.

**Comment by bkgoksel** [comment]
Since this error is in the `load_state` method call of the local run manager, my guess is that there's an old `run-state.json` file on the worker machine. Pruning all the state files and restarting with up-to-date workers should fix this issue.
