### ISSUE TITLE
SQL DELETE exception

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1550]
Production database throws the following exception:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 198, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 304, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/connections.py", line 217, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`codalab_bundles`.`worker_run`, CONSTRAINT `worker_run_ibfk_3` FOREIGN KEY (`run_uuid`) REFERENCES `bundle` (`uuid`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 106, in wrapper
    return callback(*args, **kwargs)
  File "/usr/local/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/opt/codalab-worksheets/codalab/server/json_api_plugin.py", line 18, in wrapper
    result = callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/server/authenticated_plugin.py", line 72, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/rest/bundles.py", line 339, in _delete_bundles
    uuids, force=force, recursive=recursive, data_only=data_only, dry_run=dry_run
  File "/opt/codalab-worksheets/codalab/rest/bundles.py", line 814, in delete_bundles
    local.model.delete_bundles(relevant_uuids)
  File "/opt/codalab-worksheets/codalab/model/bundle_model.py", line 990, in delete_bundles
    connection.execute(cl_bundle.delete().where(cl_bundle.c.uuid.in_(uuids)))
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 198, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 304, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/connections.py", line 217, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`codalab_bundles`.`worker_run`, CONSTRAINT `worker_run_ibfk_3` FOREIGN KEY (`run_uuid`) REFERENCES `bundle` (`uuid`))') [SQL: 'DELETE FROM bundle WHERE bundle.uuid IN (%s, %s, ..., %s, %s)'] [parameters: ('0x31602392f2c84d2fb21f23fa35818911', '0x8c127a4c536a4e13afc5e72354869520', '0x68ae620742474e8e9b00447c3a57f44a', ..., '0x9508649d3ba845ada7c292ea41fcc764')]
```

**Comment by candicegjing** [comment]
`worker_run.run_uuid` is currently referenced as `foreign key` of `bundle` table. This foreign key constraint lets data being consistent over different tables and that’s also the reason why we could not drop the parent before the child. When we delete the `uuid` from `bundle` table, no action was performed on `worker_run` table, which is considered as child table of `bundle` table. Hence, MySql throws an IntegrityError exception complaining about the deletion operation. 
To solve this, we need to drop tables in the correct order (child table first, parent table as the last one) at here: https://github.com/codalab/codalab-worksheets/blob/master/codalab/model/bundle_model.py#L970-L984.
