### ISSUE TITLE
numbering scheme off when we have missing bundles

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#157]
Create a worksheet with a real bundle and a missing bundle (cl wedit and add a fake bundle uuid).

Then `cl info ^1` will refer to the real bundle rather than the missing one, but `cl ls` will show that ^1 refers to the missing one.  Super confusing!

**Comment by kashizui** [comment]
Should `cl info ^1` still refer to the real bundle, or should the the `cl ls` output be fixed to reflect that a bundle is missing?

**Comment by percyliang** [comment]
I think it's good to show the missing bundle in cl ls.  So ^1 should refer
to the first bundle from the end, even if it is missing.

**Comment by kashizui** [comment]
And so `cl info ^1` would throw some sort of error?

**Comment by percyliang** [comment]
Yes.

**Comment by kashizui** [comment]
Got it, thanks!

**Comment by kashizui** [comment]
Is this error expected if there is a missing bundle on the worksheet, or should it be caught/handled?

```
Traceback (most recent call last):
  File "/Users/sckoo/Developer/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 66, in <module>
    run_cli()
  File "/Users/sckoo/Developer/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 57, in run_cli
    cli.do_command(sys.argv[1:])
  File "/Users/sckoo/Developer/codalab-cli/codalab/lib/bundle_cli.py", line 375, in do_command
    structured_result = command_fn(remaining_args, parser)
  File "/Users/sckoo/Developer/codalab-cli/codalab/lib/bundle_cli.py", line 873, in do_ls_command
    reference_map = self.create_reference_map('bundle', bundle_info_list)
  File "/Users/sckoo/Developer/codalab-cli/codalab/lib/bundle_cli.py", line 858, in create_reference_map
    } for info in info_list
  File "/Users/sckoo/Developer/codalab-cli/codalab/lib/bundle_cli.py", line 858, in <dictcomp>
    } for info in info_list
KeyError: 'name'
```

**Comment by kashizui** [comment]
ah I see that it's related to the new create_reference_map code
