### ISSUE TITLE
Ghost bundles in bundle manager logs

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1572]
The bundle manager logs on the prod deployment have a lot of the following:
```
2018-12-05 20:58:40,014 Staging 0xcfb93b0d50524a7581967ca3d35e7d1b
2018-12-05 20:58:54,983 Starting run bundle 0xcfb93b0d50524a7581967ca3d35e7d1b
2018-12-05 20:59:31,290 Acknowleded finalization of run bundle 0xcfb93b0d50524a7581967ca3d35e7d1b
Traceback (most recent call last):
  File "/opt/codalab-cli/codalab/worker/bundle_manager.py", line 68, in run
    self._run_iteration()
  File "/opt/codalab-cli/codalab/worker/bundle_manager.py", line 88, in _run_iteration
    self._schedule_run_bundles()
  File "/opt/codalab-cli/codalab/worker/default_bundle_manager.py", line 37, in _schedule_run_bundles
    self._schedule_run_bundles_on_workers(workers, user_owned=False)
  File "/opt/codalab-cli/codalab/worker/bundle_manager.py", line 316, in _schedule_run_bundles_on_workers
    workers_list = self._filter_and_sort_workers(workers_list, bundle)
  File "/opt/codalab-cli/codalab/worker/bundle_manager.py", line 348, in _filter_and_sort_workers
    self._deduct_worker_resources(workers_list)
  File "/opt/codalab-cli/codalab/worker/bundle_manager.py", line 330, in _deduct_worker_resources
    bundle = self._model.get_bundle(uuid)
  File "/opt/codalab-cli/codalab/model/bundle_model.py", line 144, in get_bundle
    raise NotFoundError('Could not find bundle with uuid %s' % (uuid,))
NotFoundError: Could not find bundle with uuid 0xcfb93b0d50524a7581967ca3d35e7d1b
```

**Comment by bkgoksel** [comment]
This is really an issue in the `deduct_worker_resources` call in the bundle manager, where a bundle might get deleted after the workers list is fetched and before we attempt to get its resources usage to deduct from that worker. Adding an existence check at that point in the code should be a temporary fix to this.
