### ISSUE TITLE
My worksheet seems to be down

### ISSUE THREAD

**Issue by tummykung** [codalab/codalab-worksheets#165]
My worksheet seems to be down. The only word I see there is `bundle_type`. Could someone help? Thanks!

https://worksheets.codalab.org/worksheets/0x610bcdb722bf48d3b537a65edf0fe72d/  

name	bohemian-rhapsody-nips2015
uuid	0x610bcdb722bf48d3b537a65edf0fe72d
owner	sorathan
permissions	you(?) public(undefined)

**Comment by kashizui** [comment]
Seeing this on the rest server logs:

```
Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/codalab/server/rest_server.py", line 130, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 432, in get_worksheet_content
    return service.full_worksheet(uuid)
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 150, in full_worksheet
    if bundle_info['bundle_type'] != PrivateBundle.BUNDLE_TYPE:
KeyError: 'bundle_type'
```

**Comment by kashizui** [comment]
The problem was a reference to a nonexistent bundle uuid on the worksheet. Fixed this specific worksheet and re-orienting this issue.
