### ISSUE TITLE
Prod worker can not be started due to "exec: \"bash\": executable file not found in $PATH": unknown"

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1704]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 56, in start
    self._run_manager.process_runs()
  File "/opt/codalab/worker/local_run/local_run_manager.py", line 190, in process_runs
    self._runs[bundle_uuid] = self._run_state_manager.transition(run_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/local_run/local_run_state.py", line 292, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/opt/codalab/worker/docker_utils.py", line 34, in wrapper
    raise DockerException(message + ': ' + str(e))
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 409 Client Error: Conflict ("Conflict. The container name "/codalab_run_0xc2559ab6e42f446b9beea50c74c1222f" is already in use by container "3d823a5f30232fb833b193da2d8839d380ac8c16114b60f0cc8f007caf4d10f7". You have to remove (or rename) that container to be able to reuse that name.")
2019-11-21 02:20:18,429 Sleeping for 1 hour due to exception...please help me!
```
This issue might need some investigation as I saw it several times in production.

**Comment by candicegjing** [comment]
After manually removed the container with the same name, the original container returns the following error message:
```
 File "/opt/codalab/worker/local_run/local_run_manager.py", line 190, in process_runs
    self._runs[bundle_uuid] = self._run_state_manager.transition(run_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/local_run/local_run_state.py", line 292, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/opt/codalab/worker/docker_utils.py", line 34, in wrapper
    raise DockerException(message + ': ' + str(e))
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 
500 Server Error: Internal Server Error ("OCI runtime create failed: container_linux.go:345: starting container process caused 
"process_linux.go:424: container init caused \
"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --utility --pid=52899 /mnt/scratch/docker/overlay2/70b6608e9bbda7abb8295f31449ed6be9557bd6a3a161f2941d4184cccac938e/merged]\\\\nnvidia-container-cli: mount error: file creation failed: /mnt/scratch/docker/overlay2/70b6608e9bbda7abb8295f31449ed6be9557bd6a3a161f2941d4184cccac938e/merged/usr/bin/nvidia-smi: file exists\\\\n\\\"\"": unknown")
2019-11-23 00:10:59,671 Sleeping for 1 hour due to exception...please help me!
```

**Comment by candicegjing** [comment]
I tried to remove the mounting directory mentioned in the error message and then restarted the worker, but it still kept failing because of the similar issue. Then I found this: [Nvidia-Docker](https://github.com/NVIDIA/nvidia-docker/issues/825.) Based on their discussion, it seems that this issue is caused by running a container in a GPU-based instance with Nvidia drivers/toolset/etc. already installed.

**Comment by candicegjing** [comment]
@bkgoksel Let me know if you have any suggestions.

**Comment by bkgoksel** [comment]
Reading the issue you linked this looks like a user error and not something we can fix on our end technically. 

*Details:*

I see that the run with UUID 0xc2559ab6e42f446b9beea50c74c1222f (the one mentioned in this issue) is using a custom docker image provided by the user. Reading the issue you linked it sounds like they installed a bunch of NVIDIA packages into their Docker image that they were not supposed to. 

Since we don't control what users do with their own docker images, there's not much we can do about this except for trying to catch it when it happens and throw a helpful error message.

I would focus on a way to catch this particular error and maybe a link to that GitHub issue or something as part of the error message.

**Comment by bkgoksel** [comment]
Another question: did this ever happen with the default codalab-supplied docker image? If so, we should make sure to fix that.

Also another bug here is that the container failing to start somehow leads to the worker trying to recreate a container with the same name rather than catching and failing the bundle. That's bad.

**Comment by candicegjing** [comment]
@bkgoksel Thanks for looking at this issue! I personally think there are two issues here:
1. Conflict in container naming.
2. Nvidia-Docker related issue.

I feel the second problem looks like a user issue. I just don't have an idea about the first one. It sounds like there could be a duplicate UUID when the worker tries to start the container. But I need to investigate more about this. Could you please point me to the place where we generate the UUID number?

**Comment by percyliang** [comment]
Is not happening anymore organically...try to reproduce this on dev with a stress test.

**Comment by candicegjing** [comment]
Saw this issue again in Prod CPU0 on bundle: https://worksheets.codalab.org/bundles/0x28a2cbb897a64cc4a570110e629582a7
```

Traceback (most recent call last):
  File "/opt/codalab/worker/worker_run_state.py", line 287, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/opt/codalab/worker/docker_utils.py", line 39, in wrapper
    raise DockerException(message + ': ' + str(e))
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 409 Client Error: Conflict ("Conflict. The container name "/codalab_run_0x82de4d024b154c61a9dde4020e62d205" is already in use by container "da2a01c0e74f3ebe94812fb5415c46863240c3b9b7ba4f859f46c0730f623ed8". You have to remove (or rename) that container to be able to reuse that name.")

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/create?name=codalab_run_0x82de4d024b154c61a9dde4020e62d205

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/docker_utils.py", line 31, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab/worker/docker_utils.py", line 160, in start_bundle_container
    stdin_open=tty,
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 785, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 843, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 427, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 438, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/codalab_run_0x82de4d024b154c61a9dde4020e62d205" is already in use by container "da2a01c0e74f3ebe94812fb5415c46863240c3b9b7ba4f859f46c0730f623ed8". You have to remove (or rename) that container to be able to reuse that name.")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 159, in start
    self.process_runs()
  File "/opt/codalab/worker/worker.py", line 279, in process_runs
    self.runs[bundle_uuid] = self.run_state_manager.transition(run_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/worker_run_state.py", line 287, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/opt/codalab/worker/docker_utils.py", line 39, in wrapper
    raise DockerException(message + ': ' + str(e))
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 409 Client Error: Conflict ("Conflict. The container name "/codalab_run_0x82de4d024b154c61a9dde4020e62d205" is already in use by container "da2a01c0e74f3ebe94812fb5415c46863240c3b9b7ba4f859f46c0730f623ed8". You have to remove (or rename) that container to be able to reuse that name.")
2020-01-17 23:16:57,728 Sleeping for 1 hour due to exception...please help me!
```
File status:
```
azureuser@vm-clws-prod-worker-0:~$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             7158632        0   7158632   0% /dev
tmpfs            1433852   140048   1293804  10% /run
/dev/sda1       85320036  3491512  81812140   5% /
tmpfs            7169252        0   7169252   0% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs            7169252        0   7169252   0% /sys/fs/cgroup
/dev/sdb1      206291640 26909480 168880120  14% /mnt
tmpfs            1433852        0   1433852   0% /run/user/1000
```

**Comment by candicegjing** [comment]
#### Chasing back to the point where the error started:
```
2020-01-17 06:15:30,503 http://localhost:None "GET /v1.35/containers/36c52988759a45085d5241fc4c3963a9174c50ba3756e697ab12a3cde256c705/json HTTP/1.1" 200 None
2020-01-17 06:15:30,525 http://localhost:None "GET /v1.35/containers/36c52988759a45085d5241fc4c3963a9174c50ba3756e697ab12a3cde256c705/json HTTP/1.1" 200 None
2020-01-17 06:15:31,328 Received run message: {'type': 'run', 'bundle': {'uuid': '0x82de4d024b154c61a9dde4020e62d205', 'bundle_type': 'run', 'owner_id': '0', 'command': 'git clone https://github.com/TheStanfordDaily/archives-scripts.git && cd archives-scripts && npm i && node extract-text.js 1896', 'data_hash': None, 'state': 'starting', 'is_anonymous': False, 'metadata': {'request_disk': '', 'request_cpus': 1, 'request_priority': 0, 'request_docker_image': 'node:10.18.1-alpine3.11', 'allow_failed_dependencies': False, 'name': 'run-git', 'request_gpus': 0, 'tags': [''], 'actions': [], 'created': 1579241727, 'request_queue': '', 'last_updated': 1579241731, 'request_time': '', 'request_network': True, 'request_memory': '4g', 'description': ''}, 'args': 'run "git clone https://github.com/TheStanfordDaily/archives-scripts.git && cd archives-scripts && npm i && node extract-text.js 1896" --request-cpus 1 --request-docker-image node:10.18.1-alpine3.11 --request-network --request-memory 4g', 'dependencies': [], 'location': None}, 'resources': {'cpus': 1, 'gpus': 0, 'docker_image': 'node:10.18.1-alpine3.11', 'time': 0, 'memory': 4294967296, 'disk': 0, 'network': True}, 'meta': {'version': '0.5.4'}}
2020-01-17 06:15:31,553 http://localhost:None "GET /v1.35/containers/36c52988759a45085d5241fc4c3963a9174c50ba3756e697ab12a3cde256c705/json HTTP/1.1" 200 None
2020-01-17 06:15:31,601 http://localhost:None "GET /v1.35/containers/36c52988759a45085d5241fc4c3963a9174c50ba3756e697ab12a3cde256c705/json HTTP/1.1" 200 None
2020-01-17 06:15:31,633 http://localhost:None "GET /v1.35/containers/36c52988759a45085d5241fc4c3963a9174c50ba3756e697ab12a3cde256c705/json HTTP/1.1" 200 None
2020-01-17 06:15:31,650 Downloading Docker image node:10.18.1-alpine3.11
2020-01-17 06:15:31,650 Looking for auth config
2020-01-17 06:15:31,650 Using credentials store "ecr-login"
2020-01-17 06:15:31,651 Looking for auth entry for 'https://index.docker.io/v1/'
2020-01-17 06:15:31,663 No entry found 
2020-01-17 06:15:31,663 No entry in credstore - fetching from auth dict
2020-01-17 06:15:31,663 Looking for auth entry for 'docker.io'
2020-01-17 06:15:31,663 No entry found 
2020-01-17 06:15:31,664 No auth config found 
2020-01-17 06:15:31,793 http://localhost:None "POST /v1.35/images/create?tag=10.18.1-alpine3.11&fromImage=node HTTP/1.1" 200 None
2020-01-17 06:15:33,780 http://localhost:None "GET /v1.35/images/node:10.18.1-alpine3.11/json HTTP/1.1" 200 None
2020-01-17 06:15:33,786 Download for Docker image node:10.18.1-alpine3.11 complete
...
2020-01-17 06:15:37,093 http://localhost:None "POST /v1.35/containers/da2a01c0e74f3ebe94812fb5415c46863240c3b9b7ba4f859f46c0730f623ed8/start HTTP/1.1" 400 167
2020-01-17 06:15:37,099 Cannot start Docker container: Unable to start Docker container: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown")
2020-01-17 06:15:37,235 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/da2a01c0e74f3ebe94812fb5415c46863240c3b9b7ba4f859f46c0730f623ed8/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/docker_utils.py", line 31, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab/worker/docker_utils.py", line 160, in start_bundle_container
    stdin_open=tty,
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 791, in run
    container.start()
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 392, in start
    return self.client.api.start(self.id, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 1091, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown")
```
#### docker info
```
azureuser@vm-clws-prod-worker-0:~$ docker info
Containers: 32
 Running: 1
 Paused: 0
 Stopped: 31
Images: 3
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1050-azure
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 13.67GiB
Name: vm-clws-prod-worker-0
ID: 672R:7YKK:VH6O:AJJU:NPYO:FJMF:EPHQ:SUZ4:RD6M:JA7M:LJQO:WSTG
Docker Root Dir: /mnt/scratch/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```
#### docker version
```
azureuser@vm-clws-prod-worker-0:~$ docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:17 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by candicegjing** [comment]
Bundles that cause this problem include executing the following command:
1. worksheet: https://worksheets.codalab.org/bundles/0x82de4d024b154c61a9dde4020e62d205
```
git  clone https://github.com/TheStanfordDaily/archives-scripts.git  && cd archives-scripts && npm i && node  extract-text.js 1896
```
Tried the following solutions, but none of them worked so far:
1. Removed the duplicated container and restarted the container
2. Set `PATH` env variable to explicitly include `/bin/bash` and `/bin/sh` in docker-compose.yml and restarted the container
3. Searched for `MountFlags=slave` in the system by checking service file `/lib/systemd/system/docker.service `. No such variable found.
4. Tired to reproduce the issue in local machine (docker version = `19.03.5`) using:
```
git  clone https://github.com/TheStanfordDaily/archives-scripts.git  && cd archives-scripts && npm i && node  extract-text.js 1896
```
the job was able to proceed with a different exception:
```
bash: -c: line 1: syntax error near unexpected token `;' bash: -c: line 1: `; ) >stdout 2>stderr' 
```
5. Ran the same command again using a different account, the bundle was able to proceed on the host that had the same issue before (this host has been restored and is working properly):
https://worksheets.codalab.org/bundles/0x887dc8dfd078466c89a80acc57bf244a

Online posts includes:
1. https://github.com/docker/for-linux/issues/561
2. https://gitlab.com/gitlab-org/gitlab-runner/issues/4684
3. https://github.com/moby/moby/issues/8838
4. https://github.com/moby/moby/issues/35435
5. https://github.com/storageos/cluster-operator/issues/141
