### ISSUE TITLE
Worker went offline when "Dependency quota full"

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1827]
Prod gpu worker went offline when the following error happened:
Link to bundle: https://worksheets.codalab.org/bundles/0xb6d600f48b8743c987625aa79b86fcad
```
2019-12-05 04:57:55,180 Using credentials store "ecr-login"
2019-12-05 04:57:55,192 Looking for auth entry for 'https://index.docker.io/v1/'
2019-12-05 04:57:55,215 Path /mnt/scratch/bundles/dependencies/0xb53f9b31939e4d029e0501bbff0f758d already exists, overwriting
2019-12-05 04:57:55,272 No entry found
2019-12-05 04:57:55,278 No entry in credstore - fetching from auth dict
2019-12-05 04:57:55,284 Looking for auth entry for 'docker.io'
2019-12-05 04:57:55,295 Path /mnt/scratch/bundles/dependencies/0x92016f637c7c4832b2b795d7b2243b81 already exists, overwriting
2019-12-05 04:57:55,295 No entry found
2019-12-05 04:57:55,295 Path /mnt/scratch/bundles/dependencies/0xa53e20ef5abf4ffe8f17e6367ec2fd23 already exists, overwriting
2019-12-05 04:57:55,317 No auth config found
2019-12-05 04:57:55,317 Path /mnt/scratch/bundles/dependencies/0x2972412fcf5f4f23b275168b9dbf057b already exists, overwriting
2019-12-05 04:57:55,373 Path /mnt/scratch/bundles/dependencies/0xf0afd6c1a3d643e8bbf180bec840c5c3 already exists, overwriting
2019-12-05 04:57:55,416 Path /mnt/scratch/bundles/dependencies/0x40e3c47c923549b6b622274b95e4fa1e already exists, overwriting
2019-12-05 04:57:55,416 Path /mnt/scratch/bundles/dependencies/0x0f7b76cf776949538ec87f1dc4deb180 already exists, overwriting
2019-12-05 04:57:55,456 Path /mnt/scratch/bundles/dependencies/0x788c0b29d84b4af6b815254ea1020c5a already exists, overwriting
2019-12-05 04:57:55,478 Path /mnt/scratch/bundles/dependencies/0xd2d52f3bffdf4c90a159c6567ff0eedc already exists, overwriting
2019-12-05 04:57:55,489 http://localhost:None "POST /v1.35/images/create?tag=latest&fromImage=sellpy%2Fpython3-jupyter-sklearn HTTP/1.1" 200 None
2019-12-05 04:57:55,489 Path /mnt/scratch/bundles/dependencies/0x0b48f89198e24060bdcecebccf80d9e0 already exists, overwriting
2019-12-05 04:57:55,495 Path /mnt/scratch/bundles/dependencies/0xcacf672733c64ac5a9297a373471f379 already exists, overwriting
2019-12-05 04:57:55,502 Path /mnt/scratch/bundles/dependencies/0x0bd7ea99857e41a5a4f08cfb675b092e already exists, overwriting
2019-12-05 04:57:55,502 Path /mnt/scratch/bundles/dependencies/0xedae2bb9917b4e10be02f5895f72f388 already exists, overwriting
2019-12-05 04:57:55,504 Finished downloading directory dependency DependencyKey(parent_uuid='0x20cd59f04add4171ab25bd489c32d8e3', parent_path='') to /mnt/scratch/bundles/dependencies/0x20cd59f04add4171ab25bd489c32d8e3
2019-12-05 04:57:55,525 http://localhost:None "GET /v1.35/images/sellpy/python3-jupyter-sklearn:latest/json HTTP/1.1" 200 None
2019-12-05 04:57:55,559 Download for Docker image sellpy/python3-jupyter-sklearn:latest complete
2019-12-05 04:57:55,592 Path /mnt/scratch/bundles/dependencies/0xeaf5c4f4b8ee4f9e8bcb21fda04c7deb already exists, overwriting
2019-12-05 04:57:55,650 Path /mnt/scratch/bundles/dependencies/0xc62b0f3d5dd54dba9b6e961d430ae8d2 already exists, overwriting
2019-12-05 04:57:55,650 Finished downloading directory dependency DependencyKey(parent_uuid='0x3e49235e7ad143c58d740ad1e8045f49', parent_path='') to /mnt/scratch/bundles/dependencies/0x3e49235e7ad143c58d740ad1e8045f49
2019-12-05 04:57:55,667 Path /mnt/scratch/bundles/dependencies/0x4630729910c3492f9d66513fa89a627e already exists, overwriting
2019-12-05 04:57:55,689 Path /mnt/scratch/bundles/dependencies/0xfaf325a296eb43f29c22b49e4fdf1a95 already exists, overwriting
2019-12-05 04:57:55,742 Finished downloading directory dependency DependencyKey(parent_uuid='0x64905dc440194cfcad78d8c25b99c993', parent_path='') to /mnt/scratch/bundles/dependencies/0x64905dc440194cfcad78d8c25b99c993
2019-12-05 04:57:55,804 Path /mnt/scratch/bundles/dependencies/0x00557737089948fc899abf5a5e5f39b2 already exists, overwriting
2019-12-05 04:57:55,815 Finished downloading directory dependency DependencyKey(parent_uuid='0x1d713c1e2770463d89fae7872a9d5b4e', parent_path='') to /mnt/scratch/bundles/dependencies/0x1d713c1e2770463d89fae7872a9d5b4e
2019-12-05 04:57:55,846 Path /mnt/scratch/bundles/dependencies/0x047e82013acb4da18890dde98f7254d2 already exists, overwriting
2019-12-05 04:57:55,862 Path /mnt/scratch/bundles/dependencies/0x5dc6d7401ffe4492a9ed4c8a328a3043 already exists, overwriting
2019-12-05 04:57:55,909 Finished downloading directory dependency DependencyKey(parent_uuid='0x1ff9b6c4fbf942699905f1859ca29366', parent_path='') to /mnt/scratch/bundles/dependencies/0x1ff9b6c4fbf942699905f1859ca29366
2019-12-05 04:57:55,947 Path /mnt/scratch/bundles/dependencies/0x4b6c12d52ff2473ca3b8676c039a3872 already exists, overwriting
2019-12-05 04:57:55,953 Path /mnt/scratch/bundles/dependencies/0x47a5c72d3b6d428999764ad83dc4c02d already exists, overwriting
2019-12-05 04:57:56,030 Path /mnt/scratch/bundles/dependencies/0xb504698d6155463f9f5d75bf5b7e9efa already exists, overwriting
2019-12-05 04:57:56,061 Path /mnt/scratch/bundles/dependencies/0xbc356911d6c24cb1996ace121d3a5df8 already exists, overwriting
2019-12-05 04:57:56,098 Path /mnt/scratch/bundles/dependencies/0x23067be96f8f4332bca7b9bb8b004e25 already exists, overwriting
2019-12-05 04:57:56,144 Path /mnt/scratch/bundles/dependencies/0xcb6e1fc2435749bf9d5749a4faf20f46 already exists, overwriting
2019-12-05 04:57:56,154 Path /mnt/scratch/bundles/dependencies/0xa499c0c62ecc4ce09b79cea8bcaf8cfe already exists, overwriting
2019-12-05 04:57:56,320 Path /mnt/scratch/bundles/dependencies/0x1c68e692ea3a4eafa98d776d7394d9b1 already exists, overwriting
2019-12-05 04:57:56,387 Path /mnt/scratch/bundles/dependencies/0xdb396f2b6a3d411aa8d24c26c472a9ab already exists, overwriting
2019-12-05 04:57:56,427 88 dependencies in cache, disk usage: 2.6m (max 90g), serialized size: 58.9k (max 60000)
2019-12-05 04:57:56,432 Dependency quota full but there are only downloading dependencies, not cleaning up until downloads are over
2019-12-05 04:57:56,453 Path /mnt/scratch/bundles/dependencies/0x77e9710c4eb444cc92937b754367ec1e already exists, overwriting
2019-12-05 04:57:56,467 Path /mnt/scratch/bundles/dependencies/0xb3a464b2d9b3499290cfccde7f74c90d already exists, overwriting
2019-12-05 04:57:56,519 Path /mnt/scratch/bundles/dependencies/0xefedbd4fb0bc4869a4526cafa0b9864a already exists, overwriting
2019-12-05 04:57:56,571 Path /mnt/scratch/bundles/dependencies/0x17b955fd30604a08a57cca0ff4404e5b already exists, overwriting
2019-12-05 04:57:56,592 Path /mnt/scratch/bundles/dependencies/0xd8cbd1b8801c44128550fdc4ac560928 already exists, overwriting
2019-12-05 04:57:56,623 Path /mnt/scratch/bundles/dependencies/0x14a9eb3416d14b4dbb2d2f9a795dbf21 already exists, overwriting
2019-12-05 04:57:56,629 Path /mnt/scratch/bundles/dependencies/0xeb1f27525b6f4ea8a7ae54a07f8042eb already exists, overwriting
2019-12-05 04:57:56,660 Path /mnt/scratch/bundles/dependencies/0xec94b4a187a74d259d6effd0841bff51 already exists, overwriting
2019-12-05 04:57:56,713 Path /mnt/scratch/bundles/dependencies/0x12d7cdf003904e33b4dc0cf080e4cdf0 already exists, overwriting
2019-12-05 04:57:56,718 Path /mnt/scratch/bundles/dependencies/0x0ca13155632c463f98451c786a40ef54 already exists, overwriting
2019-12-05 04:57:56,796 Path /mnt/scratch/bundles/dependencies/0xf3d8d041c00f45f9b3e0e18aa0302a1c already exists, overwriting
2019-12-05 04:57:56,806 Path /mnt/scratch/bundles/dependencies/0x3ceed758e176497db7f7340365f23b45 already exists, overwriting
2019-12-05 04:57:56,847 Path /mnt/scratch/bundles/dependencies/0xebbe34ccb70d4cacb68458edaa69b557 already exists, overwriting
2019-12-05 04:57:56,944 Path /mnt/scratch/bundles/dependencies/0xe46ea9f4978841539d30dd665e65553c already exists, overwriting
2019-12-05 04:57:56,955 Path /mnt/scratch/bundles/dependencies/0x4a15ad01b1fb46be95f50d00b0b28383 already exists, overwriting
2019-12-05 04:57:56,960 Path /mnt/scratch/bundles/dependencies/0x7c1ba724532945ad9d969681c5b0266a already exists, overwriting
2019-12-05 04:57:57,037 Path /mnt/scratch/bundles/dependencies/0x12924f420f7d428d8b73af48bec5d111 already exists, overwriting
2019-12-05 04:57:57,140 Path /mnt/scratch/bundles/dependencies/0x8ddafbc9036d4a73a724364187f139a0 already exists, overwriting
2019-12-05 04:57:57,165 Path /mnt/scratch/bundles/dependencies/0xd4b792a598ce44999f07a616f47755b7 already exists, overwriting
2019-12-05 04:57:57,217 Path /mnt/scratch/bundles/dependencies/0x39e6a6912b4a49d1b79e121226496163 already exists, overwriting
2019-12-05 04:57:57,218 Path /mnt/scratch/bundles/dependencies/0x9419ca1c0af74e4ca41620d7f88725a4 already exists, overwriting
2019-12-05 04:57:57,218 Path /mnt/scratch/bundles/dependencies/0xfa44d599fbab482799b0f1c6ad73f623 already exists, overwriting
2019-12-05 04:57:57,223 Path /mnt/scratch/bundles/dependencies/0x8de435422dc34833a2a659c3a05e5ae7 already exists, overwriting
2019-12-05 04:57:57,281 Path /mnt/scratch/bundles/dependencies/0x792fd0b9d495442a9bf9438aedfcc412 already exists, overwriting
2019-12-05 04:57:57,313 Path /mnt/scratch/bundles/dependencies/0xc38586dfcc83487fa87a157013ff0b55 already exists, overwriting
2019-12-05 04:57:57,323 Path /mnt/scratch/bundles/dependencies/0x2167ef4e2a6a47888d5664b16176f5d6 already exists, overwriting
2019-12-05 04:57:57,350 Path /mnt/scratch/bundles/dependencies/0x89833a207c0c43d18c554049a01a1c39 already exists, overwriting
2019-12-05 04:57:57,409 Path /mnt/scratch/bundles/dependencies/0x69b62ad4921a40e2ab556981a3d4ae8a already exists, overwriting
2019-12-05 04:57:57,445 Path /mnt/scratch/bundles/dependencies/0x910b08b30e7e48fdb1506518545e42bc already exists, overwriting
2019-12-05 04:57:57,513 Path /mnt/scratch/bundles/dependencies/0x1bfe816472c9403d9312bdc6cfda6cf0 already exists, overwriting
2019-12-05 04:57:57,513 Path /mnt/scratch/bundles/dependencies/0x05d060d5ed8c41e1bf883cf5db8cf552 already exists, overwriting
2019-12-05 04:57:57,576 Path /mnt/scratch/bundles/dependencies/0x10cc3d078d4642e4862807f49e8b5856 already exists, overwriting
2019-12-05 04:57:57,611 Path /mnt/scratch/bundles/dependencies/0x6437f40ca17c44cca54ea532d0274a51 already exists, overwriting
2019-12-05 04:57:57,616 Path /mnt/scratch/bundles/dependencies/0x08f6b9d6de144dc1a4853fb703c623b8 already exists, overwriting
2019-12-05 04:57:57,708 88 dependencies in cache, disk usage: 2.6m (max 90g), serialized size: 58.9k (max 60000)
2019-12-05 04:57:57,713 Dependency quota full but there are only downloading dependencies, not cleaning up until downloads are over
2019-12-05 04:57:57,719 Path /mnt/scratch/bundles/dependencies/0x0b1ff2780669442ba105058cd7b8d3b4 already exists, overwriting
2019-12-05 04:57:57,733 Path /mnt/scratch/bundles/dependencies/0x214f61175aa5462d8042edb1ea29ff55 already exists, overwriting
2019-12-05 04:57:57,733 Path /mnt/scratch/bundles/dependencies/0x2e69e0fb80c74a6d80c1c3875864bbe6 already exists, overwriting
2019-12-05 04:57:57,830 Path /mnt/scratch/bundles/dependencies/0x5f0fe7e73e63477a96b47a35648d2efc already exists, overwriting
2019-12-05 04:57:57,830 Path /mnt/scratch/bundles/dependencies/0xddf16cd193d04684b9d380174a2f67ea already exists, overwriting
2019-12-05 04:57:57,846 Path /mnt/scratch/bundles/dependencies/0x50df27eb2a68407f96112b23e43dbb0d already exists, overwriting
2019-12-05 04:57:57,851 Path /mnt/scratch/bundles/dependencies/0xf2e03cecef204fc69aad77c2042aff61 already exists, overwriting
2019-12-05 04:57:57,888 Path /mnt/scratch/bundles/dependencies/0x1542075e45a04140bb013ef58eb30f2d already exists, overwriting
2019-12-05 04:57:57,899 Path /mnt/scratch/bundles/dependencies/0x85089e1e11724bb6be852c79e76efacb already exists, overwriting
2019-12-05 04:57:57,899 Path /mnt/scratch/bundles/dependencies/0xd169f2ab5b214270bdb95fab55cc644d already exists, overwriting
2019-12-05 04:57:57,940 copying file to /mnt/scratch/bundles/dependencies/0x85089e1e11724bb6be852c79e76efacb
2019-12-05 04:57:58,988 88 dependencies in cache, disk usage: 2.6m (max 90g), serialized size: 58.9k (max 60000)
2019-12-05 04:57:58,993 Dependency quota full but there are only downloading dependencies, not cleaning up until downloads are over
2019-12-05 04:58:00,226 88 dependencies in cache, disk usage: 2.6m (max 90g), serialized size: 58.9k (max 60000)
2019-12-05 04:58:00,231 Dependency quota full but there are only downloading dependencies, not cleaning up until downloads are over
2019-12-05 04:58:01,132 Connected! Successful check in!
```

**Comment by candicegjing** [comment]
It failed with the following message:
```
2019-12-09 21:02:37,432 Uploading results for run with UUID 0xf8b27cd19c9c453f9e78236c38bea44b
2019-12-09 21:02:40,879 Connected! Successful check in!
Traceback (most recent call last):
  File "/opt/codalab/worker/bundle_service_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab/worker/bundle_service_client.py", line 166, in update_bundle_contents
    progress_callback=progress_callback,
  File "/opt/codalab/worker/rest_client.py", line 148, in _upload_with_chunked_encoding
    conn.send(b'%X\r\n%s\r\n' % (len(to_send), to_send))
  File "/usr/lib/python3.6/http/client.py", line 996, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 214, in _execute_bundle_service_command_with_retry
    cmd()
  File "/opt/codalab/worker/worker.py", line 188, in <lambda>
    self.id, bundle_uuid, bundle_path, update_status
  File "/opt/codalab/worker/bundle_service_client.py", line 48, in wrapper
    raise BundleServiceException(message + ': ' + str(e), False)
codalab.worker.bundle_service_client.BundleServiceException: Unable to update bundle contents in bundle service: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/opt/codalab/worker/bundle_service_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab/worker/bundle_service_client.py", line 166, in update_bundle_contents
    progress_callback=progress_callback,
  File "/opt/codalab/worker/rest_client.py", line 148, in _upload_with_chunked_encoding
    conn.send(b'%X\r\n%s\r\n' % (len(to_send), to_send))
  File "/usr/lib/python3.6/http/client.py", line 996, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```
Seems to be related to #1829
