### ISSUE TITLE
Prod CPU worker 0 went offline due to HTTP Error 400: Bad Request in _upload_with_chunked_encoding

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1829]
prodcpu0 went offline with the following error:
```
2019-12-05 05:21:27,969 http://localhost:None "GET /v1.35/containers/7b8dd192457b3711b3ea3ae15c1e8ff15b47ecb15a389a3c070f5dfcf8b212c8/json HTTP/1.1" 200 None
2019-12-05 05:21:27,981 http://localhost:None "GET /v1.35/containers/7b8dd192457b3711b3ea3ae15c1e8ff15b47ecb15a389a3c070f5dfcf8b212c8/json HTTP/1.1" 200 None
2019-12-05 05:21:27,982 Finished run with UUID 0x030b0d84f576464d9958e1aafb947c88, exitcode 0, failure_message None
2019-12-05 05:21:33,231 http://localhost:None "GET /v1.35/containers/7b8dd192457b3711b3ea3ae15c1e8ff15b47ecb15a389a3c070f5dfcf8b212c8/json HTTP/1.1" 200 None
2019-12-05 05:21:33,254 http://localhost:None "GET /v1.35/containers/7b8dd192457b3711b3ea3ae15c1e8ff15b47ecb15a389a3c070f5dfcf8b212c8/json HTTP/1.1" 200 None
2019-12-05 05:21:33,261 http://localhost:None "GET /v1.35/containers/7b8dd192457b3711b3ea3ae15c1e8ff15b47ecb15a389a3c070f5dfcf8b212c8/logs?stderr=1&stdout=0&timestamps=0&follow=0&tail=all HTTP/1.1" 200 None
2019-12-05 05:21:33,278 http://localhost:None "GET /v1.35/containers/7b8dd192457b3711b3ea3ae15c1e8ff15b47ecb15a389a3c070f5dfcf8b212c8/json HTTP/1.1" 200 None
2019-12-05 05:21:33,304 http://localhost:None "DELETE /v1.35/containers/7b8dd192457b3711b3ea3ae15c1e8ff15b47ecb15a389a3c070f5dfcf8b212c8?v=False&link=False&force=True HTTP/1.1" 204 0
2019-12-05 05:21:36,673 Uploading results for run with UUID 0x030b0d84f576464d9958e1aafb947c88
2019-12-05 05:21:44,216 Received mark_finalized message: {'type': 'mark_finalized', 'uuid': '0x030b0d84f576464d9958e1aafb947c88', 'meta': {'version': '0.5.1'}}
2019-12-05 05:27:09,857 Traceback (most recent call last):
  File "/opt/codalab/worker/bundle_service_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab/worker/bundle_service_client.py", line 166, in update_bundle_contents
    progress_callback=progress_callback,
  File "/opt/codalab/worker/rest_client.py", line 165, in _upload_with_chunked_encoding
    StringIO(response.read().decode()),
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/local_run/local_run_state.py", line 496, in upload_results
    run_state.bundle.uuid, run_state.bundle_path, progress_callback
  File "/opt/codalab/worker/worker.py", line 187, in upload_bundle_contents
    lambda: self._bundle_service.update_bundle_contents(
  File "/opt/codalab/worker/worker.py", line 214, in _execute_bundle_service_command_with_retry
    cmd()
  File "/opt/codalab/worker/worker.py", line 188, in <lambda>
    self.id, bundle_uuid, bundle_path, update_status
  File "/opt/codalab/worker/bundle_service_client.py", line 25, in wrapper
    client_error = json.loads(e.read().decode())
AttributeError: 'str' object has no attribute 'decode'

2019-12-05 05:27:12,446 Received mark_finalized message: {'type': 'mark_finalized', 'uuid': '0x9d7e7823a3f9456e92ac97a33607065f', 'meta': {'version': '0.5.1'}}
```

**Comment by candicegjing** [comment]
@teetone I reassigned this ticket as it appears to have the same issue discovered in PR #1884.
