### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1958]
```
Error on request by matt.downey18(0xd72e93b8f2b448fc9318d136e89e555a):

POST /cli/command

Query params:

Form params:

JSON body:
{
"command": "cl run evaluate.py: 0xdcf10e1da32e45ce970bbb07fd4694eb",
"worksheet_uuid": "0x1fc53883bf2f432eb3bc0ae4164ee0dd"
}

Local variables:
bundle_spec=None
worksheet_uuid='0x1fc53883bf2f432eb3bc0ae4164ee0dd'
client=<codalab.client.json_api_client.JsonApiClient object at 0x7f678015a6a0>

Traceback (most recent call last):
File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 106, in wrapper
return callback(*args, **kwargs)
File "/usr/local/bin/bottle.py", line 1732, in wrapper
rv = callback(*a, **ka)
File "/opt/codalab-worksheets/codalab/server/json_api_plugin.py", line 18, in wrapper
result = callback(*args, **kwargs)
File "/opt/codalab-worksheets/codalab/rest/cli.py", line 48, in post_worksheets_command
return general_command(query['worksheet_uuid'], query['command'])
File "/opt/codalab-worksheets/codalab/rest/cli.py", line 149, in general_command
structured_result = cli.do_command(args)
File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 839, in do_command
structured_result = command_fn()
File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 833, in <lambda>
command_fn = lambda: args.function(self, args)
File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 1527, in do_run_command
targets = self.resolve_key_targets(client, worksheet_uuid, args.target_spec)
File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 585, in resolve_key_targets
client, worksheet_uuid, target_spec, allow_remote=False
File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 563, in resolve_target
bundle_uuid = BundleCLI.resolve_bundle_uuid(client, worksheet_uuid, bundle_spec)
File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 597, in resolve_bundle_uuid
if spec_util.UUID_REGEX.match(bundle_spec):
TypeError: expected string or bytes-like object
```

**Comment by candicegjing** [comment]
The above issue is caused by `None` value in doing regex match. `re.match(<String>)` doesn't allow `None` value.

**Comment by epicfaace** [comment]
This is not a new error. I noticed it coming up even as far back as when we initially migrated to Python 3.

**Comment by candicegjing** [comment]
Ran local tests to reproduce this issue. See the following example:
<img width="881" alt="Screen Shot 2020-02-19 at 5 05 56 PM" src="https://user-images.githubusercontent.com/1483372/74890830-1f815680-533a-11ea-9665-1d244986037f.png">
Whenever we specify the dependency in the wrong format, the system will send out an email notifying the admin about this issue. But this exception doesn't bring down any existing running services. Should be safe to close this ticket unless we want to handle it in a different way.

**Comment by percyliang** [comment]
Let's not close this ticket.  This error message is bad and suggests something serious has happened, not just a user error.

**Comment by candicegjing** [comment]
I think this one is due to wrongly formatted dependencies specified from `cl run` command, then this leads to failures in regex matching, see the following example:
```
>>> uuid = re.compile('^' + '0x[0-9a-f]{32}' + '$')
>>> uuid.match(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected string or bytes-like object
```
When the input value is `None`, the TypeError will be thrown.
