### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'parser'

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1959]
```
Error on request by matt.downey18(0xd72e93b8f2b448fc9318d136e89e555a):

POST /cli/command

Query params:

Form params:

JSON body:
{
"autocomplete": true,
"command": "cl run ev",
"worksheet_uuid": "0x1fc53883bf2f432eb3bc0ae4164ee0dd"
}

Local variables:
completer=<codalab.lib.completers.TargetsCompleter object at 0x7f673c680ac8>
complete_remaining_positionals=True
greedy_actions=[]
completions=[]
parsed_args=Namespace(after_sort_key=None, command=None, edit=False, function=<function BundleCLI.do_run_command at 0x7f678add6ea0>, md_allow_failed_dependencies=None, md_description=None, md_name=None, md_request_cpus=None, md_request_disk=None, md_request_docker_image=None, md_request_gpus=None, md_request_memory=None, md_request_network=None, md_request_priority=None, md_request_queue=None, md_request_time=None, md_tags=None, print_version=False, tail=False, target_spec=[], verbose=False, wait=False, worksheet_spec=None)
next_positional=IntrospectAction(option_strings=[], dest='command', nargs=None, const=None, default=None, type=None, choices=None, help='Arbitrary Linux command to execute.', metavar='[---] command')
parser=MonkeyPatchedIntrospectiveArgumentParser(prog='cl run', usage=None, description='Create a bundle by running a program bundle on an input bundle.', formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=True)
self=<argcomplete.CompletionFinder object at 0x7f675c3f79e8>
isoptional=False
cword_prefix='ev'
active_action=IntrospectAction(option_strings=[], dest='target_spec', nargs='*', const=None, default=None, type=None, choices=None, help='[<key>]:[[(<alias>|<address>)::](<uuid>|<name>)//](<uuid>|<name>|^<index>)[/<subpath within bundle>]', metavar=None)

Traceback (most recent call last):
File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 106, in wrapper
return callback(*args, **kwargs)
File "/usr/local/bin/bottle.py", line 1732, in wrapper
rv = callback(*a, **ka)
File "/opt/codalab-worksheets/codalab/server/json_api_plugin.py", line 18, in wrapper
result = callback(*args, **kwargs)
File "/opt/codalab-worksheets/codalab/rest/cli.py", line 46, in post_worksheets_command
return {'completions': complete_command(query['worksheet_uuid'], query['command'])}
File "/opt/codalab-worksheets/codalab/rest/cli.py", line 116, in complete_command
return cli.complete_command(command)
File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 808, in complete_command
cf._get_completions(comp_words, cword_prefix, cword_prequote, first_colon_pos),
File "/usr/local/lib/python3.6/dist-packages/argcomplete/__init__.py", line 251, in _get_completions
completions = self.collect_completions(active_parsers, parsed_args, cword_prefix, debug)
File "/usr/local/lib/python3.6/dist-packages/argcomplete/__init__.py", line 464, in collect_completions
completions)
File "/usr/local/lib/python3.6/dist-packages/argcomplete/__init__.py", line 418, in _complete_active_option
prefix=cword_prefix, action=active_action, parser=parser, parsed_args=parsed_args)
TypeError: __call__() got an unexpected keyword argument 'parser'

```

**Comment by candicegjing** [comment]
Identical with the issue #1027
