### ISSUE TITLE
Permissions issues with wcp

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#197]
Some sort of permission errors with cl wcp. In particular, if run:

```
cl wcp -c nlp::translation_powerlaw_noisy https://codalab.org/bundleservice::translation_powerlaw_noisy
```

get the following error:

```
Copying beta_0.1(0x3c4a25912c4f4ed38c21dd8340208097)...
Copying 0x3c4a25912c4f4ed38c21dd8340208097 from http://localhost:12800 to https://codalab.org/bundleservice: 212K [done]
Traceback (most recent call last):
  File "/home/$USER/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 66, in <module>
    run_cli()
  File "/home/$USER/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 57, in run_cli
    cli.do_command(sys.argv[1:])
  File "/home/$USER/codalab-cli/codalab/lib/bundle_cli.py", line 524, in do_command
    structured_result = command_fn()
  File "/home/$USER/codalab-cli/codalab/lib/bundle_cli.py", line 506, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/home/$USER/codalab-cli/codalab/lib/bundle_cli.py", line 1720, in do_wcp_command
    self.copy_bundle(source_client, source_bundle_info['uuid'], dest_client, dest_worksheet_uuid, copy_dependencies=False, add_to_worksheet=False)
  File "/home/$USER/codalab-cli/codalab/lib/bundle_cli.py", line 811, in copy_bundle
    source_client.copy_bundle(source_bundle_uuid, info, dest_client, dest_worksheet_uuid, add_to_worksheet)
  File "/home/$USER/codalab-cli/codalab/client/remote_bundle_client.py", line 244, in copy_bundle
    result = dest_client.upload_bundle_zip(dest_file_uuid, info, dest_worksheet_uuid, False, add_to_worksheet)
  File "/home/$USER/codalab-cli/codalab/client/remote_bundle_client.py", line 141, in inner
    return getattr(self.proxy, command)(*args, **kwargs)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<class 'codalab.common.AuthorizationError'>:Not authenticated">
```

A possibly related issue is that wcp does not seem to copy private bundles (the desired behavior would be for the private bundles to be copied, with permissions still set to private).

**Comment by kashizui** [comment]
This specific issue has not been reproducible, and new permissions problems with wcp have been narrowed down to a one-time database integrity issue to be addressed asap.
