### ISSUE TITLE
The data type of urllib.error.HTTPError object could vary between String and bytes

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#2012]
Case 1: when a user types in a wrong password, which causes authentication error, the bundle_service_client.py throws an error complaining about the data type of [e.read](https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/bundle_service_client.py#L25). From the logging message listed below, the data type of `e.read()` is bytes.
```
stanford@Stanfords-MacBook-Pro codalab-worksheets % cl-worker --server=http://localhost                                                                        
Username: codalab
Password: 
[code] = <class 'int'>, 401
[msg] = <class 'str'>, Unauthorized
[e.read] = <class 'bytes'>, b'{"error": "invalid_grant", "error_description": "Invalid credentials given."}'
[e.code] = <class 'int'>, 401
Traceback (most recent call last):
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/worker/bundle_service_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/worker/bundle_service_client.py", line 105, in _authorize
    with closing(urllib.request.urlopen(request)) as response:
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 651, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cl-worker", line 11, in <module>
    load_entry_point('codalab', 'console_scripts', 'cl-worker')()
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/worker/main.py", line 162, in main
    bundle_service = connect_to_codalab_server(args.server, args.password_file)
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/worker/main.py", line 151, in connect_to_codalab_server
    bundle_service = BundleServiceClient(server, username, password)
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/worker/bundle_service_client.py", line 78, in __init__
    self._authorize()
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/worker/bundle_service_client.py", line 35, in wrapper
    message + ': ' + http.client.responses[e.code] + ' - ' + client_error,
TypeError: can only concatenate str (not "bytes") to str
```

Case 2: in function `upload_with_chunk_encoding`: [StringIO(response.read().decode())](https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/rest_client.py#L160-L165) will be received as String in `e.read()`, which causes discrepancy in data type between case 1.  This error will be thrown when a user's disk utilization exceeds the upper limit of the disk quota allowed.

**Comment by candicegjing** [comment]
In the first case, the data type of `fp` object is `http.client.HTTPResponse`. On the receiver side, `HTTPError` response is interpreted as `bytes` without any additional processing.
However, in the second case, the data type is `StringIO`. On the receiver side, `HTTPError` response is interpreted as `String` without any additional processing.
