### ISSUE TITLE
Travis CI failure in Valid Bundle References

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#2090]
Travis reported the following error during the build (#2031) that includes logic to support tagging public instances:
```
process: ## Bundle References
process: 
process: #### Valid Bundle Referen (...more...)
process: MISMATCH! line: 180 pattern: \s\s0x[a-z0-9]{6}\s*[\s\S]{0,100}\s*[\s\S]{0,1000}\s*[\s\S]{0,1000}\s*(uploading|created|staged|making|starting|preparing|running|finalizing|ready|failed|killed|worker_offline)\s*[\s\S]{0,1000} output: 
process: MISMATCH! line: 182 pattern: ##### Search\ for\ recently\ ready\ runs output: 
process: MISMATCH! line: 184 pattern: \s\suuid\[0:8\]\s*name\s*summary\s*data_size\s*state\s*description output:   -------------------------------------------------------------------------
process: MISMATCH! line: 187 pattern: \s\s0x[a-z0-9]{6}\s*[\s\S]{0,100}\s*[\s\S]{0,1000}\s*[\s\S]{0,1000}\s*(uploading|created|staged|making|starting|preparing|running|finalizing|ready|failed|killed|worker_offline)\s*[\s\S]{0,1000} output: 
process: MISMATCH! line: 188 pattern: \s\s0x[a-z0-9]{6}\s*[\s\S]{0,100}\s*[\s\S]{0,1000}\s*[\s\S]{0,1000}\s*(uploading|created|staged|making|starting|preparing|running|finalizing|ready|failed|killed|worker_offline)\s*[\s\S]{0,1000} output: ##### Search for worksheets (tag: codalab-sample-worksheet)
process: MISMATCH! line: 190 pattern: ##### Search\ for\ worksheets\ \(tag\:\ codalab\-sample\-worksheet\) output: [Worksheet cl_small_worksheet(0x00f7c97811fc4ef38d60a526ca3120fb)]
process: MISMATCH! line: 193 pattern: \[Worksheet \S*\(0x[a-z0-9]{32}\)\] output: 
process: MISMATCH! line: 194 pattern: \[Worksheet \S*\(0x[a-z0-9]{32}\)\] output: ##### Search for recently created bundles
process: MISMATCH! line: 196 pattern: ##### Search\ for\ recently\ created\ bundles output:   name      owner  created            
process: MISMATCH! line: 198 pattern: \s\sname\s*owner\s*created output:   run-echo         2020-03-10 17:28:48
process: MISMATCH! line: 201 pattern: \s\s[\s\S]{0,100}\s*[\s\S]{0,1000}\s*[\s\S]{0,1000} output: 
process: MISMATCH! line: 202 pattern: \s\s[\s\S]{0,100}\s*[\s\S]{0,1000}\s*[\s\S]{0,1000} output: ## Invalid Directives
process: MISMATCH! line: 204 pattern: ## Invalid\ Directives output: Error in source line 161: unknown directive `hi`
process: MISMATCH! line: 206 pattern: Error in source line [\d]+: unknown directive `hi` output: Error in source line 162: unknown directive `hello`
....
process: MISMATCH! line: 239 pattern: #### Code\ Block output: def main():
process: MISMATCH! line: 240 pattern: \~\~\~\ Python output: 	# This is some Python code
process: MISMATCH! line: 241 pattern: def\ main\(\)\: output: 	print("Hello")
process: MISMATCH! line: 242 pattern: \	\#\ This\ is\ some\ Python\ code output: ~~~
process: MISMATCH! line: 243 pattern: \	print\(\"Hello\"\) output: 
process: MISMATCH! line: 244 pattern: \~\~\~ output: #### Some Latex and Math
process: MISMATCH! line: 246 pattern: #### Some\ Latex\ and\ Math output: The loss minimization framework is to cast learning as an optimization problem. We are estimating (fitting or learning) $\mathbf w$ using $ \mathcal{D}_\text{train}$. A loss function $ \text{Loss}(x, y, \mathbf w) $ quantifies how unhappy you would be if you used $\mathbf w$ to make a prediction on $x$ when the correct output is $y$. This is the object we want to minimize. Below is minimizing training loss across all training examples. Note that $ \text{TrainLoss}(\mathbf w) $ is just the average of loss for all training examples.
process: MISMATCH! line: 247 pattern: Source\:\ \[CS221\]\(http\:\/\/cs221\.stanford\.edu\/\) output: 
process: [!] ERROR: 
process: 
process: [*][*] CLEANING UP
process: >> cl work 0x1b5253b3330946fca43fc04a44a8db20
process:  (exit code 0, expected 0)
process: 
process: Switched to worksheet: http://rest-server:2900/worksheets/0x1b5253b3330946fca43fc04a44a8db20 (home-codalab)
process: 
process: >> cl ls -w 0x0625bfb38a594b0889d75c6e6fabfc8f -u
process:  (exit code 0, expected 0)
process: 
process: 
process: >> cl wrm --force 0x0625bfb38a594b0889d75c6e6fabfc8f
process:  (exit code 0, expected 0)
process: 
process: 
process: [*][*][*] SUMMARY
process: 
process: [!][!] Tests failed: worksheets
process: 
Traceback (most recent call last):
  File "codalab_service.py", line 786, in <module>
    main()
  File "codalab_service.py", line 96, in main
    service_manager.execute()
  File "codalab_service.py", line 549, in execute
    self.run_tests()
  File "codalab_service.py", line 758, in run_tests
    self.args.rest_port, ' '.join(self.args.tests)
  File "codalab_service.py", line 657, in run_service_cmd
    ' bash -c \'%s\'' % cmd
  File "codalab_service.py", line 632, in _run_compose_cmd
    raise Exception('Command exited with code {}'.format(popen.returncode))
Exception: Command exited with code 1
The command "python3 codalab_service.py test --version ${TRAVIS_BRANCH} default" exited with 1.
```
To make the deployment process of 0.5.10 easier, we temporarily reverted this PR in #2088. However, I have observed this issue randomly happened in several places that don't include the code changes in #2031, e.g. [Git Action Functionality Test](https://github.com/candicegjing/codalab-worksheets/runs/493853133?check_suite_focus=true#step:7:8235). This particular failure could be caused by something else which needs further investigation. This PR is to fix this issue.

**Comment by candicegjing** [comment]
I set up a build that only runs the `worksheets` test, [Travis build](https://travis-ci.org/github/codalab/codalab-worksheets/jobs/663170828?utm_medium=notification&utm_source=github_status) reported a different error as following
<img width="936" alt="Screen Shot 2020-03-16 at 10 55 35 AM" src="https://user-images.githubusercontent.com/1483372/76786466-7f6df000-6774-11ea-92f0-69c6f184b716.png">
It appears that the failure is due to passing an empty string to regex matching function.

**Comment by candicegjing** [comment]
Locally tested the following two cases:
1. include #2031
1. not include #2031
Both are passed when testing against `worksheets`

**Comment by candicegjing** [comment]
However, the build in Travis doesn't work for both cases https://travis-ci.org/github/codalab/codalab-worksheets/jobs/663183363?utm_medium=notification&utm_source=github_status

**Comment by candicegjing** [comment]
The failure seems to be introduced by mismatched lines when comapring the list of bundle state.

**Comment by candicegjing** [comment]
It's unclear how these bundles can't be found later on.. And if I clear out the local working directory, I am able to reproduce the error every single time I run `worksheets` test. However, if I rerun the bundle from the previous failed run without clearing out the local working directory, the tests are running fine. This seems to be related to the logic which skips recreating the `cl_small_worksheet` when there is an existing one found in the system:
```
process: [*][*] BEGIN TEST
process: >> cl wsearch cl_small_worksheet --uuid-only
process:  (exit code 0, expected 0)
process: 
process: 0xf5071a961fd24db3a3e7246ccd5fdeb1
process: 
process: There is already an existing cl_small_worksheet with UUID 0xf5071a961fd24db3a3e7246ccd5fdeb1. Skipping creating a sample worksheet...
process: >> cl print cl_small_worksheet
```
Then the `expected_lines` will be an empty string so when we try to regex match any string with an empty string, it will just return an empty string which is a not `None` value and pass the tests.

**Comment by candicegjing** [comment]
It appears that the two bundles that were submitted at the beginning got stuck in the `staged` state. Then during the verification stage, since the expected output looks for those two `staged` bundles to be in `ready` state, the comparison started to fail because of the mismatch in the returning result. 
See the following picture:
In **Search for my bundles**, it contains 3 bundles in total. 1 in `ready` state, another two in `staged` state. In **Search for the largest bundles** and **Search for recently ready runs**, they both contain only 1 bundle, which differs from what the expected output looks for.
<img width="707" alt="Screen Shot 2020-03-17 at 10 25 24 AM" src="https://user-images.githubusercontent.com/1483372/76883584-a3dfd000-6839-11ea-94d6-d993f1146911.png">
