### ISSUE TITLE
Prod issue - Worker failing with conflict in container name

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2111]
```Traceback (most recent call last):
  File "/opt/codalab/worker/docker_utils.py", line 33, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab/worker/docker_utils.py", line 165, in start_bundle_container
    stdin_open=tty,
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 785, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 843, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 427, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 438, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/codalab_run_0x05179aa8558d4ba0b3377e6d358b9602" is already in use by container "995fe505626bbd1eff4f30f0a5d2141fbad585ea4934c93b5a664a3d21d577b0". You have to remove (or rename) that container to be able to reuse that name.")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker_run_state.py", line 287, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/opt/codalab/worker/docker_utils.py", line 41, in wrapper
    raise DockerException(message + ': ' + str(e))
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 409 Client Error: Conflict ("Conflict. The container name "/codalab_run_0x05179aa8558d4ba0b3377e6d358b9602" is already in use by container "995fe505626bbd1eff4f30f0a5d2141fbad585ea4934c93b5a664a3d21d577b0". You have to remove (or rename) that container to be able to reuse that name.")```

**Comment by nelson-liu** [comment]
usually, this indicates that there's actually another issue starting the docker container. the way i've seen it is:

(1) a docker container tries to start on the worker, but it fails for some reason. Fixing this reason is the real issue.
(2) the container is not removed, and stays there in the "STARTING" state
(3) when the worker tries to restart the container, it errors with this message.

**Comment by epicfaace** [comment]
This is starting to happen on our CI builds too :(

**Comment by epicfaace** [comment]
Failed run: https://worksheets.codalab.org/bundles/0x05179aa8558d4ba0b3377e6d358b9602

**Comment by epicfaace** [comment]
This is happening locally for me now:

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 275, in start
    self.process_runs()
  File "/opt/codalab/worker/worker.py", line 485, in process_runs
    self.runs[uuid] = self.run_state_manager.transition(prev_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/worker_run_state.py", line 414, in _transition_from_PREPARING
    shared_memory_size_gb=self.shared_memory_size_gb,
  File "/opt/codalab/worker/docker_utils.py", line 63, in wrapper
    check_for_user_error(e)
  File "/opt/codalab/worker/docker_utils.py", line 56, in check_for_user_error
    raise DockerException(error_message)
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 409 Client Error: Conflict ("Conflict. The container name "/codalab_run_0x6c07fe59d04e4c599f1d4ad029dbf434" is already in use by container "23510cbee0a9dc8fac9ab77441a2d38c1c84d740e97c1fe69c7a9e1c1a58e37c". You have to remove (or rename) that container to be able to reuse that name.")
2022-02-21 17:21:30,886 Sleeping for 1 hour due to exception...please help me! /opt/codalab/worker/worker.py 301
```
