### ISSUE TITLE
[USER ISSUE] cl wadd across instances doesn't seem to work

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2192]
**Describe the bug**

Apologies if I'm just messing up something very simple here:

```
$ cl alias
localhost: http://localhost:2900
main: https://worksheets.codalab.org
stanford: http://codalab.stanford.edu

$ cl work main::home-nfliu
Switched to worksheet: https://worksheets.codalab.org/worksheets/0x6c26647dad70404eb6ea6a01ed8b6a99 (home-nfliu)

$ cl ls
### Worksheet: https://worksheets.codalab.org::home-nfliu(0x6c26647dad70404eb6ea6a01ed8b6a99)
### Title: <none>
### Tags:
### Owner: nfliu(0x23c379b450cb4552b314268c413e2468)
### Permissions: public(0xc573c2):read
ref  uuid      name          summary  owner  created              data_size  state
----------------------------------------------------------------------------------
 ^2  0xd9fb67  run-allennlp           nfliu  2020-02-19 16:54:43       1.4g  ready
 ^1  0xb3c03f  run-echo               nfliu  2020-04-01 15:12:55       4.0k  ready

$ cl work stanford::
Switched to worksheet: http://codalab.stanford.edu/worksheets/0x8e694eac468f4763aa23b112561447ce (home-nfliu)

$ cl new nfliu-test
0xf74aaee3663c4281b8ed0e7258c41954

$ cl wadd main::home-nfliu stanford::nfliu-test
Copying run-allennlp(0xd9fb67a5bdc4483f833ed8a66062f8e5)...
Traceback (most recent call last):
  File "/Users/nfliu/miniconda3/envs/ood-variance/bin/cl", line 11, in <module>
    load_entry_point('codalab', 'console_scripts', 'cl')()
  File "/Users/nfliu/git/codalab-worksheets/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/Users/nfliu/git/codalab-worksheets/codalab/lib/bundle_cli.py", line 864, in do_command
    structured_result = command_fn()
  File "/Users/nfliu/git/codalab-worksheets/codalab/lib/bundle_cli.py", line 858, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/Users/nfliu/git/codalab-worksheets/codalab/lib/bundle_cli.py", line 3297, in do_wadd_command
    add_to_worksheet=False,
  File "/Users/nfliu/git/codalab-worksheets/codalab/lib/bundle_cli.py", line 1433, in copy_bundle
    target_info = source_client.fetch_contents_info((source_bundle_uuid, ''))
  File "/Users/nfliu/git/codalab-worksheets/codalab/client/json_api_client.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/Users/nfliu/git/codalab-worksheets/codalab/client/json_api_client.py", line 594, in fetch_contents_info
    target.bundle_uuid,
AttributeError: 'tuple' object has no attribute 'bundle_uuid'
```

**To Reproduce**
Steps to reproduce the behavior :
1. Try to wadd from one instance to another.

**Comment by candicegjing** [comment]
Upgraded codalab.stanford.edu to have the latest `v0.5.13` version. I verified that I am seeing the same issue reported in this ticket:
```
Copying run-allennlp(0x131c832bfc354015b18cd5658d7ea144)...
Traceback (most recent call last):
  File "/usr/local/bin/cl", line 11, in <module>
    load_entry_point('codalab', 'console_scripts', 'cl')()
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/lib/bundle_cli.py", line 864, in do_command
    structured_result = command_fn()
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/lib/bundle_cli.py", line 858, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/lib/bundle_cli.py", line 3288, in do_wadd_command
    add_to_worksheet=False,
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/lib/bundle_cli.py", line 1424, in copy_bundle
    target_info = source_client.fetch_contents_info((source_bundle_uuid, ''))
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/client/json_api_client.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/Users/stanford/PycharmProjects/codalab-worksheets/codalab/client/json_api_client.py", line 594, in fetch_contents_info
    target.bundle_uuid,
AttributeError: 'tuple' object has no attribute 'bundle_uuid'
```
