### ISSUE TITLE
better autocomplete for 'cl run'

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#223]
When type ':' tab, should complete with possible bundles.
When begin the command, then complete with possible dependency keys (the bundle name if the key is empty).
When type 'main:: tab, should complete with worksheets on instance main.

**Comment by kashizui** [comment]
Autocomplete is funky when typing out a command, because of the '---' syntax, which is not handled directly by argparse. I spent a long time on this previously and I haven't been able to figure out how to handle this properly yet, can we shunt your second request for the future?

**Comment by percyliang** [comment]
Can we just not handle the --- then?

**Comment by kashizui** [comment]
@percyliang 
I'm convinced argparse and argcomplete are not built to handle some of this. After much keysmashing I've enabled:
- completion for alias::worksheet arguments
- completion for key:bundlename/subfile/tree 

But for some reason the latter only works for the first target spec!
After some inspection of the argcomplete code, looks like its ways of determining what the next positional argument is not very robust... it fails to realize that the next argument could be another target_spec, or that it might even be the command. Finding a good solution may take a lot of time.

I think we're getting to the point where we're pushing the limits of off-the-shelf solutions and may have to begin implementing our own argument parsers/completers, like AWS CLI does, lest we just pile on the hacks:
https://github.com/aws/aws-cli/tree/9c5e3faa824c4ddbc985980af5fe66e2704b2df2/awscli

**Comment by percyliang** [comment]
Ok, that's fine.  Can you leave a TODO in the code about this?

**Comment by kashizui** [comment]
Oops, sure

**Comment by kashizui** [comment]
https://github.com/codalab/codalab-cli/commit/a94c17fb03e8b97551554a523894fb2871ec61e8

**Comment by kashizui** [comment]
Partially fixed by #271:
- completion for alias::worksheet arguments
- completion for key:bundlename/subfile/tree for the first target_spec

Proposing reduced priority until further developments.

**Comment by kashizui** [comment]
Another bug:

```
POST /api/worksheets/command/

Query params:


Form params:


JSON body:
{
    "autocomplete": true,
    "command": "kill 0xd7",
    "worksheet_uuid": "0x209f3091658b42bf96b72a836e1d2b51"
}

Local variables:
completion={u'host_worksheets': [{u'uuid': u'0x5ab12330028b44ad9ee6f7bb465735ee',
...,
u'request_disk': u'', u'exitcode': 0}}
prefix=u'0xd7'

Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/codalab/server/rest_server.py", line 146, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/azureuser/codalab-cli/codalab/server/json_api_plugin.py", line 17, in wrapper
    result = callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 720, in post_worksheets_command
    'completions': service.complete_command(data['worksheet_uuid'], data['command'])
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 531, in complete_command
    return cli.complete_command(command)
  File "/home/azureuser/codalab-cli/codalab/lib/bundle_cli.py", line 711, in complete_command
    return map(clean, cf._get_completions(comp_words, cword_prefix, cword_prequote, first_colon_pos))
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/argcomplete/__init__.py", line 233, in _get_completions
    completions = self.collect_completions(active_parsers, parsed_args, cword_prefix, debug)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/argcomplete/__init__.py", line 422, in collect_completions
    completions)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/argcomplete/__init__.py", line 365, in _complete_active_option
    if self.validator(c, cword_prefix)]
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/argcomplete/__init__.py", line 102, in default_validator
    return completion.startswith(prefix)
AttributeError: 'dict' object has no attribute 'startswith'
```

**Comment by epicfaace** [comment]
I'm going to close this since we did implement some level of autocomplete, and I don't think we need to take this further at the moment.
