### ISSUE TITLE
[USER ISSUE] cl edit doesn't work

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#2237]
**Describe the bug**
When I try to use `cl edit` from the command line I get an exception

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 0x23acc0bd2aa044fd9300f73d3a5fbbb9
- *UUID of problem bundle (please don't delete)*: n/a
- *Error message received from Codalab (if applicable)*:

```
Traceback (most recent call last):
  File "/home/robinjia/.local/bin/cl", line 8, in <module>
    sys.exit(main())
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/lib/bundle_cli.py", line 864, in do_command
    structured_result = command_fn()
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/lib/bundle_cli.py", line 858, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/lib/bundle_cli.py", line 1708, in do_edit_command
    bundle_subclass, info['metadata']
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/lib/metadata_util.py", line 73, in request_missing_metadata
    return parse_metadata_form(bundle_subclass, form_result)
  File "/home/robinjia/.local/lib/python3.6/site-packages/codalab/lib/metadata_util.py", line 85, in parse_metadata_form
    if line != '' and not line.startswith('//'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

 - *OS (if on CLI)*: Ubuntu 18.04
 - *Codalab CLI Version (if on CLI)*: 0.5.13
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :
1. `cl edit ^1` or it seems any bundle (mine opens vim)
2. Save and close

**Expected behavior**
Bundle info should update with no exception thrown

**Comment by candicegjing** [comment]
I verify that I am seeing the same error in cl edit. Seems like a string encoding/decoding issue.
