### ISSUE TITLE
Set python-dateutil to 2.8.1

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#2258]
```
Traceback (most recent call last):
  File "/u/scr/pengqi/anaconda3_slurm/lib/python3.6/site-packages/codalab/worker/worker.py", line 183, in start
    self.process_runs()
  File "/u/scr/pengqi/anaconda3_slurm/lib/python3.6/site-packages/codalab/worker/worker.py", line 326, in process_runs
    self.runs[bundle_uuid] = self.run_state_manager.transition(run_state)
  File "/u/scr/pengqi/anaconda3_slurm/lib/python3.6/site-packages/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/u/scr/pengqi/anaconda3_slurm/lib/python3.6/site-packages/codalab/worker/worker_run_state.py", line 395, in _transition_from_RUNNING
    run_state = check_resource_utilization(run_state)
  File "/u/scr/pengqi/anaconda3_slurm/lib/python3.6/site-packages/codalab/worker/worker_run_state.py", line 342, in check_resource_utilization
    container_time_total = docker_utils.get_container_running_time(run_state.container)
  File "/u/scr/pengqi/anaconda3_slurm/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 50, in wrapper
    return f(*args, **kwargs)
  File "/u/scr/pengqi/anaconda3_slurm/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 294, in get_container_running_time
    container_running_time = parser.isoparse(end_time) - parser.isoparse(start_time)
  File "/u/scr/pengqi/anaconda3_slurm/lib/python3.6/site-packages/dateutil/parser/isoparser.py", line 37, in func
    return f(self, str_in, *args, **kwargs)
  File "/u/scr/pengqi/anaconda3_slurm/lib/python3.6/site-packages/dateutil/parser/isoparser.py", line 136, in isoparse
    components += self._parse_isotime(dt_str[pos + 1:])
  File "/u/scr/pengqi/anaconda3_slurm/lib/python3.6/site-packages/dateutil/parser/isoparser.py", line 363, in _parse_isotime
    raise ValueError('Unused components in ISO string')
ValueError: Unused components in ISO string
2020-05-10 12:02:48,759 Sleeping for 1 hour due to exception...please help me!
```
User reported upgraded `python-dateutil` from `3.7.5` to `3.8.1` fixed this issue. We need to fix this in our package requirement.

**Comment by candicegjing** [comment]
To match the version in docker image: set `python-dateutil` to `2.8.1`
