### ISSUE TITLE
Low priority: show better error message when switching to an instance alias that doesn't exist.

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2291]
Super low prio:

```
$ cl alias
localhost: http://localhost:2900
main: https://worksheets.codalab.org
```

```
$ cl work stanford::
Traceback (most recent call last):
  File "/juice/scr/nfliu/miniconda3/bin/cl", line 8, in <module>
    sys.exit(main())
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 864, in do_command
    structured_result = command_fn()
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 858, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 2895, in do_work_command
    client, worksheet_uuid = self.parse_client_worksheet_uuid(args.worksheet_spec)
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 716, in parse_client_worksheet_uuid
    worksheet_uuid = self.resolve_worksheet_uuid(client, base_worksheet_uuid, spec)
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 644, in resolve_worksheet_uuid
    'worksheets', params={'base': base_worksheet_uuid, 'specs': [worksheet_spec]}
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 425, in fetch_one
    results = self.fetch(resource_type, resource_id=resource_id, params=params)
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 415, in fetch
    query_params=self._pack_params(params),
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/worker/rest_client.py", line 62, in _make_request
    access_token = self._get_access_token()
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/lib/codalab_manager.py", line 426, in <lambda>
    lambda: self._authenticate(address, auth_handler),
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/lib/codalab_manager.py", line 496, in _authenticate
    token_info = auth_handler.generate_token('credentials', username, password)
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/server/auth.py", line 42, in generate_token
    {'grant_type': 'password', 'username': username, 'password': key}
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/site-packages/codalab/server/auth.py", line 58, in _make_token_request
    data=urllib.parse.urlencode(data).encode('utf-8'),
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/urllib/request.py", line 354, in full_url
    self._parse()
  File "/juice/scr/nfliu/miniconda3/lib/python3.7/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'stanford/rest/oauth2/token'
```

**Comment by yshen-google** [comment]
I propose to have a try-catch block in `resolve_worksheet_uuid()` when fetching a worksheet based on uuid to capture ValueError, and within the catch block print out proper error messages. WDYT?

**Comment by nelson-liu** [comment]
that sounds good!
