### ISSUE TITLE
Cl search returning bundle permission errors. 

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab-worksheets#23]
When searching for a simple sleep run I am getting permission errors.  I believe this is happening because user Raisins has a worksheet shared with him that he can edit created by another user. Which has bundles called run-sleep

```
cl search sleep
Traceback (most recent call last):
  File "/Users/Dave/Work/codalab/src/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 67, in <module>
    run_cli()
  File "/Users/Dave/Work/codalab/src/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 58, in run_cli
    cli.do_command(sys.argv[1:])
  File "/Users/Dave/Work/codalab/src/codalab-cli/codalab/lib/bundle_cli.py", line 320, in do_command
    command_fn(remaining_args, parser)
  File "/Users/Dave/Work/codalab/src/codalab-cli/codalab/lib/bundle_cli.py", line 686, in do_search_command
    bundle_infos = client.get_bundle_infos(bundle_uuids)
  File "/Users/Dave/Work/codalab/src/codalab-cli/codalab/client/remote_bundle_client.py", line 149, in inner
    raise PermissionError(e.faultString[index + 1:])
codalab.common.PermissionError: User Raisins(4) does not have sufficient permissions on bundles [u'0x41fa7ccce4af46729741d13a4430aa11', u'0x3c85781dd65242f4a194630b10e802d8', u'0x936c961f5423467b8bfabeaf0f80e1e5', u'0x1f19e667756340a79157396d909a5c75', u'0x04c1ff46b5aa4b5eb7d39c60969c0c4c', u'0x33a27d65615545039ea15937853d734c', u'0xadd67d0b100f4e9d86f2597b5bef61ef', u'0xd195388fd49c4898bc5ddcea16212a6f', u'0x6eef40d89cb545f2a67716bd77a5600b', u'0x6e2a9cd269314d45b4e4e466be3078a2', u'0x27353c82a9654920af1f9c3c2aecb77c', u'0x4016aba940d349e9b2e8c413d0c3230d', u'0x96fa52a4cb0f456a92042c6b98315b7d', u'0x8bc6439f4d4e43d696e907a362ddbf82', u'0x9d393372574b415aa682c9789ed27127', u'0x895c4f2925894450a1f33b515307b94d', u'0x066945d0c7094792b467f5c17a31539c', u'0x6ce47fca4afe41439d48c2749dd35be5', u'0x67792d263c484ff1890d240b0b21f24d'] (have ['all', 'all', 'all', 'all', 'all', 'all', 'all', 'none', 'all', 'all', 'all', 'none', 'all', 'all', 'all', 'all', 'all', 'all', 'all'], need read).
```

**Comment by percyliang** [comment]
Fixed by #53
