### ISSUE TITLE
UUID matching error: TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#2349]
Got this error in dev server

```>> timeout 60s cl rm   (exit code 1, time 0.69s [limit: 15s,60s]; avg 0.00s; max 0.79s)
Traceback (most recent call last):
  File "/usr/local/bin/cl", line 11, in 
    load_entry_point('codalab', 'console_scripts', 'cl')()
  File "/opt/codalab-worksheets/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 875, in do_command
    structured_result = command_fn()
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 869, in 
    command_fn = lambda: args.function(self, args)
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 1909, in do_rm_command
    bundle_uuids = self.target_specs_to_bundle_uuids(client, worksheet_uuid, args.bundle_spec)
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 550, in target_specs_to_bundle_uuids
    for spec in target_specs
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 550, in 
    for spec in target_specs
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 591, in resolve_target
    bundle_uuid = BundleCLI.resolve_bundle_uuid(client, worksheet_uuid, bundle_spec)
  File "/opt/codalab-worksheets/codalab/lib/bundle_cli.py", line 625, in resolve_bundle_uuid
    if spec_util.UUID_REGEX.match(bundle_spec):
TypeError: expected string or bytes-like object
```

**Comment by candicegjing** [comment]
This is due to the improperly configured dev environment. The work left to be done in this ticket is to reconfigure and set up the dev environment. Currently, it's blocked by two major conferences deadline (EMNLP and NeurIPS deadlines) which is this weekend.

**Comment by candicegjing** [comment]
This is fixed by restoring the dev environment.
