### ISSUE TITLE
stats on worksheets.codalab.org doesn't load

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#235]
https://worksheets.codalab.org/worksheets/0xd1166d24875f4193a07fff841a6d320e/

**Comment by kashizui** [comment]
```
Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/bottle.py", line 1738, in wrapper
    json_response = dumps(rv)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 12, 16, 21, 18, 1) is not JSON serializable
```

**Comment by kashizui** [comment]
Appears to be a datetime instance in the 'frozen' field of a subworksheet info, which is not JSON serializable. I think it only occurs in a wsearch table, and so the bug occurs more rarely. Experimenting with fixes.

**Comment by kashizui** [comment]
Tried a simple fix but now the javascript is failing. Will continue this another day.

**Comment by percyliang** [comment]
We are serializing other dates like created_date, aren't we?  Shouldn't
frozen be treated the same way?
