### ISSUE TITLE
'WorkerInfoAccessor' object is not subscriptable

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2426]
Saw this error in the logs of the bundle manager for [this GitHub Actions run](https://github.com/codalab/codalab-worksheets/runs/779600298):

```
Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 80, in run
    self._run_iteration()
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 100, in _run_iteration
    self._schedule_run_bundles()
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 714, in _schedule_run_bundles
    self._schedule_run_bundles_on_workers(workers, staged_bundles_to_run, user_info_cache)
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 417, in _schedule_run_bundles_on_workers
    if worker['exit_after_num_runs'] < workers[worker['worker_id']]['exit_after_num_runs']:
TypeError: 'WorkerInfoAccessor' object is not subscriptable
```

Not sure if this was actually what was causing the GitHub Actions build to fail, but it's probably something we should fix anyway.

cc @teetone

**Comment by epicfaace** [comment]
fixed by #2419
