### ISSUE TITLE
'Metadata' object has no attribute 'created'

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2430]
Got this log from the bundle manager:

```
Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 80, in run
    self._run_iteration()
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 101, in _run_iteration
    self._fail_unresponsive_bundles()
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 682, in _fail_unresponsive_bundles
    if now - bundle.metadata.created > BUNDLE_TIMEOUT_DAYS * SECONDS_PER_DAY:
AttributeError: 'Metadata' object has no attribute 'created'
```

**Comment by nelson-liu** [comment]
Dupe of https://github.com/codalab/codalab-worksheets/issues/2324 , right? I think this also might be related to https://github.com/codalab/codalab-worksheets/issues/2379 / the same root fix would fix both of them.
