### ISSUE TITLE
Worker is not robust to docker network removal

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2439]
**Describe the bug**

It seems like sometimes, the worker docker networks get removed. On an already-existing worker that is trying to run another job, I got the following error:

```
2020-06-18 16:48:18,019 Cannot start Docker container: Unable to start Docker container: 404 Client Error: Not Found ("network cl_worker_nfliu-codalab-slurm-worker-main-standard-4dd7cd2c_network_int not found")
2020-06-18 16:48:18,034 Traceback (most recent call last):
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/c5e44547ac0562ec3c62614b6d9600d44321a74c7e408a164aa31781b8b75395/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 51, in wrapper
    return f(*args, **kwargs)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 186, in start_bundle_container
    stdin_open=tty,
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/models/containers.py", line 791, in run
    container.start()
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/models/containers.py", line 392, in start
    return self.client.api.start(self.id, **kwargs)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/api/container.py", line 1091, in start
    self._raise_for_status(res)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("network cl_worker_nfliu-codalab-slurm-worker-main-standard-4dd7cd2c_network_int not found")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/worker_run_state.py", line 339, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 55, in wrapper
    check_for_user_error(e)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 48, in check_for_user_error
    raise DockerException(error_message)
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 404 Client Error: Not Found ("network cl_worker_nfliu-codalab-slurm-worker-main-standard-4dd7cd2c_network_int not found")

Traceback (most recent call last):
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/c5e44547ac0562ec3c62614b6d9600d44321a74c7e408a164aa31781b8b75395/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 51, in wrapper
    return f(*args, **kwargs)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 186, in start_bundle_container
    stdin_open=tty,
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/models/containers.py", line 791, in run
    container.start()
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/models/containers.py", line 392, in start
    return self.client.api.start(self.id, **kwargs)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/api/container.py", line 1091, in start
    self._raise_for_status(res)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("network cl_worker_nfliu-codalab-slurm-worker-main-standard-4dd7cd2c_network_int not found")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/worker.py", line 199, in start
    self.process_runs()
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/worker.py", line 365, in process_runs
    self.runs[uuid] = self.run_state_manager.transition(run_state)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/worker_run_state.py", line 339, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 55, in wrapper
    check_for_user_error(e)
  File "/juice/scr/nfliu/miniconda3/envs/cl_nfliu_main/lib/python3.6/site-packages/codalab/worker/docker_utils.py", line 48, in check_for_user_error
    raise DockerException(error_message)
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 404 Client Error: Not Found ("network cl_worker_nfliu-codalab-slurm-worker-main-standard-4dd7cd2c_network_int not found")
2020-06-18 16:48:18,038 Sleeping for 1 hour due to exception...please help me!
```

Logging on to the machine, it appears that the network is indeed not there. Looking at the list, every triple of docker network prefix should have one with suffixes `ext`, `general`, and `int`. However, some of these triples are missing the `int` network.

```
$ docker network ls
NETWORK ID          NAME                                                                          DRIVER              SCOPE
d3b08a9ce680        bridge                                                                        bridge              local
58379732b6b9        cl_worker_nfliu-codalab-slurm-worker-main-standard-4dd7cd2c_network_ext       bridge              local
a7fe7b588c3b        cl_worker_nfliu-codalab-slurm-worker-main-standard-4dd7cd2c_network_general   bridge              local
6e4cdbb88be5        cl_worker_nfliu-codalab-slurm-worker-main-standard-be8ee085_network_ext       bridge              local
7931e9798632        cl_worker_nfliu-codalab-slurm-worker-main-standard-be8ee085_network_general   bridge              local
48f7179e258a        cl_worker_nfliu-codalab-slurm-worker-main-standard-be8ee085_network_int       bridge              local
e3be37f75563        cl_worker_nfliu-codalab-slurm-worker-stanford-low-21f7d0d3_network_ext        bridge              local
1cfda3e85361        cl_worker_nfliu-codalab-slurm-worker-stanford-low-21f7d0d3_network_general    bridge              local
e833baff02f1        cl_worker_nfliu-codalab-slurm-worker-stanford-low-21f7d0d3_network_int        bridge              local
d0cc4f087587        cl_worker_nfliu-codalab-slurm-worker-stanford-low-283b6698_network_ext        bridge              local
2b93ef5bbd35        cl_worker_nfliu-codalab-slurm-worker-stanford-low-283b6698_network_general    bridge              local
f3f52a9ca04d        cl_worker_nfliu-codalab-slurm-worker-stanford-low-06378f73_network_ext        bridge              local
2513f5792155        cl_worker_nfliu-codalab-slurm-worker-stanford-low-06378f73_network_general    bridge              local
1d48c87c0537        cl_worker_nfliu-codalab-slurm-worker-stanford-low-62773d58_network_ext        bridge              local
7ef521854022        cl_worker_nfliu-codalab-slurm-worker-stanford-low-62773d58_network_general    bridge              local
19b30eff830b        cl_worker_nfliu-codalab-slurm-worker-stanford-low-b7c9bc22_network_ext        bridge              local
9c4614a07ee2        cl_worker_nfliu-codalab-slurm-worker-stanford-low-b7c9bc22_network_general    bridge              local
d4c17fc1632a        cl_worker_nfliu-codalab-slurm-worker-stanford-low-b7c9bc22_network_int        bridge              local
e6c87b4b8737        cl_worker_nfliu-codalab-slurm-worker-stanford-low-f3a582a4_network_ext        bridge              local
ae03195fb837        cl_worker_nfliu-codalab-slurm-worker-stanford-low-f3a582a4_network_general    bridge              local
283a6cf62094        cl_worker_nfliu-codalab-slurm-worker-stanford-low-f3a582a4_network_int        bridge              local
574ec1166bbe        host                                                                          host                local
b24a9a7bd93e        none                                                                          null                local
```

So, one issue is to figure out where the `int` network is going. Another issue is to make the worker robust to these changes in docker networks. Currently, the worker creates docker networks (or reuses existing ones) when it initially launches, but maybe it's worth doing it before each container the worker starts?

**Comment by nelson-liu** [comment]
I'm also seeing this occasionally in jobs with the `ext` network. I'm starting to think that the best way to handle this is to just check for (and create, if necessary), the networks more often.

```
10332:codalab.worker.docker_utils.DockerException: Unable to start Docker container: 404 Client Error: Not Found ("network cl_worker_nfliu-codalab-slurm-worker-main-standard-8bc811e7_network_ext not found")
```
