### ISSUE TITLE
codalab-service doesn't work

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2510]
`pip install codalab` then run `codalab-service start`.

```
$ codalab-service start
Traceback (most recent call last):
  File "/home/pliang/.local/bin/codalab-service", line 7, in <module>
    from codalab_service import main
ModuleNotFoundError: No module named 'codalab_service'
```

**Comment by percyliang** [comment]
Motivation: this would allow people to start local CodaLab instances which would make it easier to try out experiments very fast locally.

**Comment by yiboliu** [comment]
Currently running the command locally produces this stacktrace:
```Traceback (most recent call last):
  File "/Users/yibol/codalab-worksheets/venv/bin/codalab-service", line 33, in <module>
    sys.exit(load_entry_point('codalab', 'console_scripts', 'codalab-service')())
  File "/Users/yibol/codalab-worksheets/codalab_service.py", line 98, in main
    service_manager.execute()
  File "/Users/yibol/codalab-worksheets/codalab_service.py", line 578, in execute
    self.start_services()
  File "/Users/yibol/codalab-worksheets/codalab_service.py", line 758, in start_services
    'if [ $(alembic current | wc -l) -gt 0 ]; then echo upgrade; alembic upgrade head; fi'
  File "/Users/yibol/codalab-worksheets/codalab_service.py", line 698, in run_service_cmd
    ' bash -c \'%s\'' % cmd
  File "/Users/yibol/codalab-worksheets/codalab_service.py", line 677, in _run_compose_cmd
    raise Exception('Command exited with code {}'.format(popen.returncode))
Exception: Command exited with code 255
```

**Comment by yiboliu** [comment]
If I reinstall with codalab-yibol and then run with `codalab-service start`, I get error similar to #2800 
```Traceback (most recent call last):
  File "/Users/yibol/codalab-worksheets/env/bin/codalab-service", line 33, in <module>
    sys.exit(load_entry_point('codalab', 'console_scripts', 'codalab-service')())
  File "/Users/yibol/codalab-worksheets/env/bin/codalab-service", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/Users/yibol/codalab-worksheets/env/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File "/Users/yibol/codalab-worksheets/env/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for codalab
```

**Comment by yiboliu** [comment]
```Traceback (most recent call last):
  File "/Users/yibol/codalab-worksheets/aenv/bin/codalab-service", line 33, in <module>
    sys.exit(load_entry_point('codalab==0.5.24', 'console_scripts', 'codalab-service')())
  File "/Users/yibol/codalab-worksheets/aenv/bin/codalab-service", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/yibol/codalab-worksheets/aenv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'codalab_service'

**Comment by yiboliu** [comment]
By manually tracing the code, the suspected cause could be sys.modules isn't pointed to virtual environment activated. So it can't find codalab-service

**Comment by yiboliu** [comment]
As investigated so far, the problem could be that unlike other entry-points:
```EntryPoint(name='cl', value='codalab.bin.cl:main', group='console_scripts')
EntryPoint(name='cl-bundle-manager', value='codalab.bin.bundle_manager:main', group='console_scripts')
EntryPoint(name='cl-competitiond', value='scripts.competitiond:main', group='console_scripts')
EntryPoint(name='cl-server', value='codalab.bin.server:main', group='console_scripts')
EntryPoint(name='cl-worker', value='codalab.worker.main:main', group='console_scripts')
EntryPoint(name='cl-worker-manager', value='codalab.worker_manager.main:main', group='console_scripts')
EntryPoint(name='codalab-service', value='codalab_service:main', group='console_scripts')
```
codalab-service's value doesn't have a module installed, whereas like cl does have a codalab.bin.cl:
![image](https://user-images.githubusercontent.com/18689351/96674368-828a1980-131d-11eb-8eeb-3623718084b5.png)
So my proposed solution would be to add the codalab-service.py to the venv/lib/python3.6/site-packages/.
