### ISSUE TITLE
Requesting too little memory for a run can cause a worker to go down

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2514]
Requesting as little as `10m` for a run can cause a worker to go down with the following error:
```
2020-06-27 03:09:59,180 Cannot start Docker container: Unable to start Docker container: 500 Server Error: 
Internal Server Error ("OCI runtime create failed: container_linux.go:349: starting container process caused 
"process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused 
\\\"failed to write \\\\\\\"10485760\\\\\\\" to \\\\\\\"/sys/fs/cgroup/memory/docker
/07dff7f7e04f43b430b20266840119e33a0070883eaa35d16774525aa352ee5c/memory.limit_in_bytes\\\\\\\": 
write /sys/fs/cgroup/memory/docker/07dff7f7e04f43b430b20266840119e33a0070883eaa35d16774525aa352ee5c/memory.limit_in_bytes: device or resource busy\\\"\"": unknown")
```
See this related issue: https://github.com/moby/moby/issues/38921

**Comment by candicegjing** [comment]
This is also happening on Prod machine:
```
Traceback (most recent call last):
  File "/opt/codalab/worker/docker_utils.py", line 51, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab/worker/docker_utils.py", line 186, in start_bundle_container
    stdin_open=tty,
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 791, in run
    container.start()
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 392, in start
    return self.client.api.start(self.id, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 1091, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 203, in start
    self.process_runs()
  File "/opt/codalab/worker/worker.py", line 378, in process_runs
    self.runs[uuid] = self.run_state_manager.transition(run_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/worker_run_state.py", line 339, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/opt/codalab/worker/docker_utils.py", line 55, in wrapper
    check_for_user_error(e)
  File "/opt/codalab/worker/docker_utils.py", line 48, in check_for_user_error
    raise DockerException(error_message)
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 500 Server Error: Internal Server Error ("OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write
\\\\\\\"8388608\\\\\\\" to \\\\\\\"/sys/fs/cgroup/memory/docker/a5475e95e98bbb534870dfdf290e91251f54e5c13be07a7b6819619a2dba48ef/memory.limit_in_bytes\\\\\\\": 
write /sys/fs/cgroup/memory/docker/a5475e95e98bbb534870dfdf290e91251f54e5c13be07a7b6819619a2dba48ef/memory.limit_in_bytes: device or resource busy\\\"\"": unknown")
2020-06-30 18:48:28,935 Sleeping for 1 hour due to exception...please help me!
```

**Comment by candicegjing** [comment]
Sometimes this failure is due to the fact that the memory user requested is not enough to start a docker container. Need to fail the container properly and not block the worker from running other jobs.

**Comment by yipenghe** [comment]
Hmm, I thought this happened before and was addressed, was it only addressed on the frontend side

**Comment by candicegjing** [comment]
> Hmm, I thought this happened before and was addressed, was it only addressed on the frontend side

I don't think they are the same issue.
