### ISSUE TITLE
"unable to create context store: $HOME is not defined"

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2546]
I deleted my docker images and built / run an instance of codalab -- it failed with the following error:

```
quota 100y && cl config server/default_user_info/parallel_run_quota 100')
process: The CODALAB_ADMIN_EMAIL variable is not set. Defaulting to a blank string.
process: The CODALAB_SUPPORT_EMAIL variable is not set. Defaulting to a blank string.
process: The CODALAB_EMAIL_HOST variable is not set. Defaulting to a blank string.
process: The CODALAB_EMAIL_USERNAME variable is not set. Defaulting to a blank string.
process: The CODALAB_EMAIL_PASSWORD variable is not set. Defaulting to a blank string.
process: The CODALAB_SERVER variable is not set. Defaulting to a blank string.
process: The CODALAB_SHARED_FILE_SYSTEM variable is not set. Defaulting to a blank string.
process: The CODALAB_PUBLIC_WORKERS variable is not set. Defaulting to a blank string.
process: unable to create context store: $HOME is not definedTraceback (most recent call last):
  File "codalab_service.py", line 767, in <module>
    main()
  File "codalab_service.py", line 97, in main
    service_manager.execute()
  File "codalab_service.py", line 534, in execute
    self.start_services()
  File "codalab_service.py", line 701, in start_services
    self.run_service_cmd(' && '.join(commands))
  File "codalab_service.py", line 648, in run_service_cmd
    ' bash -c \'%s\'' % cmd
  File "codalab_service.py", line 627, in _run_compose_cmd
    raise Exception('Command exited with code {}'.format(popen.returncode))
Exception: Command exited with code 1
```

**Comment by epicfaace** [comment]
This is actually due to my Docker version (I was using the beta channel) -- switched to the stable channel and it's working now.
