### ISSUE TITLE
[Prod] Run bundles are stuck in uploading results

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2722]
In production, some bundles are stuck with the status `Uploading results: 14.5g done (archived size)` and continues to occupy the worker. Killing the bundles doesn't do anything either.

**Comment by nelson-liu** [comment]
(fwiw, i've seen that codalab often chokes when you're uploading large bundles like this)

**Comment by epicfaace** [comment]
Sample bundle on dev:

https://worksheets-dev.codalab.org/bundles/0xf8e2febb21fe46fd96f0514eaf3e081b

Worker logs:

![image](https://user-images.githubusercontent.com/1689183/104778651-b7a2de00-574b-11eb-8490-9f49d4d31a05.png)

**Comment by epicfaace** [comment]
This issue is actually happening on the rest server. Here's the stack trace that comes from the "Invalid archive upload" error (this normally isn't logged; I had to modify codalab on my local computer to log it):

```
2021-01-22 21:29:27,697 - ERROR (/opt/codalab-worksheets/codalab/lib/zip_util.py:79) - Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/lib/zip_util.py", line 66, in unpack
    un_tar_directory(source, dest_path, 'gz')
  File "/opt/codalab-worksheets/codalab/worker/file_util.py", line 170, in un_tar_directory
    tar.extract(member, directory_path)
  File "/usr/lib/python3.6/tarfile.py", line 2054, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.6/tarfile.py", line 2124, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.6/tarfile.py", line 2173, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/usr/lib/python3.6/tarfile.py", line 249, in copyfileobj
    buf = src.read(bufsize)
  File "/usr/lib/python3.6/tarfile.py", line 539, in read
    buf = self._read(size)
  File "/usr/lib/python3.6/tarfile.py", line 552, in _read
    buf = self.__read(self.bufsize)
  File "/usr/lib/python3.6/tarfile.py", line 572, in __read
    buf = self.fileobj.read(self.bufsize)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/http/body.py", line 215, in read
    data = self.reader.read(1024)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/http/body.py", line 30, in read
    self.buf.write(next(self.parser))
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/http/body.py", line 63, in parse_chunked
    rest = unreader.read()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by epicfaace** [comment]
Helpful screenshots of the problem on dev:

![image](https://user-images.githubusercontent.com/1689183/107442651-7660dc80-6b05-11eb-947c-eb877aeda035.png)

![image](https://user-images.githubusercontent.com/1689183/107442936-e0798180-6b05-11eb-9961-47fdcc1cf14e.png)

![image](https://user-images.githubusercontent.com/1689183/107444456-a2319180-6b08-11eb-9d28-4949b8fa12eb.png)


Reproduced this locally and got the following error:

```
2021-02-19 09:49:21,351 Uploading results: 16700819 done (archived size)
2021-02-19 09:49:21,351         Reading chunk...
2021-02-19 09:49:21,351         Finished reading chunk. Sending chunk...
2021-02-19 09:49:21,351 No more to_send, break. Bytes uploaded: 16700819
2021-02-19 09:49:21,351 About to read the response, url: /bundles/0x4715ce763ec8474d94b6738de620937b/contents/blob/
2021-02-19 10:09:21,367 Finished reading the response, url: /bundles/0x4715ce763ec8474d94b6738de620937b/contents/blob/
Traceback (most recent call last):
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/worker/bundle_service_client.py", line 22, in wrapper
    return f(*args, **kwargs)
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/worker/bundle_service_client.py", line 172, in update_bundle_contents
    progress_callback=progress_callback,
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/worker/rest_client.py", line 184, in _upload_with_chunked_encoding
    StringIO(response.read().decode()),
urllib.error.HTTPError: HTTP Error 504: Gateway Time-out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_upload.py", line 33, in <module>
    client.update_bundle_contents("worker_id", bundle_uuid, path, exclude_patterns=None, progress_callback=progress_callback)
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/worker/bundle_service_client.py", line 39, in wrapper
    400 <= e.code < 500,
codalab.worker.bundle_service_client.BundleServiceException: Unable to update bundle contents in bundle service: Gateway Timeout - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.12.0</center>
</body>
</html>
```

nginx logs:

```
172.28.0.1 - - [19/Feb/2021:15:09:21 +0000] "PUT /rest/bundles/0x4715ce763ec8474d94b6738de620937b/contents/blob/?filename=bundle.tar.gz&finalize_on_success=0 HTTP/1.1" 504 183 "-" "-"
```

REST Server logs are normal.
