### ISSUE TITLE
Unable to start a container - OCI runtime error

### ISSUE THREAD

**Issue by yiboliu** [codalab/codalab-worksheets#2736]
**Describe the bug**
```2020-08-10 04:19:36,734 Cannot start Docker container: Unable to start Docker container: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown")
2020-08-10 04:19:36,735 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/4f14b179c0050cfb07267153cd6d964c6d530db62655269e37d4a9ab991227ff/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/docker_utils.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab/worker/docker_utils.py", line 192, in start_bundle_container
    stdin_open=tty,
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 809, in run
    container.start()
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 400, in start
    return self.client.api.start(self.id, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker_run_state.py", line 339, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/opt/codalab/worker/docker_utils.py", line 61, in wrapper
    check_for_user_error(e)
  File "/opt/codalab/worker/docker_utils.py", line 54, in check_for_user_error
    raise DockerException(error_message)
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown")

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/4f14b179c0050cfb07267153cd6d964c6d530db62655269e37d4a9ab991227ff/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/docker_utils.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab/worker/docker_utils.py", line 192, in start_bundle_container
    stdin_open=tty,
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 809, in run
    container.start()
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 400, in start
    return self.client.api.start(self.id, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 242, in start
    self.process_runs()
  File "/opt/codalab/worker/worker.py", line 441, in process_runs
    self.runs[uuid] = self.run_state_manager.transition(run_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/worker_run_state.py", line 339, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/opt/codalab/worker/docker_utils.py", line 61, in wrapper
    check_for_user_error(e)
  File "/opt/codalab/worker/docker_utils.py", line 54, in check_for_user_error
    raise DockerException(error_message)
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown")
2020-08-10 04:19:36,736 Sleeping for 1 hour due to exception...please help me!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/4f14b179c0050cfb07267153cd6d964c6d530db62655269e37d4a9ab991227ff/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/docker_utils.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab/worker/docker_utils.py", line 192, in start_bundle_container
    stdin_open=tty,
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 809, in run
    container.start()
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 400, in start
    return self.client.api.start(self.id, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 242, in start
    self.process_runs()
  File "/opt/codalab/worker/worker.py", line 441, in process_runs
    self.runs[uuid] = self.run_state_manager.transition(run_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/worker_run_state.py", line 339, in _transition_from_PREPARING
    runtime=self.docker_runtime,
  File "/opt/codalab/worker/docker_utils.py", line 61, in wrapper
    check_for_user_error(e)
  File "/opt/codalab/worker/docker_utils.py", line 54, in check_for_user_error
    raise DockerException(error_message)
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cl-worker", line 33, in <module>
    sys.exit(load_entry_point('codalab', 'console_scripts', 'cl-worker')())
  File "/opt/codalab/worker/main.py", line 263, in main
    worker.start()
  File "/opt/codalab/worker/worker.py", line 278, in start
    sleep(5)
NameError: name 'sleep' is not defined```

**Codalab Information**
- *Your username*: yiboliu
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*: shown above
 - *OS (if on CLI)*: Linux
 - *Codalab CLI Version (if on CLI)*: 0.5.20
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :
1. ssh into vm-clws-prod-worker-1 and check the logs of codalab_worker_1

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by JiexingQi** [comment]
I met the same problem? Can you give me some suggestions? Thank you!

**Comment by epicfaace** [comment]
@JiexingQi What command are you running when you see this error?

**Comment by JiexingQi** [comment]
Thank you for your reply, @epicfaace , I just want to run a docker on codalab, the command are
```
CodaLab> cl run --request-docker-image jxqi/hello_docker "docker ps"
0x7eb7c81db0cd4ffaafd52cae0441a42b
```
and what I run on my server is
```
(codalab) jxqi@main-12:~/Study/codalab/spider$ cl-worker --verbose
```
and it just get error
```
2022-03-09 14:38:08,933 Connecting to https://worksheets.codalab.org /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/main.py 199
Username: jxqi
Password: 
2022-03-09 14:38:41,179 Loaded 0 dependencies, 0 paths from cache. /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/dependency_manager.py 118
2022-03-09 14:38:41,327 Trying paths: ['/home/jxqi/.docker/config.json', '/home/jxqi/.dockercfg'] /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/utils/config.py 21
2022-03-09 14:38:41,327 Found file at path: /home/jxqi/.docker/config.json /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/utils/config.py 25
2022-03-09 14:38:41,375 Found 'auths' section /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 182
2022-03-09 14:38:41,375 Found entry (registry='https://index.docker.io/v1/', username='jxqi') /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 142
2022-03-09 14:38:41,393 Looking for auth config /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 41
2022-03-09 14:38:41,393 Looking for auth entry for 'docker.io' /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 242
2022-03-09 14:38:41,393 Found 'https://index.docker.io/v1/' /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 250
2022-03-09 14:38:41,393 Found auth config /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 54
2022-03-09 14:38:45,831 GPUs: ['0, GPU-a3f26bfe-1c97-49f9-1b9f-5195cb6b7e7c', '1, GPU-11d62a7c-fdcb-d530-2999-f26b17e98823', '2, GPU-9c2f6100-f8b7-e0c3-309f-baa8d0d531ff', '3, GPU-a493947c-151e-998f-954d-1c251903c99e'] /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/docker_utils.py 137
2022-03-09 14:38:45,911 Trying paths: ['/home/jxqi/.docker/config.json', '/home/jxqi/.dockercfg'] /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/utils/config.py 21
2022-03-09 14:38:45,912 Found file at path: /home/jxqi/.docker/config.json /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/utils/config.py 25
2022-03-09 14:38:45,973 Found 'auths' section /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 182
2022-03-09 14:38:45,973 Found entry (registry='https://index.docker.io/v1/', username='jxqi') /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 142
2022-03-09 14:38:45,980 Creating docker network codalab_worker_network_general /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker.py 146
2022-03-09 14:38:46,039 Created docker network codalab_worker_network_general /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker.py 149
2022-03-09 14:38:46,039 Creating docker network codalab_worker_network_ext /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker.py 146
2022-03-09 14:38:46,137 Created docker network codalab_worker_network_ext /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker.py 149
2022-03-09 14:38:46,137 Creating docker network codalab_worker_network_int /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker.py 146
2022-03-09 14:38:46,196 Created docker network codalab_worker_network_int /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker.py 149
2022-03-09 14:38:46,196 Worker started! /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/main.py 337
2022-03-09 14:38:46,244 Starting image manager /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/image_manager.py 52
2022-03-09 14:38:46,244 Starting local dependency manager /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/dependency_manager.py 173
2022-03-09 14:38:51,034 Connected! Successful check in! /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker.py 434
2022-03-09 14:38:51,175 Downloading Docker image jxqi/hello_docker:latest /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/docker_image_manager.py 136
2022-03-09 14:38:51,176 Looking for auth config /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 41
2022-03-09 14:38:51,176 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:51,176 Looking for auth entry for 'docker.io' /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 242
2022-03-09 14:38:51,177 Found 'https://index.docker.io/v1/' /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 250
2022-03-09 14:38:51,177 Found auth config /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/auth.py 54
2022-03-09 14:38:51,468 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:51,701 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:51,926 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:52,182 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:52,431 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:52,725 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:53,002 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:53,238 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:53,454 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:53,708 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:53,958 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:54,218 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:54,500 bundle is not ready yet. uuid: 0xaf2ce7945bbb4893ae7dc142ffe386c4. status message: Pulling docker image jxqi/hello_docker:latest Download starting /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 302
2022-03-09 14:38:54,711 Download for Docker image jxqi/hello_docker:latest complete /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/docker_image_manager.py 150
2022-03-09 14:38:54,776 translate_pattern: '/home/jxqi/Study/codalab/spider/codalab-worker-scratch/runs/0xaf2ce7945bbb4893ae7dc142ffe386c4' -> '/home/jxqi/Study/codalab/spider/codalab\\-worker\\-scratch/runs/0xaf2ce7945bbb4893ae7dc142ffe386c4' /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/apache_beam/io/filesystem.py 681
2022-03-09 14:38:55,907 Cannot start container: Unable to start Docker container: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown") /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 429
2022-03-09 14:38:56,243 Traceback (most recent call last):
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.39/containers/f9835a24ae4025f9631ced983d4ac4ba3a628688b85fbf9f6bc0d89772e36dc8/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/docker_utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/docker_utils.py", line 197, in start_bundle_container
    container = client.containers.run(
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/models/containers.py", line 816, in run
    container.start()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/models/containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/api/container.py", line 1108, in start
    self._raise_for_status(res)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py", line 403, in _transition_from_PREPARING
    container = docker_utils.start_bundle_container(
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/docker_utils.py", line 63, in wrapper
    check_for_user_error(e)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/docker_utils.py", line 56, in check_for_user_error
    raise DockerException(error_message)
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown")
 /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py 430
Traceback (most recent call last):
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.39/containers/f9835a24ae4025f9631ced983d4ac4ba3a628688b85fbf9f6bc0d89772e36dc8/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/docker_utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/docker_utils.py", line 197, in start_bundle_container
    container = client.containers.run(
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/models/containers.py", line 816, in run
    container.start()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/models/containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/api/container.py", line 1108, in start
    self._raise_for_status(res)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker.py", line 283, in start
    self.process_runs()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker.py", line 485, in process_runs
    self.runs[uuid] = self.run_state_manager.transition(prev_state)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker_run_state.py", line 403, in _transition_from_PREPARING
    container = docker_utils.start_bundle_container(
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/docker_utils.py", line 63, in wrapper
    check_for_user_error(e)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/docker_utils.py", line 56, in check_for_user_error
    raise DockerException(error_message)
codalab.worker.docker_utils.DockerException: Unable to start Docker container: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown")
2022-03-09 14:38:56,358 Sleeping for 1 hour due to exception...please help me! /home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/worker.py 303
```
but I just follow the CodaLab Worksheets Documentation in https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker
and I run 
```
cl run date
```
It can get the date result successfully.

Thank you again.

**Comment by epicfaace** [comment]
Is the Docker daemon running on your computer?

--
Ashwin Ramaswami

**Comment by JiexingQi** [comment]
@epicfaace Yes，the docker is daemon is running：
```
(base) jxqi@main-12:~$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 19
  Running: 2
  Paused: 0
  Stopped: 17
 Images: 33
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-91-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 502.6GiB
 Name: main-12
 ID: CE27:PPOB:QT2U:R7XO:KEFY:5AGG:A5XJ:3HLV:DDWS:C275:SEE7:VACX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: jxqi
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by JiexingQi** [comment]
Can anyone help me? I still faced this error and can not use docker in codalab?

**Comment by epicfaace** [comment]
> Thank you for your reply, @epicfaace , I just want to run a docker on codalab, the command are
> 
> ```
> CodaLab> cl run --request-docker-image jxqi/hello_docker "docker ps"
> 0x7eb7c81db0cd4ffaafd52cae0441a42b
> ```

@JiexingQi Why are you trying to run docker from within codalab? I don't think that's suupported.

**Comment by JiexingQi** [comment]
@epicfaace ,thanks a lot for your reply, what I actually want to do is that run my code in my docker env for this competation in https://worksheets.codalab.org/worksheets/0x82150f426cb94c17b861ef4162817399/. And my model need a very large memory for GPU and I want to run it in my own server. So I just try to learn how to run my code in docker env and make it run in my own server. By the way, could you tell me how to specify a run in my own server rather in other remote.(I have use 
```
cl-worker --verbose
```
to start two workers in my server)

Thanks a lot @epicfaace

**Comment by epicfaace** [comment]
In that case, you can still run your own worker, but you shouldn't run docker commands directly. Rather, you can just run your script that runs the model, for example:

```
cl run --request-docker-image jxqi/hello_docker "run-model.sh"
```

You should also reach out to the competition organizers if you have more specific questions!

**Comment by JiexingQi** [comment]
@epicfaace Thank you, I just run 
```
cl run --request-docker-image jxqi/hello_docker "pwd"
```
in my own server,
however, in the web page, this bundle still run in a remote server rather than my own server, can I specify this run executed in my own server? Thank you.

**Comment by epicfaace** [comment]
@JiexingQi you need to use tags, please see https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker and the "Controlling where runs happen with tags." section.

**Comment by JiexingQi** [comment]
Well, @epicfaace ,Thank you.

**Comment by epicfaace** [comment]
Hmm, not sure. Is your user root or is it part of the docker group?

--
Ashwin Ramaswami
