### ISSUE TITLE
AttributeError: 'Metadata' object has no attribute 'created'

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2792]
**Describe the bug**
Seeing the following stacktrace in bundle manager in our `dev` instance:

```
AttributeError: 'Metadata' object has no attribute 'created'
Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 80, in run
    self._run_iteration()
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 101, in _run_iteration
    self._fail_unresponsive_bundles()
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 716, in _fail_unresponsive_bundles
    if now - bundle.metadata.created > BUNDLE_TIMEOUT_DAYS * SECONDS_PER_DAY:
AttributeError: 'Metadata' object has no attribute 'created'
Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 80, in run
    self._run_iteration()
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 101, in _run_iteration
    self._fail_unresponsive_bundles()
  File "/opt/codalab-worksheets/codalab/server/bundle_manager.py", line 716, in _fail_unresponsive_bundles
    if now - bundle.metadata.created > BUNDLE_TIMEOUT_DAYS * SECONDS_PER_DAY:
```

**Codalab Information**
 - *Codalab CLI Version (if on CLI)*: v0.5.22

**To Reproduce**
I can't reproduce this issue locally. So far, I've only seen it happen in `dev`.

**Expected behavior**
There shouldn't be any errors.

**Comment by yiboliu** [comment]
Reached out to Candice, who said it should have already been resolved. Will need to double check this later.

**Comment by yiboliu** [comment]
Not occurring anymore in dev server's bundle manager
