### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2993]
**Describe the bug**
Request `POST /account/login` failed with the following stack trace:

```
POST /account/login

Query params:

Form params:
username='webmaster'
password='<censored>'

JSON body:
<none>

Local variables:
params={'error': 'Login/password did not match.', 'next': None}
redirect_uri=None

Traceback (most recent call last):
File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 106, in wrapper
return callback(*args, **kwargs)
File "/usr/local/bin/bottle.py", line 1748, in wrapper
rv = callback(*a, **ka)
File "/opt/codalab-worksheets/codalab/server/json_api_plugin.py", line 18, in wrapper
result = callback(*args, **kwargs)
File "/opt/codalab-worksheets/codalab/rest/account.py", line 46, in do_login
error_uri, {"error": "Login/password did not match.", "next": success_uri}
File "/opt/codalab-worksheets/codalab/lib/server_util.py", line 173, in redirect_with_query
return redirect(redirect_uri + '?' + urllib.parse.urlencode(params))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Codalab Information**
 - *Codalab CLI Version (if on CLI)*: 0.5.25

**Expected behavior**

We should fail gracefully.

**Comment by yiboliu** [comment]
Not happening anymore. My suggestion is to give a default value to the `redirect_uri` when it's None in the #3054 . Feel free to comment your thoughts.
