### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by fereshte-** [codalab/codalab-worksheets#300]
I got this error when I want to access my below worksheet.

https://codalab.stanford.edu/worksheets/0x9c26cd6b94a5431f8eada51dd711424f/

**Comment by kashizui** [comment]
Thanks @fereshte- 
For our debugging purposes:
```
Error on request by fereshte(42):

GET /api/worksheets/0x9c26cd6b94a5431f8eada51dd711424f/

Query params:
bundle_uuid='0x9a40cc5edef5490bb14c2194efdb43b1'
bundle_uuid='0xad40f62288f84f0383150328e366ec74'
bundle_uuid='0x90ff73a4bdd449ff88f09fddc6136887'
bundle_uuid='0x6433f3ce989b49759ccd6adf4f6d33cc'
bundle_uuid='0xe9f9847ed0fe4ed5b6e483066bb18829'
bundle_uuid='0x0f6c0bd24b274dafb040f0fd8abaeb3a'
_='1492936907051'

Form params:


JSON body:
<none>

Local variables:
description=u'run run-mkdir -- :bin,:lib,:amazon,:scripts'
item=({'owner_name': 'fereshte', 'args': 'run bin:0xdca523a9b1e44b55973018eda374141a lib:0xc6ffcc10b56640cf8b55d6c547a74ea9 amazon:0xc9e1f634da9d48c88c9dcbcd7137ecdc scripts:0xe0020f24f9c64b12a5a3ac962f4d7554 "mkdir writtenData && scripts/run -baseline n  -actionCost 50\xa0 -a 15 -f 1 -k 1 -b 1" --request-queue host=jagupard4', 'dependencies': [{'parent_path': '', 'child_uuid': '0x48e777e8fe244a8d962622b6b13cb033', 'parent_uuid': '0xdca523a9b1e44b55973018eda374141a', 'child_path': 'bin', 'parent_name': 'bin'}, {'parent_path': '', 'child_uuid': '0x48e777e8fe244a8d962622b6b13cb033', 'parent_uuid': '0xc6ffcc10b56640cf8b55d6c547a74ea9', 'child_path': 'lib', 'parent_name': 'lib'}, {'parent_path': '', 'child_uuid': '0x48e777e8fe244a8d962622b6b13cb033', 'parent_uuid': '0xc9e1f634da9d48c88c9dcbcd7137ecdc', 'child_path': 'amazon', 'parent_name': 'amazon'}, {'parent_path': '', 'child_uuid': '0x48e777e8fe244a8d962622b6b13cb033', 'parent_uuid': '0xe0020f24f9c64b12a5a3ac962f4d7554', 'chil
 d_path': 'scripts', 'parent_name': 'scripts'}], 'bundle_type': 'run', 'owner': 'fereshte(42)', 'data_hash': None, 'uuid': '0x48e777e8fe244a8d962622b6b13cb033', 'state': 'starting', 'command': 'mkdir writtenData && scripts/run -baseline n  -actionCost 50\xa0 -a 15 -f 1 -k 1 -b 1', 'owner_id': '42', 'metadata': {'allow_failed_dependencies': False, 'job_handle': u'1282544.scail.stanford.edu', 'description': u'', 'tags': [], 'request_memory': u'', 'request_network': False, 'request_docker_image': u'', 'actions': [], 'created': 1492937267, 'request_time': u'', 'request_queue': u'host=jagupard4', 'request_cpus': 0, 'request_disk': u'', 'request_priority': 0, 'request_gpus': 0, 'last_updated': 1492937274, 'name': u'run-mkdir'}}, None, u'', 'bundle')
lines=[u'[dataset Makefile]{0xb234a6178e8444dabeef5ce67107aae8}', u'[dataset amazon]{0xc9e1f634da9d48c88c9dcbcd7137ecdc}', u'[dataset lib]{0xc6ffcc10b56640cf8b55d6c547a74ea9}', u'[dataset scripts]{0xe0020f24f9c64b12a5a3ac962f4d7554}', u'', '% schema simple1', "% add uuid uuid '[0:8]'", '% add command', '% add k /result(...truncated...)iority': 0, 'request_gpus': 0, 'last_updated': 1492937274, 'name': u'run-mkdir'}}, None, u'', 'bundle')], 'tags': [], 'name': 'fereshte-PIP2', 'group_permissions': [{'permission': 1L, 'group_name': 'public', 'id': 437L, 'group_uuid': '0xcbda9a5d09894262a0f04289f90d45f1'}], 'permission': 2, 'owner_id': '42'}
subworksheet_info=None
value_obj=u''
bundle_info={'owner_name': 'fereshte', 'args': 'run bin:0xdca523a9b1e44b55973018eda374141a lib:0xc6ffcc10b56640cf8b55d6c547a74ea9 amazon:0xc9e1f634da9d48c88c9dcbcd7137ecdc scripts:0xe0020f24f9c64b12a5a3ac962f4d7554 "mkdir writtenData && scripts/run -baseline n  -actionCost 50\xa0 -a 15 -f 1 -k 1 -b 1" --request-queue host=jagupard4', 'dependencies': [{'parent_path': '', 'child_uuid': '0x48e777e8fe244a8d962622b6b13cb033', 'parent_uuid': '0xdca523a9b1e44b55973018eda374141a', 'child_path': 'bin', 'parent_name': 'bin'}, {'parent_path': '', 'child_uuid': '0x48e777e8fe244a8d962622b6b13cb033', 'parent_uuid': '0xc6ffcc10b56640cf8b55d6c547a74ea9', 'child_path': 'lib', 'parent_name': 'lib'}, {'parent_path': '', 'child_uuid': '0x48e777e8fe244a8d962622b6b13cb033', 'parent_uuid': '0xc9e1f634da9d48c88c9dcbcd7137ecdc', 'child_path': 'amazon', 'parent_name': 'amazon'}, {'parent_path': '', 'child_uuid': '0x48e777e8fe244a8d962622b6b13cb033', 'parent_uuid': '0xe0020f24f9c64b12a5a3ac962f4d7554',
  'child_path': 'scripts', 'parent_name': 'scripts'}], 'bundle_type': 'run', 'owner': 'fereshte(42)', 'data_hash': None, 'uuid': '0x48e777e8fe244a8d962622b6b13cb033', 'state': 'starting', 'command': 'mkdir writtenData && scripts/run -baseline n  -actionCost 50\xa0 -a 15 -f 1 -k 1 -b 1', 'owner_id': '42', 'metadata': {'allow_failed_dependencies': False, 'job_handle': u'1282544.scail.stanford.edu', 'description': u'', 'tags': [], 'request_memory': u'', 'request_network': False, 'request_docker_image': u'', 'actions': [], 'created': 1492937267, 'request_time': u'', 'request_queue': u'host=jagupard4', 'request_cpus': 0, 'request_disk': u'', 'request_priority': 0, 'request_gpus': 0, 'last_updated': 1492937274, 'name': u'run-mkdir'}}
metadata={'allow_failed_dependencies': False, 'job_handle': u'1282544.scail.stanford.edu', 'description': u'', 'tags': [], 'request_memory': u'', 'request_network': False, 'request_docker_image': u'', 'actions': [], 'created': 1492937267, 'request_time': u'', 'request_queue': u'host=jagupard4', 'request_cpus': 0, 'request_disk': u'', 'request_priority': 0, 'request_gpus': 0, 'last_updated': 1492937274, 'name': u'run-mkdir'}

Traceback (most recent call last):
  File "/u/nlp/data/codalab/codalab-cli/codalab/server/rest_server.py", line 146, in wrapper
    return callback(*args, **kwargs)
  File "/u/nlp/data/codalab/codalab-cli/venv/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/u/nlp/data/codalab/codalab-cli/codalab/server/json_api_plugin.py", line 17, in wrapper
    result = callback(*args, **kwargs)
  File "/u/nlp/data/codalab/codalab-cli/codalab/rest/legacy.py", line 731, in get_worksheet_content
    return service.full_worksheet(uuid, bundle_uuids)
  File "/u/nlp/data/codalab/codalab-cli/codalab/rest/legacy.py", line 170, in full_worksheet
    worksheet_info['raw'] = worksheet_util.get_worksheet_lines(worksheet_info)
  File "/u/nlp/data/codalab/codalab-cli/codalab/lib/worksheet_util.py", line 147, in get_worksheet_lines
    if command: description += ' : ' + command
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 63: ordinal not in range(128)
```

**Comment by kashizui** [comment]
The command had a unicode character in it that was unsafely handled.
`mkdir writtenData && scripts/run -baseline n  -actionCost 50\xa0 -a 15 -f 1 -k 1 -b 1`

**Comment by kashizui** [comment]
For reference `\xa0` is a "non-breaking space in Latin1 (ISO 8859-1), also chr(160)"

**Comment by fereshte-** [comment]
Thanks,

I wrote all the commands in Word first I think that's why this happened. I
didn't mean to use special character!

Can you please kill/remove these bundles so I can work with fereshte-PIP
worksheet?

**Comment by kashizui** [comment]
Yup was just trying to do that. I manually removed the character and worksheet should be working now

**Comment by kashizui** [comment]
We should be handling unicode better

**Comment by fereshte-** [comment]
It's working now.

Thanks a lot for the fast response.

**Comment by kashizui** [comment]
dup of codalab/codalab-cli#502
