### ISSUE TITLE
Large bundles that can't fit in server memory cannot be downloaded by workers

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#3011]
**Describe the bug**

If a worker takes a dependency on a very large bundle (e.g. 3GB) that can't fit in the server's memory, the server is unable to transmit the dependency and thus the worker fails.

The issue is that in https://github.com/codalab/codalab-worksheets/commit/4cc81fc8142efef6b608d6677bec0e85565908b8#diff-2b2d1ef00e8805335562a7967af36158e9140f6c4a5039f3462517795e4d67f6R210-R218, some changes were made to the `gzip_file` function. Now, it does a `data = open_file(file_path).read()`, which attempts to read the entire file into memory---this isn't always going to work.

**To Reproduce**
Steps to reproduce the behavior :
1. Run a bundle on codalab.stanford.edu (host only has 4G memory) that depends on glove.840B.300d (3GB+ file)

**Expected behavior**
The worker downloads the file

**Server Log**
```
2020-11-03 23:19:02,245 Error on request by nfliu(0x9da95d34ca4d4b7a8b271859281d936c):

GET /bundles/0x58947c280ae341b9b270fcc2173dc951/contents/blob/

Query params:


Form params:


JSON body:
<none>

Local variables:
file_path='/juice/u/codalab/var/codalab/home/partitions/default/bundles/0x58947c280ae341b9b270fcc2173dc951'

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/worker/file_util.py", line 214, in gzip_file
    data = open_file(file_path).read()
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 106, in wrapper
    return callback(*args, **kwargs)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/opt/codalab-worksheets/codalab/server/json_api_plugin.py", line 18, in wrapper
    result = callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/server/authenticated_plugin.py", line 136, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/rest/bundles.py", line 664, in _fetch_bundle_contents_blob
    fileobj = local.download_manager.stream_file(target, gzipped_stream)
  File "/opt/codalab-worksheets/codalab/lib/download_manager.py", line 22, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/lib/download_manager.py", line 197, in stream_file
    return file_util.gzip_file(file_path)
  File "/opt/codalab-worksheets/codalab/worker/file_util.py", line 217, in gzip_file
    raise IOError(e)
OSError

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/worker/file_util.py", line 214, in gzip_file
    data = open_file(file_path).read()
MemoryError
```

**Comment by percyliang** [comment]
@epicfaace @teetone Do we have a stress test that could catch this?

**Comment by teetone** [comment]
@percyliang No, not at the moment. I created an issue for it: https://github.com/codalab/codalab-worksheets/issues/3013
