### ISSUE TITLE
Github Actions Stress Testing always fails

### ISSUE THREAD

**Issue by yuqijin** [codalab/codalab-worksheets#3057]
**Describe the bug**
Manual stress testing can pass while the GHA stress testing always fails when running the command of `cl upload small_file --tags=***-stress-test`. The error message is:
```
>> cl upload small_file --tags=***-stress-test
 (exit code test-cli exception, expected 0 BAD)
Traceback (most recent call last):
  File "/Users/runner/work/***-worksheets/***-worksheets/***/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/Users/runner/work/***-worksheets/***-worksheets/***/client/json_api_client.py", line 660, in upload_contents_blob
    progress_callback=progress_callback,
  File "/Users/runner/work/***-worksheets/***-worksheets/***/worker/rest_client.py", line 162, in _upload_with_chunked_encoding
    response = conn.getresponse()
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/http/client.py", line 1379, in getresponse
    response.begin()
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/runner/ho (...more...)
Traceback (most recent call last):
  File "tests/stress/stress_test.py", line 461, in <module>
    main()
  File "tests/stress/stress_test.py", line 339, in main
    runner.run()
  File "tests/stress/stress_test.py", line 125, in run
    self._test_many_bundle_uploads()
  File "tests/stress/stress_test.py", line 193, in _test_many_bundle_uploads
    self._run_bundle([self._cl, 'upload', file.name()])
  File "tests/stress/stress_test.py", line 293, in _run_bundle
    return run_command(args, expected_exit_code)
  File "/Users/runner/work/***-worksheets/***-worksheets/scripts/test_util.py", line 138, in run_command
    assert expected_exit_code == exitcode, 'Exit codes don\'t match'
AssertionError: Exit codes don't match
Error: Process completed with exit code 1.
```

It also might fail when running `cl wait`, an example run: https://github.com/codalab/codalab-worksheets/runs/1394336766

**Comment by nelson-liu** [comment]
I think this is related to #3058 . If I install codalab from master in a fresh virtualenv with python 3, and run `cl up <any file>`, it shows:

```
$ cl up monitor.py
/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.26.2 (/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nfliu/miniconda3/envs/cl_dev/bin/cl", line 33, in <module>
    sys.exit(load_entry_point('codalab', 'console_scripts', 'cl')())
  File "/home/nfliu/miniconda3/envs/cl_dev/bin/cl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nfliu/git/codalab-worksheets/codalab/bin/cl.py", line 3, in <module>
    from codalab.lib.bundle_cli import BundleCLI
  File "/home/nfliu/git/codalab-worksheets/codalab/lib/bundle_cli.py", line 38, in <module>
    import codalab.model.bundle_model as bundle_model
  File "/home/nfliu/git/codalab-worksheets/codalab/model/bundle_model.py", line 54, in <module>
    from codalab.rest.util import get_group_info
  File "/home/nfliu/git/codalab-worksheets/codalab/rest/util.py", line 11, in <module>
    from codalab.lib import bundle_util
  File "/home/nfliu/git/codalab-worksheets/codalab/lib/bundle_util.py", line 7, in <module>
    from codalab.client.json_api_client import JsonApiClient, JsonApiRelationship  # NOQA: F401
  File "/home/nfliu/git/codalab-worksheets/codalab/client/json_api_client.py", line 10, in <module>
    from codalab.worker.rest_client import RestClient, RestClientException
  File "/home/nfliu/git/codalab-worksheets/codalab/worker/rest_client.py", line 10, in <module>
    from .file_util import un_gzip_stream
  File "/home/nfliu/git/codalab-worksheets/codalab/worker/file_util.py", line 12, in <module>
    from apache_beam.io.filesystem import CompressionTypes
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/apache_beam/__init__.py", line 95, in <module>
    from apache_beam import coders
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/apache_beam/coders/__init__.py", line 19, in <module>
    from apache_beam.coders.coders import *
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/apache_beam/coders/coders.py", line 42, in <module>
    import google.protobuf.wrappers_pb2
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.26.2 (/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})
```

So, hopefully fixing those things should do the trick.

**Comment by yuqijin** [comment]
> I think this is related to #3058 . If I install codalab from master in a fresh virtualenv with python 3, and run `cl up <any file>`, it shows:
> 
> ```
> $ cl up monitor.py
> /home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
>   RequestsDependencyWarning)
> Traceback (most recent call last):
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 567, in _build_master
>     ws.require(__requires__)
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 884, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 775, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (urllib3 1.26.2 (/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/nfliu/miniconda3/envs/cl_dev/bin/cl", line 33, in <module>
>     sys.exit(load_entry_point('codalab', 'console_scripts', 'cl')())
>   File "/home/nfliu/miniconda3/envs/cl_dev/bin/cl", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
>     module = import_module(match.group('module'))
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/nfliu/git/codalab-worksheets/codalab/bin/cl.py", line 3, in <module>
>     from codalab.lib.bundle_cli import BundleCLI
>   File "/home/nfliu/git/codalab-worksheets/codalab/lib/bundle_cli.py", line 38, in <module>
>     import codalab.model.bundle_model as bundle_model
>   File "/home/nfliu/git/codalab-worksheets/codalab/model/bundle_model.py", line 54, in <module>
>     from codalab.rest.util import get_group_info
>   File "/home/nfliu/git/codalab-worksheets/codalab/rest/util.py", line 11, in <module>
>     from codalab.lib import bundle_util
>   File "/home/nfliu/git/codalab-worksheets/codalab/lib/bundle_util.py", line 7, in <module>
>     from codalab.client.json_api_client import JsonApiClient, JsonApiRelationship  # NOQA: F401
>   File "/home/nfliu/git/codalab-worksheets/codalab/client/json_api_client.py", line 10, in <module>
>     from codalab.worker.rest_client import RestClient, RestClientException
>   File "/home/nfliu/git/codalab-worksheets/codalab/worker/rest_client.py", line 10, in <module>
>     from .file_util import un_gzip_stream
>   File "/home/nfliu/git/codalab-worksheets/codalab/worker/file_util.py", line 12, in <module>
>     from apache_beam.io.filesystem import CompressionTypes
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/apache_beam/__init__.py", line 95, in <module>
>     from apache_beam import coders
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/apache_beam/coders/__init__.py", line 19, in <module>
>     from apache_beam.coders.coders import *
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/apache_beam/coders/coders.py", line 42, in <module>
>     import google.protobuf.wrappers_pb2
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/google/protobuf/__init__.py", line 37, in <module>
>     __import__('pkg_resources').declare_namespace(__name__)
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3238, in <module>
>     @_call_aside
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
>     f(*args, **kwargs)
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 569, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 775, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (urllib3 1.26.2 (/home/nfliu/miniconda3/envs/cl_dev/lib/python3.6/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})
> ```
> 
> So, hopefully fixing those things should do the trick.

Hi Nelson, but it seems like fixing the version conflict did not solve the problem. The Master branch now has downgraded the urllib, while the stress test still failed.

**Comment by nelson-liu** [comment]
seems like it's at least a different issue now, though...the stress test are pretty flaky on gha, especially when it comes to uploading the large dependency to the dev server.

**Comment by epicfaace** [comment]
> the stress test are pretty flaky on gha, especially when it comes to uploading the large dependency to the dev server.

Yeah, perhaps it would be good to reduce the size of that large dependency. When we initially made stress tests work on GHA, I intentionally reduced file sizes so that it wouldn't be flaky. I believe @teetone increased the size to ensure we test with large files that don't fit in memory; but perhaps it would be better to see if we can test that a different way instead (by changing `--request-memory` instead)

**Comment by nelson-liu** [comment]
> I believe @teetone increased the size to ensure we test with large files that don't fit in memory; but perhaps it would be better to see if we can test that a different way instead (by changing --request-memory instead)

The test uploads a bundle that can't fit in the _server_'s memory, so `--request-memory` doesn't seem like it'd do the trick here (since it's only worker-side)

**Comment by epicfaace** [comment]
Latest stress tests on GHA are working!
