### ISSUE TITLE
Version conflict of urllib3

### ISSUE THREAD

**Issue by yiboliu** [codalab/codalab-worksheets#3058]
**Describe the bug**
```Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/bin/cl", line 33, in <module>
    sys.exit(load_entry_point('***', 'console_scripts', 'cl')())
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/bin/cl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/runner/work/***-worksheets/***-worksheets/***/bin/cl.py", line 3, in <module>
    from ***.lib.bundle_cli import BundleCLI
  File "/Users/runner/work/***-worksheets/***-worksheets/***/lib/bundle_cli.py", line 38, in <module>
    import ***.model.bundle_model as bundle_model
  File "/Users/runner/work/***-worksheets/***-worksheets/***/model/bundle_model.py", line 54, in <module>
    from ***.rest.util import get_group_info
  File "/Users/runner/work/***-worksheets/***-worksheets/***/rest/util.py", line 11, in <module>
    from ***.lib import bundle_util
  File "/Users/runner/work/***-worksheets/***-worksheets/***/lib/bundle_util.py", line 7, in <module>
    from ***.client.json_api_client import JsonApiClient, JsonApiRelationship  # NOQA: F401
  File "/Users/runner/work/***-worksheets/***-worksheets/***/client/json_api_client.py", line 10, in <module>
    from ***.worker.rest_client import RestClient, RestClientException
  File "/Users/runner/work/***-worksheets/***-worksheets/***/worker/rest_client.py", line 10, in <module>
    from .file_util import un_gzip_stream
  File "/Users/runner/work/***-worksheets/***-worksheets/***/worker/file_util.py", line 12, in <module>
    from apache_beam.io.filesystem import CompressionTypes
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/apache_beam/__init__.py", line 95, in <module>
    from apache_beam import coders
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/apache_beam/coders/__init__.py", line 19, in <module>
    from apache_beam.coders.coders import *
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/apache_beam/coders/coders.py", line 42, in <module>
    import google.protobuf.wrappers_pb2
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.26.1 (/Users/runner/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})
```
**Codalab Information**
- *Your username*:
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
1. Go to stress test: https://github.com/codalab/codalab-worksheets/runs/1391206778?check_suite_focus=true
2. See error

**Expected behavior**
Should not have any version conficts

**Screenshots**

**Additional context**
Our plan is to downgrade it for now and add a pip check. Later on we may upgrade it.

**Comment by epicfaace** [comment]
Fixed by #3059.
