### ISSUE TITLE
[USER ISSUE] Trying to upload large folder fails.

### ISSUE THREAD

**Issue by henrikmarklund** [codalab/codalab-worksheets#3082]
**Describe the bug**
I'm trying to upload a folder of size  86G. I run cl upload -n 'name' /path/to/data/. This fails after 64G with  json_api_client.JsonApiException.

**Codalab Information**
- *Your username*: henrikmarklund
- *UUID of worksheet where problem occurred*: 0xb44731cc8e8a4265a20146c3887b6b90
- *UUID of problem bundle (please don't delete)*: 0x877ce404aa6a43adac7a95a4a8ee8c51
- *Error message received from Codalab (if applicable)*:
cl upload -n 'iwildcam' /iris/u/marklund/data/iwildcam/data
Preparing upload archive...
Uploading data.tar.gz (0x877ce404aa6a43adac7a95a4a8ee8c51) to https://worksheets.codalab.org
Sent 64189.78MiB [7.88MiB/sec]
Traceback (most recent call last):
  File "/iris/u/marklund/miniconda3/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/iris/u/marklund/miniconda3/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 660, in upload_contents_blob
    progress_callback=progress_callback,
  File "/iris/u/marklund/miniconda3/lib/python3.7/site-packages/codalab/worker/rest_client.py", line 153, in _upload_with_chunked_encoding
    conn.send(b'%X\r\n%s\r\n' % (len(to_send), to_send))
  File "/iris/u/marklund/miniconda3/lib/python3.7/http/client.py", line 987, in send  
    self.sock.sendall(data)
  File "/iris/u/marklund/miniconda3/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/iris/u/marklund/miniconda3/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

Traceback (most recent call last):
  File "/iris/u/marklund/miniconda3/bin/cl", line 8, in <module>
    sys.exit(main())
  File "/iris/u/marklund/miniconda3/lib/python3.7/site-packages/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/iris/u/marklund/miniconda3/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 944, in do_command
    structured_result = command_fn()
  File "/iris/u/marklund/miniconda3/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 938, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/iris/u/marklund/miniconda3/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 1383, in do_upload_command
    progress_callback=progress.update,
  File "/iris/u/marklund/miniconda3/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 52, in wrapper
    sys.exc_info()[2],
  File "/afs/cs.stanford.edu/u/marklund/.local/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/iris/u/marklund/miniconda3/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/iris/u/marklund/miniconda3/lib/python3.7/site-packages/codalab/client/json_api_client.py", line 660, in upload_contents_blob
    progress_callback=progress_callback,
  File "/iris/u/marklund/miniconda3/lib/python3.7/site-packages/codalab/worker/rest_client.py", line 153, in _upload_with_chunked_encoding
    conn.send(b'%X\r\n%s\r\n' % (len(to_send), to_send))
  File "/iris/u/marklund/miniconda3/lib/python3.7/http/client.py", line 987, in send  
    self.sock.sendall(data)
  File "/iris/u/marklund/miniconda3/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/iris/u/marklund/miniconda3/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
codalab.client.json_api_client.JsonApiException: Unable to upload contents of bundle 0x877ce404aa6a43adac7a95a4a8ee8c51: [Errno 32] Broken pipe

 - *OS (if on CLI)*: Linux iris-ws-8.stanford.edu 4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Thanks for the help. I would appreciate some guidance on how to debug this further.

**Comment by wayneczw** [comment]
I'm facing a similar problem, except that my upload always failed after sending about 100~120MiB of data. 

I'm using CodaLab CLI version 0.5.30, Python3.6.12.

**Comment by wayneczw** [comment]
> I'm facing a similar problem, except that my upload always failed after sending about 100~120MiB of data.
> 
> I'm using CodaLab CLI version 0.5.30, Python3.6.12.

I have found a workaround. Add the -z flag when executing the cl upload command. The JsonApiException will still be raised, but the data will be successfully uploaded to codalab. This being said, though a workaround exists, it is still a bug that needs to be fixed.

**Comment by epicfaace** [comment]
I'm seeing these errors in the logs, which might have to do with this:

[/tmp/tmper0vc6a4]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tmper0vc6a4 or
        /tmp/tmper0vc6a4.zip, and cannot find /tmp/tmper0vc6a4.ZIP, period.

Bundles with the error mentioned in this issue:
https://worksheets.codalab.org/bundles/0x877ce404aa6a43adac7a95a4a8ee8c51

**Comment by epicfaace** [comment]
Also get this error when trying to upload from a URL:

```
    structured_result = command_fn()  File "/home/azureuser/codalab-worksheets/codalab/lib/bundle_cli.py", line 938, in <lambda>
    command_fn = lambda: args.function(self, args)  File "/home/azureuser/codalab-worksheets/codalab/lib/bundle_cli.py", line 1325, in do_upload_command
    'finalize_on_success': True,  File "/home/azureuser/codalab-worksheets/codalab/client/json_api_client.py", line 52, in wrapper
    sys.exc_info()[2],  File "/home/azureuser/venv/lib/python3.6/site-packages/six.py", line 702, in reraise    raise value.with_traceback(tb)
  File "/home/azureuser/codalab-worksheets/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/home/azureuser/codalab-worksheets/codalab/client/json_api_client.py", line 653, in upload_contents_blob
    self._make_request(method='PUT', path=request_path, query_params=params)
  File "/home/azureuser/codalab-worksheets/codalab/worker/rest_client.py", line 103, in _make_request
    with closing(urllib.request.urlopen(request, timeout=timeout_seconds)) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1392, in https_open    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1379, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
codalab.client.json_api_client.JsonApiException: Unable to upload contents of bundle 0xe25830b2c2a54f6dafad214b3d0a653a: The read operation timed out
```

**Comment by epicfaace** [comment]
The limit appears to be 64 GB, after which files don't work

**Comment by epicfaace** [comment]
Error I'm getting (after ~20 GB):

```
(venv) epicfaace@ashwins-mbp codalab-worksheets % cl upload ~/codalab/largefile
Preparing upload archive...
Uploading largefile (0x4577dcc3d8a94f8db09a0d5348f664f4) to http://localhost
Sent 22567.06MiB / 102400.00MiB (22.0%) [4.70MiB/sec]           		
Traceback (most recent call last):
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/client/json_api_client.py", line 660, in upload_contents_blob
    progress_callback=progress_callback,
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/worker/rest_client.py", line 153, in _upload_with_chunked_encoding
    conn.send(b'%X\r\n%s\r\n' % (len(to_send), to_send))
  File "/Users/epicfaace/.pyenv/versions/3.6.10/lib/python3.6/http/client.py", line 996, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/epicfaace/codalab/codalab-worksheets/venv/bin/cl", line 33, in <module>
    sys.exit(load_entry_point('codalab', 'console_scripts', 'cl')())
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/bundle_cli.py", line 946, in do_command
    structured_result = command_fn()
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/bundle_cli.py", line 940, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/bundle_cli.py", line 1392, in do_upload_command
    progress_callback=progress.update,
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/client/json_api_client.py", line 52, in wrapper
    sys.exc_info()[2],
  File "/Users/epicfaace/codalab/codalab-worksheets/venv/lib/python3.6/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/client/json_api_client.py", line 660, in upload_contents_blob
    progress_callback=progress_callback,
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/worker/rest_client.py", line 153, in _upload_with_chunked_encoding
    conn.send(b'%X\r\n%s\r\n' % (len(to_send), to_send))
  File "/Users/epicfaace/.pyenv/versions/3.6.10/lib/python3.6/http/client.py", line 996, in send
    self.sock.sendall(data)
codalab.client.json_api_client.JsonApiException: Unable to upload contents of bundle 0x4577dcc3d8a94f8db09a0d5348f664f4: [Errno 32] Broken pipe
```

**Comment by epicfaace** [comment]
Ah, found the issue in the nginx logs:

```
2020/12/20 20:42:17 [error] 6#6: *118 client intended to send too large chunked body: 67108000000+1000000 bytes while sending request to upstream, client: 172.28.0.1, server: localhost, request: "PUT /rest/bundles/0x74465c242498471ea8ed6a62af0e7622/contents/blob/?filename=largefile&unpack=0&simplify=0&state_on_success=ready&finalize_on_success=1&finalize_on_failure=1 HTTP/1.1", upstream: "http://172.28.0.3:2900/rest/bundles/0x74465c242498471ea8ed6a62af0e7622/contents/blob/?filename=largefile&unpack=0&simplify=0&state_on_success=ready&finalize_on_success=1&finalize_on_failure=1", host: "localhost"
```
