### ISSUE TITLE
[USER ISSUE] cl-worker-manager fails with regex error

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3091]
nlp-cl-worker-manager fails with the following error:

```
2020-11-26 21:40:01,204 0 staged bundles (0 removed since last time), 1 worker jobs (min=0, max=5) (1 active, 0 pending)
2020-11-26 21:40:06,529 Staged bundles [state=staged .mine]: (none)
2020-11-26 21:40:06,532 Caught an exception when executing command scontrol show jobid -d 1920527 --oneliner: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/juice/scr/nfliu/public/cl_public_main/bin/cl-worker-manager", line 8, in <module>
    sys.exit(main())
  File "/juice/scr/nfliu/public/cl_public_main/lib/python3.7/site-packages/codalab/worker_manager/main.py", line 128, in main
    manager.run_loop()
  File "/juice/scr/nfliu/public/cl_public_main/lib/python3.7/site-packages/codalab/worker_manager/worker_manager.py", line 148, in run_loop
    self.run_one_iteration()
  File "/juice/scr/nfliu/public/cl_public_main/lib/python3.7/site-packages/codalab/worker_manager/worker_manager.py", line 209, in run_one_iteration
    worker_jobs = self.get_worker_jobs()
  File "/juice/scr/nfliu/public/cl_public_main/lib/python3.7/site-packages/codalab/worker_manager/slurm_batch_worker_manager.py", line 150, in get_worker_jobs
    job_state = re.search(r'JobState=(.*)\sReason', job_acct).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by nelson-liu** [comment]
i fixed this in https://github.com/codalab/codalab-worksheets/pull/3083
