### ISSUE TITLE
create-root-user.py can be called before migrations are complete

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3263]
I'm trying to run `codalab_service.py start` with this commit (https://github.com/codalab/codalab-worksheets/pull/3261/commits/d982ef912ea8b597a8ab614790fce0debe6e93b7), but I get the following error:

```
process: wait-for-it.sh: waiting 600 seconds for mysql:3306
process: wait-for-it.sh: mysql:3306 is available after 0 seconds
process: Traceback (most recent call last):
process:   File "scripts/create-root-user.py", line 27, in <module>
process:     if model.get_user(user_id=user_id, check_active=False):
process:   File "/opt/codalab-worksheets/codalab/model/bundle_model.py", line 2178, in get_user
process:     user_ids=user_ids, usernames=usernames, check_active=check_active, limit=1
process:   File "/opt/codalab-worksheets/codalab/model/bundle_model.py", line 2342, in get_users
process:     results = [User(row) for row in rows]
process:   File "/opt/codalab-worksheets/codalab/model/bundle_model.py", line 2342, in <listcomp>
process:     results = [User(row) for row in rows]
process:   File "/opt/codalab-worksheets/codalab/model/orm_object.py", line 44, in __init__
process:     self.update_in_memory(dict(row), strict=strict)
process:   File "/opt/codalab-worksheets/codalab/model/orm_object.py", line 58, in update_in_memory
process:     precondition(key in self.COLUMNS or key == 'id', message)
process:   File "/opt/codalab-worksheets/codalab/common.py", line 97, in precondition
process:     raise PreconditionViolation(message)
process: codalab.common.PreconditionViolation: Row {'id': 1, 'user_id': '0', 'user_name': 'codalab', 'email': '', 'notifications': 2, 'last_login': datetime.datetime(2021, 1, 27, 20, 26, 55), 'is_active': True, 'first_name': '', 'last_name': '', 'date_joined': datetime.datetime(2020, 9, 9, 22, 38, 6), 'has_access': True, 'is_verified': True, 'is_superuser': False, 'password': 'pbkdf2_sha256$30000$YQJeLqaf9s1u$EZP4GmK2DGXHMY4QCFkD3reFA7n+gIZz92WgO9NEU2M=', 'affiliation': '', 'url': None, 'time_quota': 3153600000.0, 'parallel_run_quota': 100, 'time_used': 57023.8, 'disk_quota': 107374000000.0, 'disk_used': 106543000000.0, 'avatar_id': None} has extra column: avatar_id
Traceback (most recent call last):
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab_service.py", line 834, in <module>
    main()
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab_service.py", line 106, in main
    service_manager.execute()
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab_service.py", line 586, in execute
    self.start_services()
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab_service.py", line 772, in start_services
    self.run_service_cmd(
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab_service.py", line 702, in run_service_cmd
    self._run_compose_cmd(
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab_service.py", line 685, in _run_compose_cmd
    raise Exception('Command exited with code {}'.format(popen.returncode))
Exception: Command exited with code 1
```

It appears that the alembic migration is not happening properly / at the right time, as the `avatar_id` migration should have been applied before `create-root-user.py` was called.

**Comment by epicfaace** [comment]
I'm not seeing this issue anymore
