### ISSUE TITLE
Consider removing "cl mount"

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3311]
Does anyone use "cl mount" at all? When I try using "cl mount", I get an error:

```
(venv) epicfaace@ashwins-mbp codalab-worksheets % cl mount 0x0c3ec361b38d412e9d07f3ff10744309 --mountpoint aa
BundleFUSE mounting bundle 0x0c3ec361b38d412e9d07f3ff10744309 on /Users/epicfaace/codalab/codalab-worksheets/aa
BundleFUSE will run and maintain the mounted filesystem in the foreground. CTRL-C to cancel.
Traceback (most recent call last):
  File "/Users/epicfaace/codalab/codalab-worksheets/venv/bin/cl", line 33, in <module>
    sys.exit(load_entry_point('codalab', 'console_scripts', 'cl')())
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/bundle_cli.py", line 952, in do_command
    structured_result = command_fn()
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/bundle_cli.py", line 946, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/bundle_cli.py", line 2436, in do_mount_command
    bundle_fuse.bundle_mount(client, mountpoint, target.bundle_uuid, args.verbose)
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/bundle_fuse.py", line 296, in bundle_mount
    FUSE(BundleFuse(client, bundle_uuid, verbose), mountpoint, nothreads=True, foreground=True)
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/bundle_fuse.py", line 168, in __init__
    info = self._get_info('/')
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/bundle_fuse.py", line 125, in func
    kw.sort()
AttributeError: 'dict_items' object has no attribute 'sort'
```

We also don't have any tests for it, so if it's broken and no one is using it, it may be good to just remove it.

**Comment by percyliang** [comment]
I'm not sure exactly who uses it, but `cl mount` has some pretty nice use cases - you're running a job and want to view the tensorboard output.  It's not very performant though.
