### ISSUE TITLE
Don't allow creation of bundles with missing dependencies

### ISSUE THREAD

**Issue by klopyrev** [codalab/codalab-worksheets#338]
The run command should fail if a dependency is missing. Currently, if you create such a bundle when you refresh the worksheet you get an error in the worksheets Django server:

Traceback (most recent call last):
  File "/Users/klopyrev/Dropbox/Codalab/codalab-cli/codalab/lib/worksheet_util.py", line 917, in interpret_items
    flush_bundles()
  File "/Users/klopyrev/Dropbox/Codalab/codalab-cli/codalab/lib/worksheet_util.py", line 759, in flush_bundles
    for (name, genpath, post) in schema
  File "/Users/klopyrev/Dropbox/Codalab/codalab-cli/codalab/lib/worksheet_util.py", line 759, in <dictcomp>
    for (name, genpath, post) in schema
  File "/Users/klopyrev/Dropbox/Codalab/codalab-cli/codalab/lib/worksheet_util.py", line 397, in interpret_genpath
    key, value = friendly_render_dep(dep)
  File "/Users/klopyrev/Dropbox/Codalab/codalab-cli/codalab/lib/worksheet_util.py", line 383, in friendly_render_dep
    dep['parent_uuid'][0:4] + '}'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by kashizui** [comment]
Fixed by BundleManager
