### ISSUE TITLE
cl wcp failing on copy from local to test env

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab-worksheets#34]
It is failing on a foreign key constraint. This might because the bundle exists already on test env. 

```
Traceback (most recent call last):
  File "/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 67, in <module>
    run_cli()
  File "/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 58, in run_cli
    cli.do_command(sys.argv[1:])
  File "/codalab-cli/codalab/lib/bundle_cli.py", line 342, in do_command
    command_fn(remaining_args, parser)
  File "/codalab-cli/codalab/lib/bundle_cli.py", line 1317, in do_wcp_command
    self.copy_bundle(source_client, source_bundle_info['uuid'], dest_client, dest_worksheet_uuid)
  File "/codalab-cli/codalab/lib/bundle_cli.py", line 558, in copy_bundle
    print dest_client.upload_bundle(source_path, info, dest_worksheet_uuid, False)
  File "/codalab-cli/codalab/client/remote_bundle_client.py", line 177, in upload_bundle
    result = self.upload_bundle_zip(remote_file_uuid, info, worksheet_uuid, follow_symlinks)
  File "/codalab-cli/codalab/client/remote_bundle_client.py", line 137, in inner
    return getattr(self.proxy, command)(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<class 'sqlalchemy.exc.IntegrityError'>:(IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`bundlesdb`.`bundle_dependency`, CONSTRAINT `bundle_dependency_ibfk_2` FOREIGN KEY (`parent_uuid`) REFERENCES `bundle` (`uuid`))') 'INSERT INTO bundle_dependency (child_uuid, child_path, parent_uuid, parent_path) VALUES (%s, %s, %s, %s), (%s, %s, %s, %s)' ('0xf150a31a891e4173a4cfc90638c143e7', 'input', '0x89e1235ca35e4e07a7dfaa33626058f7', '', '0xf150a31a891e4173a4cfc90638c143e7', 'sort.py', '0xbe37d8b9fac845a4a26abc73271d8177', '')">
```

**Comment by percyliang** [comment]
Which command did you run / which worksheet were you trying to copy?
Bundle existing on target worksheet is not a problem.

**Comment by percyliang** [comment]
Suppose bundle A depends on bundle B.
Problem was when you're copying A onto a bundle server where B doesn't exist, A points to an invalid uuid.  But that constraint is now relaxed, so the exception should no longer happen.
