### ISSUE TITLE
KeyError: frozen for existing bundles

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3410]
After pulling the latest from master and running a worker locally, I'm getting the following error:

```
2021-04-17 23:27:47,478 Worker started! /opt/codalab/worker/main.py 295
Traceback (most recent call last):
  File "/usr/local/bin/cl-worker", line 33, in <module>
    sys.exit(load_entry_point('codalab', 'console_scripts', 'cl-worker')())
  File "/opt/codalab/worker/main.py", line 298, in main
    worker.start()
  File "/opt/codalab/worker/worker.py", line 263, in start
    self.load_state()
  File "/opt/codalab/worker/worker.py", line 207, in load_state
    bundle=BundleInfo.from_dict(run_state.bundle),
  File "/opt/codalab/worker/bundle_state.py", line 126, in from_dict
    frozen=dct["frozen"],
KeyError: 'frozen'
```

**Comment by epicfaace** [comment]
@nelson-liu this seems to be happening due to the frozen bundles change, because existing bundles don't have the `frozen` keyword defined. I guess the fix to this would be just to run `dct.get("frozen")` instead -- will make a PR.
