### ISSUE TITLE
Worksheet content disappears after adding unicode characters

### ISSUE THREAD

**Issue by ppasupat** [codalab/codalab-worksheets#35]
To reproduce:
1. Create a new worksheet and add some content.
   
   ```
   > cl new bug-sandbox
   > cl work bug-sandbox
   > cl wedit
   # (Add some content and then save)
   > cl print
   ### Worksheet: http://localhost:12800::bug-sandbox(0x...)
   ### Owner: ...
   ### Permissions: ...
   Parent:
   [Worksheet ...]
   This is an example sentence.
   ```
2. Edit the worksheet, add a Unicode character, and then save.
   
   ```
   > cl wedit
   # (Add ♥ and then save)
   ```
3. The following error will appear, and the worksheet will be reset to the placeholder comments. All other contents are wiped out.
   
   ```
   Traceback (most recent call last):
     File "/home/ppasupat/.local/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 67, in <module>
       run_cli()
     File "/home/ppasupat/.local/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 58, in run_cli
       cli.do_command(sys.argv[1:])
     File "/home/ppasupat/.local/codalab-cli/codalab/lib/bundle_cli.py", line 337, in do_command
       command_fn(remaining_args, parser)
     File "/home/ppasupat/.local/codalab-cli/codalab/lib/bundle_cli.py", line 1155, in do_wedit_command
       client.update_worksheet(worksheet_info, new_items)
     File "/home/ppasupat/.local/codalab-cli/codalab/client/remote_bundle_client.py", line 136, in inner
       return getattr(self.proxy, command)(*args, **kwargs)
     File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
       return self.__send(self.__name, args)
     File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
       verbose=self.__verbose
     File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
       return self.single_request(host, handler, request_body, verbose)
     File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
       return self.parse_response(response)
     File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
       return u.close()
     File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
       raise Fault(**self._stack[0])
   xmlrpclib.Fault: <Fault 1: "<type 'exceptions.UnicodeEncodeError'>:'latin-1' codec can't encode character u'\\u2665' in position 0: ordinal not in range(256)">
   ```

**Comment by percyliang** [comment]
Fixed by #57
