### ISSUE TITLE
[USER ISSUE] HTTP Error 504: Gateway Time-out while uploading large dataset to prod

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3540]
Traceback:

```
Traceback (most recent call last):
  File "/Users/tonyhlee/stanford/research/wilds/code/wilds/venv/bin/cl", line 11, in <module>
    sys.exit(main())
  File "/Users/tonyhlee/stanford/research/wilds/code/wilds/venv/lib/python3.6/site-packages/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/Users/tonyhlee/stanford/research/wilds/code/wilds/venv/lib/python3.6/site-packages/codalab/lib/bundle_cli.py", line 952, in do_command
    structured_result = command_fn()
  File "/Users/tonyhlee/stanford/research/wilds/code/wilds/venv/lib/python3.6/site-packages/codalab/lib/bundle_cli.py", line 946, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/Users/tonyhlee/stanford/research/wilds/code/wilds/venv/lib/python3.6/site-packages/codalab/lib/bundle_cli.py", line 1410, in do_upload_command
    progress_callback=progress.update,
  File "/Users/tonyhlee/stanford/research/wilds/code/wilds/venv/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 38, in wrapper
    sys.exc_info()[2],
  File "/Users/tonyhlee/stanford/research/wilds/code/wilds/venv/lib/python3.6/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/Users/tonyhlee/stanford/research/wilds/code/wilds/venv/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/Users/tonyhlee/stanford/research/wilds/code/wilds/venv/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 660, in upload_contents_blob
    progress_callback=progress_callback,
  File "/Users/tonyhlee/stanford/research/wilds/code/wilds/venv/lib/python3.6/site-packages/codalab/worker/rest_client.py", line 188, in _upload_with_chunked_encoding
    StringIO(response.read().decode()),
codalab.client.json_api_client.JsonApiException: Unable to upload contents of bundle 0x5332717932f047f4b42a937339af0539: Gateway Timeout - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.12.0</center>
</body>
</html>
```

**Comment by teetone** [comment]
Originally, I thought the bundle was stuck in an `uploading` state after I hit this error, but it eventually transitioned to `ready`.

**Comment by epicfaace** [comment]
How large was it?

**Comment by percyliang** [comment]
captured by #158
