### ISSUE TITLE
Manual upload zip file stuck 

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3579]
Manual upload of three zip files stuck in "uploading" for about 45 minutes

**Codalab Information**
- *Your username*: DeepLearning.AI
- *UUID of worksheet where problem occurred*: 0xaece8d397dd54037bf12603b2aea0d1f
- *UUID of problem bundle (please don't delete)*: 0xc620f44d71b3451f9f135a28c7302d1b, 0x7df31975843c4ecb8b3459324c26d26a, 0xa7c4c320e32f4b0ebea63626877d8578
- *Error message received from Codalab (if applicable)*: N/A
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
Try manual uploading this file: 
[val.zip](https://github.com/codalab/codalab-worksheets/files/6563345/val.zip)

**Expected behavior**
Upload process to end within 5 minutes

**Screenshots**
<img width="1189" alt="Screen Shot 2021-05-28 at 3 04 45 PM" src="https://user-images.githubusercontent.com/51978114/120042218-a4e0c580-bfd7-11eb-9e54-112b336dfae7.png">

**Comment by lynn-he** [comment]
[val.zip](https://github.com/codalab/codalab-worksheets/files/6563663/val.zip)
have also tried with only png files and no __MACOSX folders

**Comment by epicfaace** [comment]
@lynn-he as a temporary workaround, it looks like this does work if you use `cl upload val.zip` from the CLI. We're working on fixing this issue on the frontend as well, though!

**Comment by lynn-he** [comment]
@epicfaace thank you!!

**Comment by epicfaace** [comment]
Stack trace for zip file uploads:


Traceback (most recent call last): File "/opt/codalab-worksheets/codalab/rest/bundles.py", line 798, in _update_bundle_contents_blob use_azure_blob_beta=use_azure_blob_beta, File "/opt/codalab-worksheets/codalab/lib/upload_manager.py", line 217, in upload_to_bundle_store bundle, source, git, unpack File "/opt/codalab-worksheets/codalab/lib/upload_manager.py", line 74, in upload_to_bundle_store self.write_fileobj(source_ext, source_fileobj, bundle_path, unpack_archive=True) File "/opt/codalab-worksheets/codalab/lib/upload_manager.py", line 139, in write_fileobj zip_util.unpack(source_ext, source_fileobj, bundle_path) File "/opt/codalab-worksheets/codalab/lib/zip_util.py", line 74, in unpack unzip_directory(source, dest_path) File "/opt/codalab-worksheets/codalab/worker/file_util.py", line 165, in unzip_directory for member in zf: # type: ignore File "/opt/codalab-worksheets/codalab/lib/beam/streamingzipfile.py", line 167, in __iter__ zipinfo = self.next() File "/opt/codalab-worksheets/codalab/lib/beam/streamingzipfile.py", line 115, in next raise BadZipFile("Bad magic number for file header") zipfile.BadZipFile: Bad magic number for file header

**Comment by epicfaace** [comment]
Reopening as this still seems to happen in some capacity, with the failure message 'Upload failed: Invalid archive upload.'

For example:

https://worksheets.codalab.org/bundles/0xd231f3ad64454df282fbffbee1d2d5ec
https://worksheets.codalab.org/bundles/0x5f59e647f5444562a933c75a4d686b41
https://worksheets.codalab.org/bundles/0xaf687234c8f043cfa8b35923ddf7186e

**Comment by epicfaace** [comment]
^^ The error we're getting on our end from unzip is "End-of-central-directory signature not found.  Either this file is not\n  a zipfile, or it constitutes one disk of a multi-part archive.  In the\n  latter case the central directory and zipfile comment will be found on\n  the last disk(s) of this archive." -- so it appears that somehow the file is not being transferred properly over the network / read by the server correctly.

**Comment by epicfaace** [comment]
This is still happening (first time failed, second time succeeded). The failure is with the same error as above:

first time: https://worksheets-dev.codalab.org/bundles/0xaead74aa097d4271a65d644744f83d88
second time: https://worksheets-dev.codalab.org/bundles/0x3029400f10f648249632bb11cdbd80ad

**Comment by epicfaace** [comment]
Closing this as this doesn't seem to happen often / predictably. Will reopen if we start seeing it happen again.
