### ISSUE TITLE
run bundles fail inconsistently on a file or directory not found error

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3627]
**Describe the bug**
When creating a CodaLab run bundle, the bundle will throw an error where it cannot find a file, when the user has the file. When user reruns, oftentimes the run bundle will work 

**Codalab Information**
- *Your username*: DeepLearning.AI
- *UUID of worksheet where problem occurred*: 0x37a5b4d4ec494cdeaedc73850336b8c1
- *UUID of problem bundle (please don't delete)*: 

0x5272942315f548458c6e9cde549cf617

If you look at the rest of the worksheet, you can see several predict-run-train bundles which fail for similar reasons. 
- *Error message received from Codalab (if applicable)*:
2021-06-18 20:05:23.462139: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-18 20:05:25.472894: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-18 20:05:25.475710: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2294680000 Hz
2021-06-18 20:27:19.126327: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/data/train/i/abab984c-ce5d-11eb-b317-38f9d35ea60f.png; No such file or directory
Traceback (most recent call last):
  File "/0x5272942315f548458c6e9cde549cf617/train.py", line 86, in <module>
    history = model.fit(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError:  data/data/train/i/abab984c-ce5d-11eb-b317-38f9d35ea60f.png; No such file or directory
	 [[{{node ReadFile}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_6791]

Function call stack:
train_function
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Many different browsers

**To Reproduce**
Steps to reproduce the behavior :
try following the steps for submission outlined in this guide: https://worksheets.codalab.org/worksheets/0x7a8721f11e61436e93ac8f76da83f0e6

**Expected behavior**
The run bundle to fail or succeed consistently. 

**Screenshots**
<img width="1143" alt="Screen Shot 2021-06-18 at 3 22 54 PM" src="https://user-images.githubusercontent.com/51978114/122617216-0fba7500-d049-11eb-9acf-9875e482a30e.png">

**Additional context**

**Comment by lynn-he** [comment]
This is from one of our users: https://worksheets.codalab.org/worksheets/0x254685377fba49009cc09d4979b81f51

**Comment by epicfaace** [comment]
@teetone is this similar to https://github.com/codalab/codalab-worksheets/issues/3236?

**Comment by LlewellynS96** [comment]
I can confirm that I am experiencing the same issue as described by @lynn-he.

**Comment by HiteshKhandelwal901** [comment]
I have been experiencing this error too. Though the file exists in my dataset, I consistently keep getting "file not found" here. What's even weirder is that just re run after few failed attempts solves the problem. In my case it fails for like 3-4 runs and on the 4th or 5th run it successfully runs though I make no changes.
![error](https://user-images.githubusercontent.com/57189255/123037084-b1f0a900-d40b-11eb-9e03-370e21b8a91a.PNG)

**Comment by KulkarniKaustubh** [comment]
I am experiencing the same issues. Here is the error message I am getting:

![image](https://user-images.githubusercontent.com/55317079/123049985-cccc1900-d41d-11eb-83b5-e1f915f4c390.png)

- Locally running the file yields no errors and runs perfectly well.
- I got this error at the 45th epoch of running the script.

**Comment by conceptofmind** [comment]
Same issue here:

2021-06-29 16:37:23.202999: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-29 16:37:24.910338: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-29 16:37:24.912448: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2596990000 Hz
2021-06-29 17:18:26.327289: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: sample_submission/sample_submission/train/iii/b05ca9c6-ce5d-11eb-b317-38f9d35ea60f.png; No such file or directory
Traceback (most recent call last):
  File "/0xb9b9bffbb05740e8a862a59304ebce77/train.py", line 86, in <module>
    history = model.fit(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError:  sample_submission/sample_submission/train/iii/b05ca9c6-ce5d-11eb-b317-38f9d35ea60f.png; No such file or directory
	 [[{{node ReadFile}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_6791]

Function call stack:
train_function

**Comment by RensDimmendaal** [comment]
I experience the same issue as described in the first post. During different runs it cannot find a different file during diffferent epochs.

**Comment by teetone** [comment]
Sorry for the inconvenience everyone. We are actively working on fixing this issue.

**Comment by epicfaace** [comment]
Related issues: https://github.com/codalab/codalab-worksheets/issues/3236, https://github.com/codalab/codalab-worksheets/issues/2440, https://github.com/codalab/codalab-worksheets/issues/2723, https://github.com/codalab/codalab-worksheets/issues/1417

**Comment by epicfaace** [comment]
All -- this issue has been closed because the PR with the fix has been merged, but it should be deployed to https://worksheets.codalab.org/ in the next release later this week.
