### ISSUE TITLE
Failed to download dependency <dependency>: Dependency download failed: The read operation timed out.

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3634]
Handful of my bundles failed with  **Dependency download failed: The read operation timed out.** 

It looks like a regression. I don't think I've ran into this particular error before and it happens frequently.

**Comment by epicfaace** [comment]
I also faced this same issue when trying to upload via a URL:

```
(venv) :~/environment/codalab/codalab-worksheets $ time cl upload -a "https://storage.googleapis.com/kagglesdsdata/competitions/17433/824213/imagenet_object_localization_patched2019.tar.gz?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1624911422&Signature=...&response-content-disposition=attachment%3B+filename%3Dimagenet_object_localization_patched2019.tar.gz"
Traceback (most recent call last):
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/client/json_api_client.py", line 653, in upload_contents_blob
    self._make_request(method='PUT', path=request_path, query_params=params)
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/worker/rest_client.py", line 106, in _make_request
    with closing(urlopen_with_retry(request, timeout=timeout_seconds)) as response:
  File "/home/ubuntu/environment/codalab/codalab-worksheets/venv/lib/python3.6/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/environment/codalab/codalab-worksheets/venv/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/home/ubuntu/environment/codalab/codalab-worksheets/venv/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/common.py", line 149, in urlopen_with_retry
    return urllib.request.urlopen(request, timeout=timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/environment/codalab/codalab-worksheets/venv/bin/cl", line 33, in <module>
    sys.exit(load_entry_point('codalab', 'console_scripts', 'cl')())
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/lib/bundle_cli.py", line 954, in do_command
    structured_result = command_fn()
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/lib/bundle_cli.py", line 948, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/lib/bundle_cli.py", line 1355, in do_upload_command
    'use_azure_blob_beta': args.use_azure_blob_beta,
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/client/json_api_client.py", line 52, in wrapper
    sys.exc_info()[2],
  File "/home/ubuntu/environment/codalab/codalab-worksheets/venv/lib/python3.6/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/client/json_api_client.py", line 653, in upload_contents_blob
    self._make_request(method='PUT', path=request_path, query_params=params)
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/worker/rest_client.py", line 106, in _make_request
    with closing(urlopen_with_retry(request, timeout=timeout_seconds)) as response:
  File "/home/ubuntu/environment/codalab/codalab-worksheets/venv/lib/python3.6/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/environment/codalab/codalab-worksheets/venv/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/home/ubuntu/environment/codalab/codalab-worksheets/venv/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/ubuntu/environment/codalab/codalab-worksheets/codalab/common.py", line 149, in urlopen_with_retry
    return urllib.request.urlopen(request, timeout=timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
codalab.client.json_api_client.JsonApiException: Unable to upload contents of bundle 0x39f39df679284c7183e59eca75884eac: The read operation timed out
```
