### ISSUE TITLE
Data-Centric AI Competition Training Fails Consistently

### ISSUE THREAD

**Issue by conceptofmind** [codalab/codalab-worksheets#3650]
Training function provided to us fails on every run at random points.

Codalab Information

Your username: HenryShippole

UUID of worksheet where problem occurred: 0xc5cd77630754407ebea11d5e8dce58a6

Error message received from Codalab:
2021-06-29 15:52:29.923202: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-29 15:52:31.900681: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-29 15:52:31.903343: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2294685000 Hz
2021-06-29 15:52:34.816542: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 18665472 exceeds 10% of free system memory.
2021-06-29 15:52:34.862168: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 18665472 exceeds 10% of free system memory.
2021-06-29 15:52:34.913126: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 18665472 exceeds 10% of free system memory.
2021-06-29 15:52:34.968507: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 18665472 exceeds 10% of free system memory.
2021-06-29 15:52:35.016339: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 18665472 exceeds 10% of free system memory.
2021-06-29 16:31:29.373343: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: sample_submission/sample_submission/train/ix/aecde980-ce5d-11eb-b317-38f9d35ea60f_large_shift_scale_rotate.png; No such file or directory
Traceback (most recent call last):
  File "/0xc5cd77630754407ebea11d5e8dce58a6/train.py", line 86, in <module>
    history = model.fit(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError:  sample_submission/sample_submission/train/ix/aecde980-ce5d-11eb-b317-38f9d35ea60f_large_shift_scale_rotate.png; No such file or directory
	 [[{{node ReadFile}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_6791]

Function call stack:
train_function

Browser: Microsoft Edge

Worksheet: https://worksheets.codalab.org/worksheets/0xf29e14c93502417198abc4f537634c70

**Comment by epicfaace** [comment]
Closing as a duplicate of https://github.com/codalab/codalab-worksheets/issues/3627. We're working on a fix!

**Comment by conceptofmind** [comment]
> Closing as a duplicate of #3627. We're working on a fix!

Ok. Thank you!
