### ISSUE TITLE
Blob storage error when uploading large (11 GB) file

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3665]
I get this error when uploading a 11 GB file using `cl upload -a`:

Traceback (most recent call last): File "/opt/codalab-worksheets/codalab/rest/bundles.py", line 798, in _update_bundle_contents_blob use_azure_blob_beta=use_azure_blob_beta, File "/opt/codalab-worksheets/codalab/lib/upload_manager.py", line 217, in upload_to_bundle_store bundle, source, git, unpack File "/opt/codalab-worksheets/codalab/lib/upload_manager.py", line 78, in upload_to_bundle_store source_ext, source_fileobj, bundle_path, unpack_archive=False File "/opt/codalab-worksheets/codalab/lib/upload_manager.py", line 169, in write_fileobj shutil.copyfileobj(output_fileobj, out) File "/usr/local/lib/python3.6/dist-packages/apache_beam/io/filesystemio.py", line 220, in close self._uploader.finish() File "/opt/codalab-worksheets/codalab/lib/beam/blobstorageuploader.py", line 54, in finish self._write_to_blob(self.buffer) File "/opt/codalab-worksheets/codalab/lib/beam/blobstorageuploader.py", line 49, in _write_to_blob self._blob_to_upload.stage_block(block_id, data) File "/usr/local/lib/python3.6/dist-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer return func(*args, **kwargs) File "/usr/local/lib/python3.6/dist-packages/azure/storage/blob/_blob_client.py", line 1977, in stage_block return self._client.block_blob.stage_block(**options) File "/usr/local/lib/python3.6/dist-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 349, in stage_block raise models.StorageErrorException(response, self._deserialize) File "/usr/local/lib/python3.6/dist-packages/azure/storage/blob/_generated/models/_models_py3.py", line 1817, in __init__ self.error = deserialize(model_name, response) File "/usr/local/lib/python3.6/dist-packages/msrest/serialization.py", line 1367, in __call__ data = self._unpack_content(response_data, content_type) File "/usr/local/lib/python3.6/dist-packages/msrest/serialization.py", line 1541, in _unpack_content raw_data.headers File "/usr/local/lib/python3.6/dist-packages/msrest/pipeline/universal.py", line 226, in deserialize_from_http_generics return cls.deserialize_from_text(body_bytes, content_type) File "/usr/local/lib/python3.6/dist-packages/msrest/pipeline/universal.py", line 203, in deserialize_from_text raise DeserializationError("Cannot deserialize content-type: {}".format(content_type)) msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/html

Bundle: https://worksheets-dev.codalab.org/bundles/0x72a7d091bb3d4388946982bdc88d367a

**Comment by epicfaace** [comment]
Better logging -- it appears that the length of the data input and the Content-Length header do not match in the final call to Blob Storage:


```
_write_to_blob 104857600 b54c39a9
_write_to_blob 66908600 727f7798
Request <HttpRequest [PUT]> PUT https://storageclwsdev0.blob.core.windows.net/bundles/0x72a7d091bb3d4388946982bdc88d367a/content
s.gz?blockid=SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBeE1qYz0%3D&comp=block {'Content-Type': 'application/octet-strea
m', 'Content-Length': '66908600', 'x-ms-version': '2019-12-12', 'x-ms-date': 'Mon, 05 Jul 2021 21:48:40 GMT', 'x-ms-client-reque
st-id': 'c27c3fb8-ddda-11eb-80e6-000d3a1d402e', 'User-Agent': 'azsdk-python-storage-blob/12.4.0 Python/3.6.12 (Linux-4.15.0-1098
-azure-x86_64-with-Ubuntu-16.04-xenial)', 'Authorization': 'SharedKey storageclwsdev0:...
E='} 65204664 Response Bad Request b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">\r
\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>\r\n<BO
DY><h2>Bad Request - Invalid Content Length</h2>\r\n<hr><p>HTTP Error 400. There is an invalid content length or chunk length in
 the request.</p>\r\n</BODY></HTML>\r\n'
Traceback (most recent call last):
  File "testupload.py", line 29, in <module>
    main()
  File "testupload.py", line 26, in main
    False,
  File "/home/azureuser/codalab-worksheets/codalab/lib/upload_manager.py", line 169, in write_fileobj
    shutil.copyfileobj(output_fileobj, out)
  File "/home/azureuser/venv/lib/python3.6/site-packages/apache_beam/io/filesystemio.py", line 220, in close
    self._uploader.finish()
  File "/home/azureuser/codalab-worksheets/codalab/lib/beam/blobstorageuploader.py", line 56, in finish
    self._write_to_blob(self.buffer)
  File "/home/azureuser/codalab-worksheets/codalab/lib/beam/blobstorageuploader.py", line 51, in _write_to_blob
    self._blob_to_upload.stage_block(block_id, data)
  File "/home/azureuser/venv/lib/python3.6/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/azureuser/venv/lib/python3.6/site-packages/azure/storage/blob/_blob_client.py", line 1977, in stage_block
    return self._client.block_blob.stage_block(**options)
  File "/home/azureuser/venv/lib/python3.6/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", l$ne 350, in stage_block
    raise Exception(response) 
Exception: <azure.core.pipeline.transport._requests_basic.RequestsTransportResponse object at 0x7f36542c8320>
_write_to_blob 65204664 c007d533
Request <HttpRequest [PUT]> PUT https://storageclwsdev0.blob.core.windows.net/bundles/0x72a7d091bb3d4388946982bdc88d367a/content
s.gz?blockid=SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBeE1qYz0%3D&comp=block {'Content-Type': 'application/octet-strea
m', 'Content-Length': '65204664', 'x-ms-version': '2019-12-12', 'x-ms-date': 'Mon, 05 Jul 2021 21:48:40 GMT', 'x-ms-client-reque
st-id': 'c27c3fb9-ddda-11eb-80e6-000d3a1d402e', 'User-Agent': 'azsdk-python-storage-blob/12.4.0 Python/3.6.12 (Linux-4.15.0-1098
-azure-x86_64-with-Ubuntu-16.04-xenial)', 'Authorization': 'SharedKey storageclwsdev0:mD3g7Faa0/IR0b0q/...
Q='} 65008056 Response Bad Request b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">\r
\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>\r\n<BO
DY><h2>Bad Request - Invalid Content Length</h2>\r\n<hr><p>HTTP Error 400. There is an invalid content length or chunk length in
 the request.</p>\r\n</BODY></HTML>\r\n'
_write_to_blob 65008056 a2cf4748
Request <HttpRequest [PUT]> PUT https://storageclwsdev0.blob.core.windows.net/bundles/0x72a7d091bb3d4388946982bdc88d367a/content
s.gz?blockid=SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBeE1qYz0%3D&comp=block {'Content-Type': 'application/octet-strea
m', 'Content-Length': '65008056', 'x-ms-version': '2019-12-12', 'x-ms-date': 'Mon, 05 Jul 2021 21:48:40 GMT', 'x-ms-client-reque
st-id': 'c27c3fba-ddda-11eb-80e6-000d3a1d402e', 'User-Agent': 'azsdk-python-storage-blob/12.4.0 Python/3.6.12 (Linux-4.15.0-1098
-azure-x86_64-with-Ubuntu-16.04-xenial)', 'Authorization': 'SharedKey storageclwsdev0:I0jZtTriDq/...
s='} 64713144 Response Bad Request b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">\r
\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>\r\n<BO
DY><h2>Bad Request - Invalid Content Length</h2>\r\n<hr><p>HTTP Error 400. There is an invalid content length or chunk length in
 the request.</p>\r\n</BODY></HTML>\r\n'
(venv) vm-clws-dev-server-0:~/ashwin% 
```
