### ISSUE TITLE
Competition daemon read operation timeout

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3754]
**Describe the bug**
When running competition daemon, throws this exception: `codalab.client.json_api_client.JsonApiException: Unable to interpret file genpaths: The read operation timed out` and does not update leaderboard.

**Codalab Information**
- *Your username*: DeepLearning.AI 
- *Error message received from Codalab (if applicable)*:
```Traceback (most recent call last):
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 678, in interpret_file_genpaths
    return self._make_request(
  File "competitiond_fix.py", line 73, in _make_request
    return super(JsonApiClientWithRetry, self)._make_request(*args, **kwargs)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/codalab/worker/rest_client.py", line 106, in _make_request
    with closing(urlopen_with_retry(request, timeout=timeout_seconds)) as response:
  File "<decorator-gen-2>", line 2, in urlopen_with_retry
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/codalab/common.py", line 149, in urlopen_with_retry
    return urllib.request.urlopen(request, timeout=timeout)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 1354, in do_open
    r = h.getresponse()
  File "/Users/lhe/opt/anaconda3/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/Users/lhe/opt/anaconda3/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/Users/lhe/opt/anaconda3/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/lhe/opt/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "competitiond_fix.py", line 782, in run
    self.run_once()
  File "competitiond_fix.py", line 775, in run_once
    self.generate_leaderboard(num_total_submissions, num_period_submissions)
  File "competitiond_fix.py", line 678, in generate_leaderboard
    scores = self._fetch_scores(eval_bundles)
  File "competitiond_fix.py", line 668, in _fetch_scores
    results = self.client.interpret_file_genpaths(queries)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 49, in wrapper
    six.reraise(
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 678, in interpret_file_genpaths
    return self._make_request(
  File "competitiond_fix.py", line 73, in _make_request
    return super(JsonApiClientWithRetry, self)._make_request(*args, **kwargs)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/codalab/worker/rest_client.py", line 106, in _make_request
    with closing(urlopen_with_retry(request, timeout=timeout_seconds)) as response:
  File "<decorator-gen-2>", line 2, in urlopen_with_retry
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Users/lhe/opt/anaconda3/lib/python3.8/site-packages/codalab/common.py", line 149, in urlopen_with_retry
    return urllib.request.urlopen(request, timeout=timeout)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/lhe/opt/anaconda3/lib/python3.8/urllib/request.py", line 1354, in do_open
    r = h.getresponse()
  File "/Users/lhe/opt/anaconda3/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/Users/lhe/opt/anaconda3/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/Users/lhe/opt/anaconda3/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/lhe/opt/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/lhe/opt/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
codalab.client.json_api_client.JsonApiException: Unable to interpret file genpaths: The read operation timed out```


 - *OS (if on CLI)*: MacOS Catalina
 - *Codalab CLI Version (if on CLI)*: CodaLab CLI version 0.5.52
 - *Browser (if on Web)*;

**Comment by epicfaace** [comment]
Do you have any idea from the logs (maybe logs before this error) which bundle uuid this error is related to?

**Comment by lynn-he** [comment]
Seems like the daemon is able to create new evaluation runs, but unable to generate the leaderboard. Have tried running the command multiple times, it fails after finishing creating all the evaluation runs (so fails after different submission bundles have been processed). 

<img width="598" alt="Screen Shot 2021-08-16 at 11 43 22 AM" src="https://user-images.githubusercontent.com/51978114/129606543-cf99cadf-ea84-4569-923d-371b0c024c69.png">

and later:

<img width="563" alt="Screen Shot 2021-08-16 at 11 43 44 AM" src="https://user-images.githubusercontent.com/51978114/129606589-797cfedd-0925-4b7f-8dd6-294cb6412edd.png">

**Comment by lynn-he** [comment]
Hey @epicfaace , thanks for working on this. It started working again! I have no idea how or why, but I would like to keep this issue open in case it happens again.

**Comment by epicfaace** [comment]
That's great! Since it's been over a week, I'm just going to close this issue, but if it happens again, feel free to reopen this issue.

**Comment by lynn-he** [comment]
Sounds good, thanks Ashwin
