### ISSUE TITLE
cl-worker is broken

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3857]
```
% cl-worker
2021-10-14 10:48:33,808 Connecting to https://worksheets.codalab.org /home/.local/lib/python3.8/site-packages/codalab/worker/main.py 198
Username: 
Password: 
Traceback (most recent call last):
  File "/home/.local/bin/cl-worker", line 8, in <module>
    sys.exit(main())
  File "/home.local/lib/python3.8/site-packages/codalab/worker/main.py", line 265, in main
    dependency_manager = DependencyManager(
  File "/home/.local/lib/python3.8/site-packages/codalab/worker/dependency_manager.py", line 88, in __init__
    self._load_state()
  File "/home/.local/lib/python3.8/site-packages/codalab/worker/dependency_manager.py", line 109, in _load_state
    for dep, dep_state in state['dependencies'].items():
TypeError: list indices must be integers or slices, not str
```

**Comment by teetone** [comment]
`cl-worker` seems to be working again with the latest CLI version `1.1.5`:

```
(default-py37) tonyhlee@john7:~$ cl --version
CodaLab CLI version 1.1.5

(default-py37) tonyhlee@john7:~$ cl-worker
2021-10-26 14:36:47,823 Connecting to https://worksheets.codalab.org /u/nlp/anaconda/main/anaconda3/envs/default-py37/lib/python3.7/site-packages/codalab/worker/main.py 198
Username: tonyhlee2
Password:
2021-10-26 14:36:54,055 Loaded 0 dependencies, 0 paths from cache. /u/nlp/anaconda/main/anaconda3/envs/default-py37/lib/python3.7/site-packages/codalab/worker/dependency_manager.py 120
2021-10-26 14:36:56,553 Cannot initialize NVIDIA runtime, no GPU support: Problem getting NVIDIA devices: 500 Server Error: Internal Server Error ("OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown") /u/nlp/anaconda/main/anaconda3/envs/default-py37/lib/python3.7/site-packages/codalab/worker/docker_utils.py 100
2021-10-26 14:36:56,838 Worker started! /u/nlp/anaconda/main/anaconda3/envs/default-py37/lib/python3.7/site-packages/codalab/worker/main.py 333
2021-10-26 14:36:56,839 Starting image manager /u/nlp/anaconda/main/anaconda3/envs/default-py37/lib/python3.7/site-packages/codalab/worker/image_manager.py 52
2021-10-26 14:36:56,840 Starting local dependency manager /u/nlp/anaconda/main/anaconda3/envs/default-py37/lib/python3.7/site-packages/codalab/worker/dependency_manager.py 173
2021-10-26 14:37:00,344 Connected! Successful check in! /u/nlp/anaconda/main/anaconda3/envs/default-py37/lib/python3.7/site-packages/codalab/worker/worker.py 429
```

Worker started on https://worksheets.codalab.org:

![Screen Shot 2021-10-26 at 2 38 32 PM](https://user-images.githubusercontent.com/16793796/138964834-91ef45a3-695a-4386-9c54-a5e3e48769f7.png)
