### ISSUE TITLE
ratarmount issue - update tests

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3906]
Use codalab CLI version 1.3.0 (before the fix).

Look into why the tests didn't catch this error when running a `cl` command:

```
Traceback (most recent call last):
  File "/u/nlp/anaconda/main/anaconda3/bin/cl", line 5, in <module>
    from codalab.bin.cl import main
  File "/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/codalab/bin/cl.py", line 3, in <module>
    from codalab.lib.bundle_cli import BundleCLI
  File "/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 39, in <module>
    import codalab.model.bundle_model as bundle_model
  File "/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/codalab/model/bundle_model.py", line 19, in <module>
    from codalab.bundles import get_bundle_subclass
  File "/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/codalab/bundles/__init__.py", line 4, in <module>
    from codalab.bundles.run_bundle import RunBundle
  File "/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/codalab/bundles/run_bundle.py", line 16, in <module>
    from codalab.lib.completers import DockerImagesCompleter
  File "/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/codalab/lib/completers.py", line 15, in <module>
    from codalab.worker.download_util import BundleTarget
  File "/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/codalab/worker/download_util.py", line 11, in <module>
    from codalab.worker.file_util import OpenIndexedArchiveFile
  File "/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/codalab/worker/file_util.py", line 15, in <module>
    from codalab.worker.tar_subdir_stream import TarSubdirStream
  File "/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/codalab/worker/tar_subdir_stream.py", line 5, in <module>
    from ratarmountcore import FileInfo
  File "/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/ratarmountcore/__init__.py", line 53, in <module>
    from .ZipMountSource import ZipMountSource
  File "/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/ratarmountcore/ZipMountSource.py", line 11, in <module>
    from .compressions import zipfile
ImportError: cannot import name 'zipfile' from 'ratarmountcore.compressions' (/u/nlp/anaconda/main/anaconda3/lib/python3.7/site-packages/ratarmountcore/compressions.py)
```

Update tests to test for this error.

**Comment by mxmlnkn** [comment]
> Look into why the tests didn't catch this error when running a `cl` command:

Note that this bug didn't trigger my CI either because it can only be triggered for Python versions with a bugfix version < 6. Dumb error on my part. See also the [bugfix commit](https://github.com/mxmlnkn/ratarmount/commit/83fa858e7aeaf6f1dc9a3a45b8b907aee35b3a76).

**Comment by epicfaace** [comment]
Hmmm, interesting, though this issue happened with python 3.7, so perhaps it's a different issue? (` cannot import name 'zipfile' from 'ratarmountcore.compressions' `)

**Comment by mxmlnkn** [comment]
> Hmmm, interesting, though this issue happened with python 3.7, so perhaps it's a different issue? (`cannot import name 'zipfile' from 'ratarmountcore.compressions'`)

"Bugfix version". I wanted to test for versions smaller 3.6 but the bug made it actually trigger e.g. for 3.7.0 to 3.7.6 but not for 3.7.7.

**Comment by epicfaace** [comment]
Ah, thanks.

**Comment by epicfaace** [comment]
It's not easy to reproduce this on CI because python with older bugfix versions is not easily available on GHA (see https://github.com/codalab/codalab-worksheets/pull/3951). So I'm going to just treat this as an isolated incident which we don't need to cover going forward.

I will add 3.10 to CI, though, which is a good thing anyway.
