### ISSUE TITLE
GCP - Bundle stops uploading at 14.3gb 

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3998]
A large bundle (30 GB) stops uploading at 14.3gb transferred, when it's being uploaded to GCS.

Stack trace:

```
Preparing upload archive...
Uploading raw_data.tar.gz (0x1637c04715a145e38ec066ce0d0ee36f) to https://cs324.codalab.org/
Sent 14623.82MiB [5.75MiB/sec]
Traceback (most recent call last):
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 655, in upload_contents_blob
    self._upload_with_chunked_encoding(
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/codalab/worker/rest_client.py", line 185, in _upload_with_chunked_encoding
    raise urllib.error.HTTPError(
urllib.error.HTTPError: HTTP Error 504: Gateway Time-out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/bin/cl", line 8, in <module>
    sys.exit(main())
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/codalab/lib/bundle_cli.py", line 955, in do_command
    structured_result = command_fn()
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/codalab/lib/bundle_cli.py", line 949, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/codalab/lib/bundle_cli.py", line 1478, in do_upload_command
    client.upload_contents_blob(
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 28, in wrapper
    six.reraise(
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 655, in upload_contents_blob
    self._upload_with_chunked_encoding(
  File "/u/nlp/anaconda/main/anaconda3/envs/cs324-p2/lib/python3.8/site-packages/codalab/worker/rest_client.py", line 185, in _upload_with_chunked_encoding
    raise urllib.error.HTTPError(
codalab.client.json_api_client.JsonApiException: Unable to upload contents of bundle 0x1637c04715a145e38ec066ce0d0ee36f: Gateway Timeout - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.12.0</center>
</body>
</html>
```

**Comment by pranavjain** [comment]
@epicfaace Is this a blocker? We would need this fixed to use CodaLab for the course, right?

**Comment by epicfaace** [comment]
No -- we can use codalab for the course with the disk storage, which is what cs324.codalab.org is using at the moment. It would be ideal to fix this so we can use GCS storage, though.

**Comment by wwwjn** [comment]
Update on Oct. 17, 2022:

Test: **Upload from my local PC -> GCS, openwebtext dataset (38GB)**


![Image](https://user-images.githubusercontent.com/40016222/196297658-ff045229-8daf-4317-b98b-208ec10a9af4.png)



Since we are using bypass server uploading for GCS now, the upload process take quite long time because of generating index. If we [change the signed token expire time](https://github.com/codalab/codalab-worksheets/pull/4280) to enough long time (eg, 10h), upload succeed. The slow upload problem will be fixed after issue # is fixed.
