### ISSUE TITLE
NFS folder can't be mounted by worker

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4036]
Because docker container doesn't have the right capabilities. See https://stackoverflow.com/questions/39922161/mounting-nfs-shares-inside-docker-container

**Comment by epicfaace** [comment]
Docker documentation for `--mount`: https://docs.docker.com/storage/volumes/#create-a-service-which-creates-an-nfs-volume

We can use the `mount` argument in the docker python SDK (see https://docker-py.readthedocs.io/en/stable/containers.html) and we'd need to modify this piece of code: https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/docker_utils.py#L197-L214

**Comment by epicfaace** [comment]
Worker should have a new flag that indicates when the work directory is on NFS. In that case, we would use `--mount` and the special NFS-specific parameters to mount it rather than `--volume`.

**Comment by pranavjain** [comment]
Talked with @teetone about it. Please update the ETA.

**Comment by pranavjain** [comment]
@teetone Can you please put an ETA to this task?

**Comment by teetone** [comment]
Worker launched via the worker manager with `/exports` as one of the volume mounts:

```
 Starting a worker!
 {'containers': [{'name': 'cl-worker-46a5fa6343de40e19fe76f8bea59717a-container', 'image': 'codalab/worker:testdeploy', 'command': ['cl-worker', '--server', 'https://worksheets.codalab.org', '--verbose', '--exit-when-idle', '--idle-seconds', '600', '--work-dir', '/exports/codalab-worker-scratch', '--id', '$(hostname -s)-46a5fa6343de40e19fe76f8bea59717a', '--network-prefix', 'cl_worker_46a5fa6343de40e19fe76f8bea59717a_network', '--tag', 'gcp', '--exit-after-num-runs', '5', '--download-dependencies-max-retries', '3', '--max-work-dir-size', '450g', '--tag-exclusive', '--pass-down-termination', '--shared-memory-size-gb', '8'], 'securityContext': {'runAsUser': 0}, 'env': [{'name': 'CODALAB_USERNAME', 'value': 'tonyhlee2'}, {'name': 'CODALAB_PASSWORD', 'value': 'codalabstanford'}], 'resources': {'limits': {'cpu': 6, 'memory': '22000Mi', 'nvidia.com/gpu': 0}}, 'volumeMounts': [{'name': 'dockersock', 'mountPath': '/var/run/docker.sock'}, {'name': 'nfs', 'mountPath': '/exports'}]}], 'volumes': [{'name': 'dockersock', 'hostPath': {'path': '/var/run/docker.sock'}}, {'name': 'nfs', 'persistentVolumeClaim': {'claimName': 'nfs-claim'}}], 'restartPolicy': 'Never'}
```

The NFS server has the dependencies:

```
(venv) tonyhlee@DN0a22a2eb gcp-for-codalab % kubectl exec -it nfs-server-7bd7f87b84-26nfp -- df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          97G  4.0G   93G   5% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/sdb        295G   52G  243G  18% /exports
/dev/root        97G  4.0G   93G   5% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           7.9G   12K  7.9G   1% /run/secrets/kubernetes.io/serviceaccount
```

The worker pod is able to access the dependencies stored on the NFS server:

```
(venv) tonyhlee@DN0a22a2eb gcp-for-codalab % kubectl exec -it cl-worker-46a5fa6343de40e19fe76f8bea59717a -- df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          97G  7.9G   89G   9% /
tmpfs            64M     0   64M   0% /dev
tmpfs            15G     0   15G   0% /sys/fs/cgroup
10.24.11.180:/  295G   52G  243G  18% /exports
/dev/root        97G  7.9G   89G   9% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           3.0G  3.1M  3.0G   1% /run/docker.sock
tmpfs            15G   12K   15G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            15G     0   15G   0% /proc/acpi
tmpfs            15G     0   15G   0% /proc/scsi
tmpfs            15G     0   15G   0% /sys/firmware
```

```
(venv) tonyhlee@DN0a22a2eb gcp-for-codalab % kubectl exec -it cl-worker-46a5fa6343de40e19fe76f8bea59717a -- ls /exports
codalab-worker-scratch	index.html  lost+found
```

How we mount before and after:

```
volumes: 
{'/exports/codalab-worker-scratch/dependencies/0xc12cfe54d7ca4a5ba3d0013f9b1a2db7': {'bind': '/0xd0f499c3d85a43d2a4f63bb65c5f434a_dependencies/wilds', 'mode': 'ro'}, 
'/exports/codalab-worker-scratch/dependencies/0xa7e54b6ee8d64230bf887a4cb32ba9e5': {'bind': '/0xd0f499c3d85a43d2a4f63bb65c5f434a_dependencies/wandb_api_key.txt', 'mode': 'ro'}, 
'/exports/codalab-worker-scratch/dependencies/0xaec91eb7c9d548ebb15e1b5e60f966ab': {'bind': '/0xd0f499c3d85a43d2a4f63bb65c5f434a_dependencies/fmow_v1.1', 'mode': 'ro'}, 
'/exports/codalab-worker-scratch/dependencies/0x3b7e033b88464f53a3c432614bda72d3': {'bind': '/0xd0f499c3d85a43d2a4f63bb65c5f434a_dependencies/teacher', 'mode': 'ro'}, 
'/exports/codalab-worker-scratch/runs/0xd0f499c3d85a43d2a4f63bb65c5f434a': {'bind': '/0xd0f499c3d85a43d2a4f63bb65c5f434a', 'mode': 'rw'}}
```

```
mounts (should be 'Type': 'bind'): 
[{'Target': '/0xd0f499c3d85a43d2a4f63bb65c5f434a_dependencies/wilds', 'Source': '/exports/codalab-worker-scratch/dependencies/0xc12cfe54d7ca4a5ba3d0013f9b1a2db7', 'Type': 'volume', 'ReadOnly': True}, {'Target': '/0xd0f499c3d85a43d2a4f63bb65c5f434a_dependencies/wandb_api_key.txt', 'Source': '/exports/codalab-worker-scratch/dependencies/0xa7e54b6ee8d64230bf887a4cb32ba9e5', 'Type': 'volume', 'ReadOnly': True}, 
{'Target': '/0xd0f499c3d85a43d2a4f63bb65c5f434a_dependencies/fmow_v1.1', 'Source': '/exports/codalab-worker-scratch/dependencies/0xaec91eb7c9d548ebb15e1b5e60f966ab', 'Type': 'volume', 'ReadOnly': True}, 
{'Target': '/0xd0f499c3d85a43d2a4f63bb65c5f434a_dependencies/teacher', 'Source': '/exports/codalab-worker-scratch/dependencies/0x3b7e033b88464f53a3c432614bda72d3', 'Type': 'volume', 'ReadOnly': True}, 
{'Target': '/0xd0f499c3d85a43d2a4f63bb65c5f434a', 'Source': '/exports/codalab-worker-scratch/runs/0xd0f499c3d85a43d2a4f63bb65c5f434a', 'Type': 'volume', 'ReadOnly': False}] 
```

```
Traceback (most recent call last): 

File "/opt/codalab/worker/docker_utils.py", line 223, in start_bundle_container stdin_open=tty,
 File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 810, in run detach=detach, **kwargs) 
File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 868, in create resp = self.client.api.create_container(**create_kwargs) 
File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 430, in create_container return self.create_container_from_config(config, name) 
File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 441, in create_container_from_config return self._result(res, True) 
File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 267, in _result self._raise_for_status(response) 
File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 263, in _raise_for_status raise create_api_error_from_http_exception(e) 
File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception raise cls(e, response=response, explanation=explanation) docker.errors.APIError: 400 Client Error: Bad Request ("create /exports/codalab-worker-scratch/dependencies/0xc12cfe54d7ca4a5ba3d0013f9b1a2db7: "/exports/codalab-worker-scratch/dependencies/0xc12cfe54d7ca4a5ba3d0013f9b1a2db7" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path")
```

Started using bind mounts instead.


Mounting without specifying NFS type for volume. I would think it would work because the worker pod already has access to it:
 
```
Traceback (most recent call last): File "/opt/codalab/worker/docker_utils.py", line 61, in wrapper return f(*args, **kwargs) File "/opt/codalab/worker/docker_utils.py", line 223, in start_bundle_container stdin_open=tty, File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 810, in run detach=detach, **kwargs) File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 868, in create resp = self.client.api.create_container(**create_kwargs) File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 430, in create_container return self.create_container_from_config(config, name) File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 441, in create_container_from_config return self._result(res, True) File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 267, in _result self._raise_for_status(response) File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 263, in _raise_for_status raise create_api_error_from_http_exception(e) File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception raise cls(e, response=response, explanation=explanation) docker.errors.APIError: 400 Client Error: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /exports/codalab-worker-scratch/dependencies/0xc12cfe54d7ca4a5ba3d0013f9b1a2db7")
```

Created NFS volume before mounting:


 nfs_volumes (current): 

```
{'exportscodalabworkerscratchdependencies0xc12cfe54d7ca4a5ba3d0013f9b1a2db7': {'bind': '/0x33654ef5f300487c8434f4e3d8a8355f_dependencies/wilds', 'mode': 'ro'}, 'exportscodalabworkerscratchdependencies0xa7e54b6ee8d64230bf887a4cb32ba9e5': {'bind': '/0x33654ef5f300487c8434f4e3d8a8355f_dependencies/wandb_api_key.txt', 'mode': 'ro'}, 'exportscodalabworkerscratchdependencies0xaec91eb7c9d548ebb15e1b5e60f966ab': {'bind': '/0x33654ef5f300487c8434f4e3d8a8355f_dependencies/fmow_v1.1', 'mode': 'ro'}, 'exportscodalabworkerscratchdependencies0x3b7e033b88464f53a3c432614bda72d3': {'bind': '/0x33654ef5f300487c8434f4e3d8a8355f_dependencies/teacher', 'mode': 'ro'}, 'exportscodalabworkerscratchruns0x33654ef5f300487c8434f4e3d8a8355f': {'bind': '/0x33654ef5f300487c8434f4e3d8a8355f', 'mode': 'rw'}}
```

```Python
        volume = client.volumes.create(
            name=dep_volume_name,
            driver='local',
            driver_opts={
                'type': 'nfs',
                'o': 'addr=<nfs server address>,vers=4,soft',
                'device': dep_abs_path,
            },
        )
```


```
Traceback (most recent call last): File "/opt/codalab/worker/docker_utils.py", line 61, in wrapper return f(*args, **kwargs) File "/opt/codalab/worker/docker_utils.py", line 226, in start_bundle_container stdin_open=tty, File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 810, in run detach=detach, **kwargs) File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 868, in create resp = self.client.api.create_container(**create_kwargs) File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 430, in create_container return self.create_container_from_config(config, name) File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 441, in create_container_from_config return self._result(res, True) File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 267, in _result self._raise_for_status(response) File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 263, in _raise_for_status raise create_api_error_from_http_exception(e) File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception raise cls(e, response=response, explanation=explanation) docker.errors.APIError: 500 Server Error: Internal Server Error ("failed to mount local volume: mount /exports/codalab-worker-scratch/runs/0x0a89a1d2795741f8964c4d6de6f896a7:/var/lib/docker/volumes/exportscodalabworkerscratchruns0x0a89a1d2795741f8964c4d6de6f896a7/_data, data: addr=10.24.11.180,vers=4,soft: invalid argument")
```

```
Traceback (most recent call last): File "/opt/codalab/worker/docker_utils.py", line 226, in start_bundle_container stdin_open=tty, File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 810, in run detach=detach, **kwargs) File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 868, in create resp = self.client.api.create_container(**create_kwargs) File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 430, in create_container return self.create_container_from_config(config, name) File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 441, in create_container_from_config return self._result(res, True) File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 267, in _result self._raise_for_status(response) File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 263, in _raise_for_status raise create_api_error_from_http_exception(e) File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception raise cls(e, response=response, explanation=explanation) docker.errors.APIError: 500 Server Error: Internal Server Error ("failed to mount local volume: mount /exports/codalab-worker-scratch/runs/0x0aafa2b3f02845f28aaa9b8ea3c78097:/var/lib/docker/volumes/exportscodalabworkerscratchruns0x0aafa2b3f02845f28aaa9b8ea3c78097/_data: invalid argument")
```

**Comment by pranavjain** [comment]
@teetone and @epicfaace will debug it further.

**Comment by teetone** [comment]
Closing as we will switch from containers to pods.
