### ISSUE TITLE
cl work error: ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by JiexingQi** [codalab/codalab-worksheets#4039]
**Describe the bug**
I follow the Tutorial: Quickstart in https://codalab-worksheets.readthedocs.io/en/latest/examples/quickstart/, and create a conda env named codalab and python version==3.8.8; Then I use 

```
$ pip install codalab -U 
```
and run 
```
cl work
```
when typed my username and password, it got an error :
```
(codalab) jxqi@han-server-01:~$ cl work
Requesting access at https://worksheets.codalab.org
Username: jxqi
Password: 
Traceback (most recent call last):
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/http/client.py", line 926, in connect
    self._tunnel()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/http/client.py", line 900, in _tunnel
    (version, code, message) = response._read_status()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 414, in fetch
    self._make_request(
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/rest_client.py", line 69, in _make_request
    access_token = self._get_access_token()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/lib/codalab_manager.py", line 441, in <lambda>
    lambda: self._authenticate(address, auth_handler),
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/lib/codalab_manager.py", line 511, in _authenticate
    token_info = auth_handler.generate_token('credentials', username, password)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/server/auth.py", line 44, in generate_token
    return self._make_token_request(
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/server/auth.py", line 64, in _make_token_request
    response = urlopen_with_retry(request)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/common.py", line 164, in urlopen_with_retry
    return urllib.request.urlopen(request, timeout=timeout)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jxqi/anaconda3/envs/codalab/bin/cl", line 8, in <module>
    sys.exit(main())
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/lib/bundle_cli.py", line 955, in do_command
    structured_result = command_fn()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/lib/bundle_cli.py", line 949, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/lib/bundle_cli.py", line 3217, in do_work_command
    client, worksheet_uuid = self.parse_client_worksheet_uuid(args.worksheet_spec)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/lib/bundle_cli.py", line 786, in parse_client_worksheet_uuid
    client, worksheet_uuid = self.manager.get_current_worksheet_uuid()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/lib/codalab_manager.py", line 527, in get_current_worksheet_uuid
    worksheet_uuid = client.fetch_one('worksheets', params={'specs': '/'})['uuid']
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 427, in fetch_one
    results = self.fetch(resource_type, resource_id=resource_id, params=params)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 49, in wrapper
    six.reraise(
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/client/json_api_client.py", line 414, in fetch
    self._make_request(
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/worker/rest_client.py", line 69, in _make_request
    access_token = self._get_access_token()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/lib/codalab_manager.py", line 441, in <lambda>
    lambda: self._authenticate(address, auth_handler),
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/lib/codalab_manager.py", line 511, in _authenticate
    token_info = auth_handler.generate_token('credentials', username, password)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/server/auth.py", line 44, in generate_token
    return self._make_token_request(
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/server/auth.py", line 64, in _make_token_request
    response = urlopen_with_retry(request)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/site-packages/codalab/common.py", line 164, in urlopen_with_retry
    return urllib.request.urlopen(request, timeout=timeout)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/jxqi/anaconda3/envs/codalab/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
codalab.client.json_api_client.JsonApiException: Unable to fetch worksheets: <urlopen error [Errno 104] Connection reset by peer>
```

**Codalab Information**
- *Your username*:jxqi
- *UUID of worksheet where problem occurred*:no id
- *UUID of problem bundle (please don't delete)*:no id
- *Error message received from Codalab (if applicable)*: as mentiond in description
 - *OS (if on CLI)*: Ubuntu 18.04.3 LTS
 - *Codalab CLI Version (if on CLI)*:  1.4.5
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

see description

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JiexingQi** [comment]
Update： I can connect successfully in my MacBook Pro，but it can‘t connect successfully in server。

**Comment by teetone** [comment]
Hi @JiexingQi, does this happen to you every time, or is it intermittently?

**Comment by JiexingQi** [comment]
Hi @teetone , it happens in my server every time, but it can connect successfully in my MacbookPro. Could you give me some suggestions about it? Thanks a lot.
