### ISSUE TITLE
Connection Error when launching jobs. Tested from `k8s-runtime` branch

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#4156]
```
2022-07-21 20:21:45,617 Exception when calling Kubernetes utils->create_from_dict...: HTTPSConnectionPool(host='34.90.237.115', port=443): Max retries exceeded with url: /api/v1/namespaces/default/pods (Caused by SSLError(FileNotFoundError(2, 'No such file or directory'))) /opt/codalab/worker/runtime/kubernetes_runtime.py 145
2022-07-21 20:21:45,617 Cannot start container: HTTPSConnectionPool(host='34.90.237.115', port=443): Max retries exceeded with url: /api/v1/namespaces/default/pods (Caused by SSLError(FileNotFoundError(2, 'No such file or directory'))) /opt/codalab/worker/worker_run_state.py 450
2022-07-21 20:21:45,623 Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 404, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker_run_state.py", line 435, in _transition_from_PREPARING
    shared_memory_size_gb=self.shared_memory_size_gb,
  File "/opt/codalab/worker/runtime/kubernetes_runtime.py", line 146, in start_bundle_container
    raise e
  File "/opt/codalab/worker/runtime/kubernetes_runtime.py", line 143, in start_bundle_container
    pod = utils.create_from_dict(self.k8_client, config)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/utils/create_from_yaml.py", line 130, in create_from_dict
    k8s_client, data, verbose, namespace=namespace, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/utils/create_from_yaml.py", line 168, in create_from_yaml_single_item
    body=yml_object, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 7320, in create_namespaced_pod
    return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 7429, in create_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 397, in request
    body=body)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 280, in POST
    body=body)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 172, in request
    headers=headers)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='34.90.237.115', port=443): Max retries exceeded with url: /api/v1/namespaces/default/pods (Caused by SSLError(FileNotFoundError(2, 'No such file or directory')))
 /opt/codalab/worker/worker_run_state.py 451
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 404, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 299, in start
    self.process_runs()
  File "/opt/codalab/worker/worker.py", line 502, in process_runs
    self.runs[uuid] = self.run_state_manager.transition(prev_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/worker_run_state.py", line 435, in _transition_from_PREPARING
    shared_memory_size_gb=self.shared_memory_size_gb,
  File "/opt/codalab/worker/runtime/kubernetes_runtime.py", line 146, in start_bundle_container
    raise e
  File "/opt/codalab/worker/runtime/kubernetes_runtime.py", line 143, in start_bundle_container
    pod = utils.create_from_dict(self.k8_client, config)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/utils/create_from_yaml.py", line 130, in create_from_dict
    k8s_client, data, verbose, namespace=namespace, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/utils/create_from_yaml.py", line 168, in create_from_yaml_single_item
    body=yml_object, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 7320, in create_namespaced_pod
    return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 7429, in create_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 397, in request
    body=body)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 280, in POST
    body=body)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 172, in request
    headers=headers)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='34.90.237.115', port=443): Max retries exceeded with url: /api/v1/namespaces/default/pods (Caused by SSLError(FileNotFoundError(2, 'No such file or directory')))
```

**Comment by teetone** [comment]
2022-07-21 21:34:36,062 Cannot start container: HTTPSConnectionPool(host='34.90.237.115', port=443): Max retries exceeded with url: /api/v1/namespaces/default/pods (Caused by SSLError(FileNotFoundError(2, 'No such file or directory'))) /opt/codalab/worker/worker_run_state.py 450
2022-07-21 21:34:36,068 Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 404, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker_run_state.py", line 435, in _transition_from_PREPARING
    shared_memory_size_gb=self.shared_memory_size_gb,
  File "/opt/codalab/worker/runtime/kubernetes_runtime.py", line 148, in start_bundle_container
    raise e
  File "/opt/codalab/worker/runtime/kubernetes_runtime.py", line 145, in start_bundle_container
    pod = utils.create_from_dict(self.k8_client, config)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/utils/create_from_yaml.py", line 130, in create_from_dict
    k8s_client, data, verbose, namespace=namespace, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/utils/create_from_yaml.py", line 168, in create_from_yaml_single_item
    body=yml_object, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 7320, in create_namespaced_pod
    return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 7429, in create_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 397, in request
    body=body)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 280, in POST
    body=body)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 172, in request
    headers=headers)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='34.90.237.115', port=443): Max retries exceeded with url: /api/v1/namespaces/default/pods (Caused by SSLError(FileNotFoundError(2, 'No such file or directory')))
 /opt/codalab/worker/worker_run_state.py 451
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 404, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 299, in start
    self.process_runs()
  File "/opt/codalab/worker/worker.py", line 502, in process_runs
    self.runs[uuid] = self.run_state_manager.transition(prev_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/worker_run_state.py", line 435, in _transition_from_PREPARING
    shared_memory_size_gb=self.shared_memory_size_gb,
  File "/opt/codalab/worker/runtime/kubernetes_runtime.py", line 148, in start_bundle_container
    raise e
  File "/opt/codalab/worker/runtime/kubernetes_runtime.py", line 145, in start_bundle_container
    pod = utils.create_from_dict(self.k8_client, config)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/utils/create_from_yaml.py", line 130, in create_from_dict
    k8s_client, data, verbose, namespace=namespace, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/utils/create_from_yaml.py", line 168, in create_from_yaml_single_item
    body=yml_object, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 7320, in create_namespaced_pod
    return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 7429, in create_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 397, in request
    body=body)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 280, in POST
    body=body)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 172, in request
    headers=headers)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='34.90.237.115', port=443): Max retries exceeded with url: /api/v1/namespaces/default/pods (Caused by SSLError(FileNotFoundError(2, 'No such file or directory')))

**Comment by epicfaace** [comment]
No longer replicable
