### ISSUE TITLE
Custom docker image causes timeout error

### ISSUE THREAD

**Issue by theSage21** [codalab/codalab-worksheets#443]
I'm trying to submit to the [Squad leaderboard](https://rajpurkar.github.io/SQuAD-explorer/) and successfully followed the tutorial for dev set evaluations.

Now when I try to submit my model, I'm running this command in the web console.

`cl run :dev-v2.0.json :random_sub.py "pipenv run python random_sub.py dev-v2.0.json predictions.json" -n random_predictions --request-docker-image arjoonn/squad2:env_reorg`

The docker image is basically a pipenv with some other things in it. I have uploaded some code in `random_sub.py`.

The command however fails with the following traceback. What am I doing wrong?
```
Creating a virtualenv for this project...
Pipfile: /0xf08e096a5ec44bedb9791a2d31880da3/Pipfile
Using /usr/local/bin/python (3.6.6) to create virtualenv...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 109, in expect_loop
    return self.timeout()
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f05800fa278>
searcher: searcher_re:
    0: EOF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 701, in run
    do_run(command=command, args=args, three=three, python=python, pypi_mirror=pypi_mirror)
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 2244, in do_run
    ensure_project(three=three, python=python, validate=False, pypi_mirror=pypi_mirror)
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 609, in ensure_project
    three=three, python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 556, in ensure_virtualenv
    do_create_virtualenv(python=python, site_packages=site_packages, pypi_mirror=pypi_mirror)
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 934, in do_create_virtualenv
    click.echo(crayons.blue(c.out), err=True)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/delegator.py", line 99, in out
    self.__out = self._pexpect_out
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/delegator.py", line 87, in _pexpect_out
    result += self.subprocess.read()
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 441, in read
    self.expect(self.delimiter)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f05800fa278>
searcher: searcher_re:
    0: EOF
<pexpect.popen_spawn.PopenSpawn object at 0x7f05800fa278>
searcher: searcher_re:
    0: EOF
```

**Comment by bkgoksel** [comment]
Hi, 
Can you try to run the docker image locally and try to run the problem pipenv command in it? (You can follow [this Wiki guide](https://github.com/codalab/codalab-worksheets/wiki/Creating-Docker-Images#building-your-own-images), especially step 9, to run your docker image locally)
Closing until then as there's no reason to think this is a CodaLab bug until then, feel free to reopen if you can't get your workflow to run on CodaLab.

**Comment by theSage21** [comment]
Here's what I've done.

1. Rebuilt the docker image. Dockerfile attached.
2. Pushed to `arjoonn/squad2env:0.1`
3. Now this command runs locally. `docker run -it --rm arjoonn/squad2env:0.1 /bin/bash`
   - after which I can successfully run `pipenv run python --version` and it prints out the correct things.
   - importing the libraries I need also works in this interactive environment.

I take it I don't have to include the `random_sub.py` file in the docker image since that would be uploaded to codalab in the contest? The command still [fails on codalab](https://worksheets.codalab.org/bundles/0x385b8a84197c470aad2931bb4ddcb449/) with a similar traceback


[Dockerfile.txt](https://github.com/codalab/codalab-worksheets/files/2323594/Dockerfile.txt)

**Comment by bkgoksel** [comment]
Is the pipenv command interactive? I see that it fails with a timeout in a package called expect. Maybe the command expects some user input and that times out? Codalab doesn't support interactive sessions so you'd need to make sure your command completely runs without any user input.
