### ISSUE TITLE
CI tests failed for 3.9

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4449]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/1689183/233200657-7813f13b-f995-4088-9ecc-f23764a0b796.png">

```
Obtaining file:///home/runner/work/codalab-worksheets/codalab-worksheets
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Collecting apache-beam[azure]==2.36.0 (from codalab==1.6.2)
  Using cached apache-beam-2.36.0.zip (2.[7](https://github.com/codalab/codalab-worksheets/actions/runs/4747469114/jobs/8433126837?pr=4444#step:5:8) MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 11[8](https://github.com/codalab/codalab-worksheets/actions/runs/4747469114/jobs/8433126837?pr=4444#step:5:9), in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-22px35hi/overlay/lib/python3.[9](https://github.com/codalab/codalab-worksheets/actions/runs/4747469114/jobs/8433126837?pr=4444#step:5:10)/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-22px35hi/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 3[20](https://github.com/codalab/codalab-worksheets/actions/runs/4747469114/jobs/8433126837?pr=4444#step:5:21), in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-[22](https://github.com/codalab/codalab-worksheets/actions/runs/4747469114/jobs/8433126837?pr=4444#step:5:23)px35hi/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-22px35hi/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 97, in <module>
        File "/tmp/pip-build-env-22px35hi/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 526, in get_distribution
          dist = get_provider(dist)
        File "/tmp/pip-build-env-22px35hi/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 398, in get_provider
          return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
        File "/tmp/pip-build-env-22px35hi/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 966, in require
          needed = self.resolve(parse_requirements(requirements))
        File "/tmp/pip-build-env-22px35hi/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/tmp/pip-build-env-22px35hi/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 868, in _resolve_dist
          raise DistributionNotFound(req, requirers)
      pkg_resources.DistributionNotFound: The 'pip' distribution was not found and is required by the application
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Notice:  A new release of pip is available: 22.0.4 -> [23](https://github.com/codalab/codalab-worksheets/actions/runs/4747469114/jobs/8433126837?pr=4444#step:5:24).1
Notice:  To update, run: pip install --upgrade pip
```

**Comment by epicfaace** [comment]
Fixed by #4452
