### ISSUE TITLE
Tests failing with int() conversion

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4481]
I get this error

```
Traceback (most recent call last):
  File "tests/cli/test_cli.py", line 3433, in <module>
    success = TestModule.run(args.tests, args.instance, args.second_instance)
  File "tests/cli/test_cli.py", line 636, in run
    module.func(ctx)
  File "tests/cli/test_cli.py", line 2983, in test_workers
    free_memory_original = int(free_memory_original)
ValueError: invalid literal for int() with base 10: '6.8g'
```

https://github.com/codalab/codalab-worksheets/actions/runs/5134669028/jobs/9239275408?pr=4413

**Comment by epicfaace** [comment]
Nvm, this is only part of https://github.com/codalab/codalab-worksheets/pull/4413 and will be fixed in that PR.
