### ISSUE TITLE
Help getting started with contributing

### ISSUE THREAD

**Issue by SaumitraLohokare** [codalab/codalab-worksheets#4524]
Hello! I am an independent researcher who recently graduated from Binghamton University (SUNY). I am interested in contributing to this project, however I'm facing trouble getting my setup ready.

According to the docs, I have made sure that docker & docker-compose is of the correct version.
```
(codalab) artimuas@MSI:~/projects/codalab-worksheets$ docker --version
Docker version 24.0.5, build ced0996
(codalab) artimuas@MSI:~/projects/codalab-worksheets$ docker-compose --version
Docker Compose version v2.20.2-desktop.1
```

Then I ran `./codalab_service.py start`, to get the server quickly started. However, this results in an error for me:
```
process: time="2023-08-29T13:21:07-04:00" level=warning msg="The \"CODALAB_SENTRY_INGEST_URL\" variable is not set. Defaulting to a blank string."
process: time="2023-08-29T13:21:07-04:00" level=warning msg="The \"CODALAB_SENTRY_ENVIRONMENT\" variable is not set. Defaulting to a blank string."
process: 1 error(s) decoding:
process:
process: * error decoding 'volumes[1]': invalid spec: ::ro: empty section between colons
Traceback (most recent call last):
  File "./codalab_service.py", line 1062, in <module>
    main()
  File "./codalab_service.py", line 125, in main
    service_manager.execute()
  File "./codalab_service.py", line 790, in execute
    self.start_services()
  File "./codalab_service.py", line 942, in start_services
    self.bring_up_service('mysql')
  File "./codalab_service.py", line 901, in bring_up_service
    self._run_compose_cmd('up --force-recreate -d --no-deps %s' % service)
  File "./codalab_service.py", line 891, in _run_compose_cmd
    raise Exception('Command exited with code {}'.format(popen.returncode))
Exception: Command exited with code 15
```

I am unable to debug this error... I'd really appreciate help getting started, I'd love to contribute to this project!

**Comment by percyliang** [comment]
@epicfaace Perhaps you can help?

**Comment by epicfaace** [comment]
Hi @SaumitraLohokare ! What OS are you using? Also, can you run `printenv` to send me your current environment variables?

**Comment by pranavjain** [comment]
Closing this issue for now. @SaumitraLohokare Feel free to open it again if required.
