### ISSUE TITLE
Correctly and consistently handle Unicode characters

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#502]
There are a lot of places in the codebase that crash due to unicode characters. Fixing them one-by-one is probably a bad idea and will lead to even flakier code. We need to try to think of a general way to handle Unicode characters properly everywhere.

- [ ] Encode all strings as UTF-8 before printing in BundleCLI? (Non-encoded Unicode characters cause an exception to be raised by the StringIO instance that buffers output when using the web terminal.)
- [ ] Unicode in web terminal commands cause error (see below)
- [ ] Worksheet markdown should be unicode safe
- [x] Unicode characters in bundle commands currently crash the worksheet when generating the raw lines (codalab/codalab-worksheets#300)
- [ ] Change `String` columns to `Unicode` as necessary for automatic conversion
- [ ] and others
- [ ] Add tests a bunch of tests for adding and displaying Unicode content so that bugs don't happen again

**Comment by kashizui** [comment]
Adding another:
```
POST /api/worksheets/command/

Form params:

{"worksheet_uuid":"0x356dfea3aa93477ebc5c04d33c661ec6","raw_command":{"k":"title","v":"run â€˜dateâ€™","action":"worksheet-edit"}}=''

Local variables:
action=u'worksheet-edit'
raw_command_map={u'action': u'worksheet-edit', u'k': u'title', u'v': u'run \u2018date\u2019'}
key=u'title'
value=u'run \u2018date\u2019'

Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/codalab/server/rest_server.py", line 146, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/azureuser/codalab-cli/codalab/server/json_api_plugin.py", line 17, in wrapper
    result = callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 712, in post_worksheets_command
    data['command'] = service.get_command(data['raw_command'])
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 540, in get_command
    return worksheet_util.get_worksheet_info_edit_command(raw_command_map)
  File "/home/azureuser/codalab-cli/codalab/lib/worksheet_util.py", line 101, in get_worksheet_info_edit_command
    return 'wedit -{k[0]} "{v}"'.format(**raw_command_map)

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 4: ordinal not in range(128)
```

**Comment by kashizui** [comment]
Follow official advice:
https://docs.python.org/2/howto/unicode.html#tips-for-writing-unicode-aware-programs

Just use Unicode everywhere in the backend where reasonable, and only encode/decode at the network/database boundaries.

Check that sqlalchemy does not do encoding automatically..

**Comment by maxwang7** [comment]
Would it be possible to push a quick fix to the worksheets problem? It seems like a recent bug that was introduced.

**Comment by maxwang7** [comment]
Would also be happy to help once the newsletter is out.

**Comment by kashizui** [comment]
i'm struggling to come up with a good solution that doesn't make our code worse because of the state of our encoding code :/ 

i'll try to come up with a simple patch for the worksheets problem though as soon as I can

**Comment by percyliang** [comment]
Is implementing the "unicode everywhere except at network / file
boundaries" principle difficult?

**Comment by percyliang** [comment]
@epicfaace Check that these issues are resolved with the upgrade to Python 3 (#1016).

**Comment by epicfaace** [comment]
Update: We are constraining #1016 to keep the same behavior as before (unicode allowed only in worksheet_item values)

As a proper solution for unicode, we need to modify the database to make sure that the appropriate columns have a charset of utf8mb4 (instead of latin-1), remove the custom encoding / decoding code, and do any transformations of existing data as necessary.
