### ISSUE TITLE
AssertionError in cl print

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#503]
From @ppasupat 

> With CodaLab CLI, When I tried running `cl print`, it gives me the following exception:
> 
> ```
> Traceback (most recent call last):
>   File "/home/ppasupat/.local/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 131, in <module>
>     cli.do_command(sys.argv[1:])
>   File "/home/ppasupat/.local/codalab-cli/codalab/lib/bundle_cli.py", line 659, in do_command
>     structured_result = command_fn()
>   File "/home/ppasupat/.local/codalab-cli/codalab/lib/bundle_cli.py", line 641, in <lambda>
>     command_fn = lambda: args.function(self, args)
>   File "/home/ppasupat/.local/codalab-cli/codalab/lib/bundle_cli.py", line 1918, in do_print_command
>     self.display_interpreted(client, worksheet_info, interpreted)
>   File "/home/ppasupat/.local/codalab-cli/codalab/lib/bundle_cli.py", line 1932, in display_interpreted
>     self.print_target_info(client, data, decorate=True, maxlines=maxlines)
>   File "/home/ppasupat/.local/codalab-cli/codalab/lib/bundle_cli.py", line 1455, in print_target_info
>     for line in client.head_target(target, maxlines):
>   File "/home/ppasupat/.local/codalab-cli/codalab/client/remote_bundle_client.py", line 161, in inner
>     return getattr(self.proxy, command)(*args, **kwargs)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
>     return self.__send(self.__name, args)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
>     verbose=self.__verbose
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
>     return self.parse_response(response)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
>     return u.close()
>   File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
>     raise Fault(**self._stack[0])
> xmlrpclib.Fault: <Fault 1: "<type 'exceptions.AssertionError'>:">
> ```
> 
> My sheet is https://codalab.stanford.edu/worksheets/0xbc6ffb29af8b422b8fef3312738cee4c/. It seems to happen on the following lines:
> 
> % display contents /stdout
> [run run-cat -- ..(omitted).. ]{0x1becfb6417264151a43111f53b5e81b1}

Logs show:

```
bundle_rpc_server: head_target (['0x1becfb6417264151a43111f53b5e81b1', 'stdout'], None)
=== INTERNAL ERROR:
…
Traceback (most recent call last):
  File "/u/nlp/data/codalab/codalab-cli/codalab/server/bundle_rpc_server.py", line 121, in function_to_register
    result = getattr(target, command)(*args, **kwargs)
  File "/u/nlp/data/codalab/codalab-cli/codalab/client/local_bundle_client.py", line 596, in head_target
    gzipped=False).splitlines(True)
  File "/u/nlp/data/codalab/codalab-cli/codalab/lib/download_manager.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/u/nlp/data/codalab/codalab-cli/codalab/lib/download_manager.py", line 171, in summarize_file
    string = file_util.summarize_file(file_path, num_head_lines, num_tail_lines, max_line_length, truncation_text)
  File "/u/nlp/data/codalab/codalab-cli/worker/file_util.py", line 153, in summarize_file
    assert(num_head_lines > 0 or num_tail_lines > 0)
AssertionError
```

@percyliang

**Comment by kashizui** [comment]
Fixed in upcoming release by #434 

(~~However looks like there is now a new error on this worksheet..
`ERROR: Not found: '/bundles/0x1908dea05d534b62a5242dfd7850a7bb/contents/info/stdout'`~~
EDIT: oops sorry this is expected as the new code has not been deployed yet)
