### ISSUE TITLE
No module named marshmallow

### ISSUE THREAD

**Issue by ppasupat** [codalab/codalab-worksheets#526]
After setting up a fresh copy of codalab and running `cl ls`, the following error occurs:

```
Traceback (most recent call last):
  File "/home/ppasupat/.local/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 13, in <module>
    from codalab.lib.bundle_cli import BundleCLI, Commands
  File "/home/ppasupat/.local/codalab-cli/codalab/lib/bundle_cli.py", line 32, in <module>
    from codalab.bundles import (
  File "/home/ppasupat/.local/codalab-cli/codalab/bundles/__init__.py", line 1, in <module>
    from codalab.bundles.dataset_bundle import DatasetBundle
  File "/home/ppasupat/.local/codalab-cli/codalab/bundles/dataset_bundle.py", line 4, in <module>
    from codalab.bundles.uploaded_bundle import UploadedBundle
  File "/home/ppasupat/.local/codalab-cli/codalab/bundles/uploaded_bundle.py", line 6, in <module>
    from codalab.bundles.named_bundle import NamedBundle
  File "/home/ppasupat/.local/codalab-cli/codalab/bundles/named_bundle.py", line 9, in <module>
    from codalab.lib import spec_util
  File "/home/ppasupat/.local/codalab-cli/codalab/lib/spec_util.py", line 7, in <module>
    from marshmallow import ValidationError
ImportError: No module named marshmallow
```

**Comment by ppasupat** [comment]
After installing marshmallow manually, it further complains about not finding other packages, all of which are listed in `requirements-server.txt`.

**Comment by ppasupat** [comment]
Never mind; duplicated with #521.
