### ISSUE TITLE
Fail to set up local instance

### ISSUE THREAD

**Issue by ChengshuLi** [codalab/codalab-worksheets#53]
Hello,

Thanks in advance for reading this. 

I was trying to set up my local instance and followed the instruction from this page. 
https://github.com/codalab/codalab-competitions/wiki/Setup-Local-Worksheets

I finished installing all the requirements (except I had trouble downloading uWSGI==1.9.16 as it has some bugs for Mac OS 10.10, so I instead downloaded a different (newest stable) version uWSGI==2.0.12)

Then I was stuck when I tried to run this:

```
cd $HOME/codalab/codalab-worksheets
./manage syncdb --migrate
./manage config_gen
./manage set_site your_domain_name.com
```

Here is my error:
```
$ ./manage syncdb --migrate
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/configurations/importer.py", line 127, in load_module
    mod = imp.load_module(fullname, *self.location)
  File "/Users/apple/Desktop/codalab-worksheets/codalab/codalab/settings/__init__.py", line 14, in <module>
    class Base(Settings):
  File "/Users/apple/Desktop/codalab-worksheets/codalab/codalab/settings/__init__.py", line 20, in Base
    config = json.loads(open(config_path).read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

I think the problem is that I did not properly generate ~/.codalab/website-config.json. In fact, it is actually empty in my case, which is definitely not correct. Does anyone have any suggestion on how to generate website-config.json?
 
My environment is Python 2.7.8 and Mac OS 10.10.5

Any help is greatly appreciated! Thanks! 

-Eric

**Comment by andreweduffy** [comment]
Yes, the file cannot be empty, simply make it a trivial JSON object to get rid of the error

```
{}
```

**Comment by ChengshuLi** [comment]
Hey Andrew,

Thanks a lot for your help! I got past 
`./manage syncdb --migrate`
Then I got an error when I ran this
`./manage config_gen`
The error is:
`TypeError: argument 2 to map() must support iteration`

I have been trying to deal with this myself for a while but haven't got anything. Thanks in advance for your help! 

-Eric

**Comment by percyliang** [comment]
You don't need config_gen for now

**Comment by percyliang** [comment]
Can you edit the wiki with whatever you did to make this work?

**Comment by ChengshuLi** [comment]
No problem. Will do.

**Comment by klopyrev** [comment]
I removed the config_gen line from the Wiki.
