### ISSUE TITLE
Exception on malformed bundle

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#565]
Report from NLP instance, where I had just run `cl search .` (searching for a period, don't ask me why). This bug can't be reproduced on any other instance. There is probably some malformed data corresponding to a bundle that a period in its name that doesn't get processed robustly on the server.

```
Error on request by stephenkoo(33):

GET /bundles

Query params: [('keywords', '.'), ('worksheet', '0x69c74999b0e8413eb93d1b0f5ddb6b3d')]

Form params: []

JSON body:
<none>

Traceback (most recent call last):
  File "/u/nlp/data/codalab/codalab-cli/codalab/server/rest_server.py", line 134, in wrapper
    return callback(*args, **kwargs)
  File "/u/nlp/data/codalab/codalab-cli/codalab/server/json_api_plugin.py", line 16, in wrapper
    return callback(*args, **kwargs)
  File "/u/nlp/data/codalab/codalab-cli/codalab/server/authenticated_plugin.py", line 34, in wrapper
    return callback(*args, **kwargs)
  File "/u/nlp/data/codalab/codalab-cli/codalab/rest/bundles.py", line 167, in _fetch_bundles
    return build_bundles_document(bundle_uuids)
  File "/u/nlp/data/codalab/codalab-cli/codalab/rest/bundles.py", line 177, in build_bundles_document
    get_host_worksheets=True,
  File "/u/nlp/data/codalab/codalab-cli/codalab/rest/util.py", line 101, in wrapper
    return f(local, request, *args, **kwargs)
  File "/u/nlp/data/codalab/codalab-cli/codalab/rest/bundles.py", line 660, in get_bundle_infos
    user = users[info['owner_id']]
KeyError: None
```

**Comment by kashizui** [comment]
This bug resulted from `owner_id` being `None` for some bundles. @percyliang I don't believe there is any case where this is expected/OK, right?

**Comment by percyliang** [comment]
No, this shouldn't happen.  But maybe the code should be robust to this
anyway (assuming it doesn't make the code too ugly).

**Comment by kashizui** [comment]
After inspection, there are too many places where the code depends on owner being defined.

Seeing as NLP is the only instance with bundles that have undefined owner (wsprod/test are fine), I propose transferring ownership to all these ownerless bundles to the admin (codalab). @percyliang is this OK?

**Comment by percyliang** [comment]
Yes, that's fine.

**Comment by kashizui** [comment]
Transferred all ownerless bundles to admin on NLP instance.
