### ISSUE TITLE
Frequent MySQL errors on worker check-in

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#571]
Getting a MySQL deadlock error on worksheets.codalab.org every few hours at irregular intervals when handling a worker check-in.

Error report:

```
Error on request by codalab(0):

POST /workers/clws-w2(29917)/checkin

Query params:


Form params:


JSON body:
{
    "cpus": 4,
    "dependencies": [
        [
            "0x1efccd6e618f4318a0a0ab4b3efea94d",
            ""
        ],
        [
            "0x48d7ed4d68ca447ab0cc1edef00164e6",
            ""
        ],
<truncated>
        [
            "0x3cd3bd8c01554e9189f49dd7f8398d14",
            ""
        ]
    ],
    "memory_bytes": 14707765248,
    "slots": 4,
    "tag": null,
    "version": 6,
    "will_upgrade": false
}

Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/codalab/server/rest_server.py", line 136, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/server/json_api_plugin.py", line 16, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/server/authenticated_plugin.py", line 34, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/rest/workers.py", line 41, in checkin
    request.json['dependencies'])
  File "/home/azureuser/codalab-cli/codalab/model/worker_model.py", line 64, in worker_checkin
    cl_worker_dependency.c.worker_id == worker_id)))
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction') [SQL: u'DELETE FROM worker_dependency WHERE worker_dependency.user_id = %s AND worker_dependency.worker_id = %s'] [parameters: ('0', 'clws-w2(29917)')]
```

**Comment by kashizui** [comment]
Maybe helpful reference: 
http://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans

**Comment by kashizui** [comment]
From `SHOW ENGINE INNODB STATUS`:

```
------------------------
LATEST DETECTED DEADLOCK
------------------------
160820  8:34:39
*** (1) TRANSACTION:
TRANSACTION 155996B3, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 8 lock struct(s), heap size 1248, 607 row lock(s), undo log entries 1
MySQL thread id 1093, OS thread handle 0x7f8d7c217700, query id 10737000 localhost bundles_user updating
DELETE FROM worker_dependency WHERE worker_dependency.user_id = '0' AND worker_dependency.worker_id = 'clws-w2(29917)'
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 0 page no 485242 n bits 264 index `GEN_CLUST_INDEX` of table `codalab_bundles`.`worker_dependency` trx id 155996B3 lock_mode X locks rec but not gap waiting
Record lock, heap no 61 PHYSICAL RECORD: n_fields 7; compact format; info bits 0
 0: len 6; hex 0000b4b64f6a; asc     Oj;;
 1: len 6; hex 000015599639; asc    Y 9;;
 2: len 7; hex d800004f850110; asc    O   ;;
 3: len 1; hex 30; asc 0;;
 4: len 14; hex 636c77732d773228323939313729; asc clws-w2(29917);;
 5: len 30; hex 307831656663636436653631386634333138613061306162346233656665; asc 0x1efccd6e618f4318a0a0ab4b3efe; (total 34 bytes);
 6: len 0; hex ; asc ;;

*** (2) TRANSACTION:
TRANSACTION 155996AF, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
45 lock struct(s), heap size 6960, 7230 row lock(s), undo log entries 544
MySQL thread id 1099, OS thread handle 0x7f8d7c2aa700, query id 10737001 localhost bundles_user update
INSERT INTO worker_dependency (user_id, worker_id, dependency_uuid, dependency_path) VALUES 
('0', 'clws-w1(7756)', '0xe480ff61619749dcb454e9e56c35f932', ''),
('0', 'clws-w1(7756)', '0x2cf81ac9b8154e49a06f51dfeaa04a34', ''),
('0', 'clws-w1(7756)', '0x5c627ed23a384afb9db7b7fdc03378aa', ''),
('0', 'clws-w1(7756)', '0xe97d1527f3f143ee9f37cf9d42b2fb08', ''),
('0', 'clws-w1(7756)', '0x0f0486d00ec64eb49c48e57134635933', ''),
('0', 'clws-w1(7756)', '0x31ec219d95b74f30985116c5865999fb', ''),
('0', 'clws-w1(7756)', '0x805d7c6524e84c03b09fc593b41a9f9d', ''),
('0', 'clws-w1(7756)', '0xdf5fb298d5614afea7766a7967dc96c1', ''),
('0', 'clws-w1(7756)', '0xe8656523bb36402a89b8148b1ca23fe3', ''),
('0', 'clws-w1(7756)', '0x36d7519b338941f6ab10f8a3b3e88680', ''),
('0', 'clws-w1(7756)', '0x744473d306df4da3b20c7a0ce529164c', ''),
('0', 'clws-w1(7756)', '0xeaadde5d9d4d41fe855f416254fc08f2', ''),
('0', 'clws-w1(7756)', '0xee212041d
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 0 page no 485242 n bits 264 index `GEN_CLUST_INDEX` of table `codalab_bundles`.`worker_dependency` trx id 155996AF lock_mode X
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

Record lock, heap no 2 PHYSICAL RECORD: n_fields 7; compact format; info bits 32
 0: len 6; hex 0000b4b64f2f; asc     O/;;
 1: len 6; hex 000015599680; asc    Y  ;;
 2: len 7; hex 1e00004f902dda; asc    O - ;;
 3: len 1; hex 30; asc 0;;
 4: len 14; hex 636c77732d773628313337303429; asc clws-w6(13704);;
 5: len 30; hex 307837663631313930323633303734656430623532376636613232393937; asc 0x7f61190263074ed0b527f6a22997; (total 34 bytes);
 6: len 0; hex ; asc ;;

<truncated>

Record lock, heap no 196 PHYSICAL RECORD: n_fields 7; compact format; info bits 0
 0: len 6; hex 0000b4b64ff1; asc     O ;;
 1: len 6; hex 000015599639; asc    Y 9;;
 2: len 7; hex d800004f850980; asc    O   ;;
 3: len 1; hex 30; asc 0;;
 4: len 14; hex 636c77732d773228323939313729; asc clws-w2(29917);;
 5: len 30; hex 307833393162383733663638303734356363613365366366383933343039; asc 0x391b873f680745cca3e6cf893409; (total 34 bytes);
 6: len 0; hex ; asc ;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 0 page no 357955 n bits 144 index `user_id` of table `codalab_bundles`.`worker_dependency` trx id 155996AF lock_mode X locks gap before rec insert intention waiting
Record lock, heap no 2 PHYSICAL RECORD: n_fields 3; compact format; info bits 32
 0: len 1; hex 30; asc 0;;
 1: len 14; hex 636c77732d773228323939313729; asc clws-w2(29917);;
 2: len 6; hex 0000b4b64491; asc     D ;;

*** WE ROLL BACK TRANSACTION (1)
```

**Comment by kashizui** [comment]
@percyliang Do you have any idea why we haven't seen this bug since 9/9? (Looking at the codalab.alerts emails.) Has this been resolved while I was gone?

**Comment by percyliang** [comment]
maybe because we have stressed it as much?  What it shows up when we have
lots of jobs running?

**Comment by kashizui** [comment]
Just an update: I've been staring at these deadlock logs and reading about InnoDB for hours and still not immediately upon a solution. I'm also unable to reproduce the error on my own machine at the moment. Hopefully will figure this out soon, I think it may require a schema change, since the lack of primary index in `worker_dependency` means that there's no way to guarantee on the order of the index records, potentially leading to deadlock?

**Comment by kashizui** [comment]
A few of my findings:
- There is no primary index in `worker_dependency`, so InnoDB creates a hidden clustered index on a synthetic column containing row ID values called `GEN_CLUST_INDEX`.
- Record-level locks and gap locks are set according to this index.
- For some reason, `INSERT`ing worker dependencies for worker A ends up setting exclusive locks on records that are for worker B (not sure why yet), so when concurrently deleting the worker dependencies for worker B we end up with a deadlock. (This means that the locks for worker B dependencies records are being grabbed in different orders in the two transactions.)
- Easiest solution is to just implement retry on deadlock, since deadlocks don't break database integrity.
- Still trying to understand the deadlock better so that we can potentially rewrite the queries to prevent deadlock (possibly involving modifying the table indices though not sure what.)

References:
http://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks.html
http://dev.mysql.com/doc/refman/5.7/en/innodb-deadlock-example.html
http://dev.mysql.com/doc/refman/5.7/en/innodb-locking.html
http://dev.mysql.com/doc/refman/5.7/en/innodb-locks-set.html
https://dev.mysql.com/doc/refman/5.7/en/innodb-index-types.html
http://www.xaprb.com/blog/2006/08/03/a-little-known-way-to-cause-a-database-deadlock/
https://www.percona.com/blog/2014/10/28/how-to-deal-with-mysql-deadlocks/
http://www.fromdual.com/deadlocks-indexing-and-primary-keys

**Comment by kashizui** [comment]
As-per-Percy, maybe add an arbitrary index?

**Comment by kashizui** [comment]
Solution that I've settled on so far and will implement asap:
- Store dependencies in a single row per user/worker as an array of tuples in a MEDIUMBLOB column, de/serialized using json (we can switch to a faster/more compact serialization format like msgpack in the future if we want to)
- ALTER (user_id, worker_id) to be a primary key on dependency table
- On checkin, update corresponding row in dependency table by primary key (there should no longer be deadlock since this will grab a record lock, not a next-key lock)
- ADD COLUMN is_active to worker table, set to false instead of deleting row when worker disconnects (this will help minimize page fragmentation)
- Leave the dependency row in the table when its associated worker becomes inactive, to minimize database page fragmentation
  - Maybe once in a while clear all dependency rows where the worker is not active, but there aren't that many unique workers using our system yet.

References:
https://www.percona.com/live/mysql-conference-2013/sessions/practical-tips-using-mysql-scalable-key-value-store
http://www.informit.com/articles/article.aspx?p=1238838&seqNum=2
http://stackoverflow.com/questions/3413291/how-to-store-an-array-into-mysql

**Comment by percyliang** [comment]
It seems like we have to have a mechanism (script?) for cleaning up old
workers - maybe those that haven't been active after a week or something.
