### ISSUE TITLE
Unexpected PreconditionViolation (Trying to find worker for bundle that is not running)

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#588]
```
GET /api/bundles/0x3d4dab7107044331b96026b839d37833/

Query params:
_=1475138492941

Form params:


JSON body:
<none>

Local variables:
message=Trying to find worker for bundle that is not running.
condition=None

Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/codalab/server/rest_server.py", line 136, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/server/json_api_plugin.py", line 16, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 545, in get_bundle_info
    bundle_info.update(service.get_bundle_file_contents(uuid))
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 256, in get_bundle_file_contents
    info = self.get_top_level_contents((uuid, ''))
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 287, in get_top_level_contents
    info = self.client.get_target_info(target, 1)
  File "/home/azureuser/codalab-cli/codalab/client/local_bundle_client.py", line 381, in get_target_info
    return self.download_manager.get_target_info(target[0], target[1], depth)
  File "/home/azureuser/codalab-cli/codalab/lib/download_manager.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/lib/download_manager.py", line 70, in get_target_info
    worker = self._worker_model.get_bundle_worker(uuid)
  File "/home/azureuser/codalab-cli/codalab/model/worker_model.py", line 149, in get_bundle_worker
    precondition(row, 'Trying to find worker for bundle that is not running.')
  File "/home/azureuser/codalab-cli/codalab/common.py", line 112, in precondition
    raise PreconditionViolation(message)
PreconditionViolation: Trying to find worker for bundle that is not running.
```

**Comment by kashizui** [comment]
I think this is a simple TOCTTOU error that might be rare enough not to warrant fixing, since fixing it will require creating larger transactions, which is bad for db performance. The solution for the user is just to retry the command.

**Comment by percyliang** [comment]
Ok, let's maybe record it somewhere for now, and if see it again, then we
can revisit it.

**Comment by fabeschan** [comment]
Should be gone with #805
