### ISSUE TITLE
mysql_config not found when running codalab-worksheets/setup.sh

### ISSUE THREAD

**Issue by klopyrev** [codalab/codalab-worksheets#59]
Downloading MySQL-python-1.2.5.zip (108kB): 
  Downloading from URL https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.5.zip#md5=654f75b302db6ed8dc5a898c625e030c (fro
m https://pypi.python.org/simple/mysql-python/)
...Downloading MySQL-python-1.2.5.zip (108kB): 108kB downloaded
  Running setup.py (path:/home/klopyrev/Dropbox/Codalab/codalab-worksheets/venv/build/MySQL-python/setup.py) egg_info for package MySQL-python
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/klopyrev/Dropbox/Codalab/codalab-worksheets/venv/build/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/klopyrev/Dropbox/Codalab/codalab-worksheets/venv/build/MySQL-python/setup.py", line 17, in <module>

    metadata, options = get_config()

  File "setup_posix.py", line 43, in get_config

    libs = mysql_config("libs_r")

  File "setup_posix.py", line 25, in mysql_config

    raise EnvironmentError("%s not found" % (mysql_config.path,))

EnvironmentError: mysql_config not found

----------------------------------------
Cleaning up...
  Removing temporary dir /home/klopyrev/Dropbox/Codalab/codalab-worksheets/venv/build...
Command python setup.py egg_info failed with error code 1 in /home/klopyrev/Dropbox/Codalab/codalab-worksheets/venv/build/MySQL-python
Exception information:
Traceback (most recent call last):
  File "/home/klopyrev/codalab/codalab-worksheets/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/klopyrev/codalab/codalab-worksheets/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/klopyrev/codalab/codalab-worksheets/venv/local/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/home/klopyrev/codalab/codalab-worksheets/venv/local/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/klopyrev/codalab/codalab-worksheets/venv/local/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/klopyrev/Dropbox/Codalab/codalab-worksheets/venv/build/M
ySQL-python

Storing debug log for failure in /home/klopyrev/.pip/pip.log
ERROR: Failed to install requirements: /home/klopyrev/codalab/codalab-worksheets/codalab/requirements/common.txt

**Comment by andreweduffy** [comment]
@klopyrev I'm guessing you don't have mysql installed on your system?

**Comment by andreweduffy** [comment]
http://stackoverflow.com/questions/7475223/mysql-config-not-found-when-installing-mysqldb-python-interface
