### ISSUE TITLE
Error on metadata update

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#620]
Pending investigation
```
Error on request by XXX:

POST /api/bundles/0x47df80fc705843f9ac7094d2037d2c0b/

Query params:


Form params:
{"metadata":{"description":"xxx"}}=''

JSON body:
<none>

Local variables:
bundle_info=None
uuid='0x47df80fc705843f9ac7094d2037d2c0b'
service=<codalab.rest.legacy.BundleService object at 0x7f513c1151d0>

Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/codalab/server/rest_server.py", line 141, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/server/json_api_plugin.py", line 17, in wrapper
    result = callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 779, in post_bundle_info
    if bundle_info['edit_permission']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by kashizui** [comment]
Code will be removed in legacy cleanup
