### ISSUE TITLE
Catch ValueError in shlex call in web terminal

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#625]
Should re-raise as a UsageError?
```
POST /api/worksheets/command/

Query params:


Form params:


JSON body:
{
    "autocomplete": true,
    "command": "run 'a.t",
    "worksheet_uuid": "0xe461a08f9aef47988054a3185be37ee3"
}

Local variables:
self=<shlex.shlex instance at 0x7f50b420c050>
nextchar=''
quoted=True
escapedstate=' '

Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/codalab/server/rest_server.py", line 141, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/server/json_api_plugin.py", line 17, in wrapper
    result = callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 720, in post_worksheets_command
    'completions': service.complete_command(data['worksheet_uuid'], data['command'])
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 531, in complete_command
    return cli.complete_command(command)
  File "/home/azureuser/codalab-cli/codalab/lib/bundle_cli.py", line 673, in complete_command
    return map(clean, cf._get_completions(comp_words, cword_prefix, cword_prequote, first_colon_pos))
  File "/home/azureuser/codalab-cli/codalab/lib/bundle_cli.py", line 672, in <lambda>
    clean = lambda s: shlex.split(s.strip())[0] if s else ''
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by maxwang7** [comment]
codalab/rest/legacy.py
bundle_cli.py
error at: line 552 in legacy.py (using shlex to split command into tokens). If there's something improper, raises ValueError -> UsageError. 
bundle_cli.py: complete_command() need a try try catch (line 672).
