### ISSUE TITLE
KeyError: user_name

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#640]
@maxwang7 
```
Error on request by maxwang7(0xd7eb0f6433324b56a1835a56524ad5fa):

POST /api/worksheets/command/

Query params:


Form params:


JSON body:
{
    "command": "ginfo public",
    "worksheet_uuid": "0xa403ec6dfb5d430db24ef5e5ff4e6ddf"
}

Local variables:
args=Namespace(command='ginfo', function=<function do_ginfo_command at 0x7fb0f29ccb90>, group_spec='public')
self=<codalab.lib.bundle_cli.BundleCLI object at 0x7fb084681610>
client=<codalab.client.json_api_client.JsonApiClient object at 0x7fb084681590>
group={u'name': u'public', u'admins': [], 'meta': {u'version': u'0.2.0'}, u'members': [], u'owner': EmptyJsonApiRelationship(), 'id': u'0xc573c2c89326443a97e96edaf6443e51'}
members=[]

Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/codalab/server/rest_server.py", line 141, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/server/json_api_plugin.py", line 17, in wrapper
    result = callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 723, in post_worksheets_command
    result = service.general_command(data['worksheet_uuid'], data['command'])
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 566, in general_command
    structured_result = cli.do_command(args)
  File "/home/azureuser/codalab-cli/codalab/lib/bundle_cli.py", line 704, in do_command
    structured_result = command_fn()
  File "/home/azureuser/codalab-cli/codalab/lib/bundle_cli.py", line 686, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/home/azureuser/codalab-cli/codalab/lib/bundle_cli.py", line 2596, in do_ginfo_command
    'user': '%s(%s)' % (group['owner']['user_name'], group['owner']['id']),
KeyError: 'user_name'
```

**Comment by kashizui** [comment]
Fixed by #624
