### ISSUE TITLE
Foreign key constraint fails on bundle deletion

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#648]
..even after `cl wait`.

Our monitor (on both wsprod and nlp) have occasionally been reporting that a `cl rm` call fails on a bundle, AFTER a call to `cl wait` on that bundle just completed. The sequence of commands run by the monitor looks like:

     >>> cl run stress-test.pl:<uuid of stress-test script> perl stress-test.pl 5 10 10
     >>> cl wait <uuid of the newly created run bundle>
     >>> cl rm <uuid of stress-test script> <uuid of newly created run bundle>

We also get a simultaneous exception report with MySQL complaining that 
```
Cannot delete or update a parent row: a foreign key constraint fails (`codalab_bundles`.`worker_run`, CONSTRAINT `worker_run_ibfk_3` FOREIGN KEY (`run_uuid`) REFERENCES `bundle` (`uuid`))
```

It looks like the row in the worker_run table that references the run bundle is not yet deleted when the `cl rm` command is issued, causing a foreign key constraint error.

This is strange to me because when I last checked the code, the bundle is marked as completed (status set to 'ready' or 'failed') in the same database transaction as the deletion of the worker_run row, but for some reason `cl wait` is returning before the worker_run row is deleted. Requires further investigation.

**Comment by kashizui** [comment]
```
Error on request by codalab(0):

DELETE /bundles

Query params:
force='0'
data-only='0'
dry-run='0'
recursive='0'

Form params:


JSON body:
{
    "data": [
        {
            "id": "0xd6f2fff1d742426580ff8dcf4a373ac6",
            "type": "bundles"
        },
        {
            "id": "0x9e6ce3edcddb49feb5725bba44ea7c36",
            "type": "bundles"
        }
    ]
}

Local variables:
errorclass=<class '_mysql_exceptions.IntegrityError'>
errorvalue=IntegrityError(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`codalab_bundles`.`worker_run`, CONSTRAINT `worker_run_ibfk_3` FOREIGN KEY (`run_uuid`) REFERENCES `bundle` (`uuid`))')
error=(<class '_mysql_exceptions.IntegrityError'>, IntegrityError(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`codalab_bundles`.`worker_run`, CONSTRAINT `worker_run_ibfk_3` FOREIGN KEY (`run_uuid`) REFERENCES `bundle` (`uuid`))'))

Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/codalab/server/rest_server.py", line 146, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/azureuser/codalab-cli/codalab/server/json_api_plugin.py", line 17, in wrapper
    result = callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/server/authenticated_plugin.py", line 76, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/rest/bundles.py", line 307, in _delete_bundles
    data_only=data_only, dry_run=dry_run)
  File "/home/azureuser/codalab-cli/codalab/rest/bundles.py", line 617, in delete_bundles
    local.model.delete_bundles(relevant_uuids)
  File "/home/azureuser/codalab-cli/codalab/model/bundle_model.py", line 807, in delete_bundles
    cl_bundle.c.uuid.in_(uuids)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/azureuser/codalab-cli/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (_mysql_exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`codalab_bundles`.`worker_run`, CONSTRAINT `worker_run_ibfk_3` FOREIGN KEY (`run_uuid`) REFERENCES `bundle` (`uuid`))') [SQL: u'DELETE FROM bundle WHERE bundle.uuid IN (%s, %s)'] [parameters: (u'0xd6f2fff1d742426580ff8dcf4a373ac6', u'0x9e6ce3edcddb49feb5725bba44ea7c36')]
```

**Comment by kashizui** [comment]
There seems to be some correlation with this error and attempts to kill bundles, but not an exact correlation. When inspecting the database, the offending bundles clearly have worker_run rows in the database that persist long after the runs have already completed, indicating a bug in cleaning up worker_run rows.

**Comment by bkgoksel** [comment]
Should be fixed with worker2.0 as finalization workflows are now simplified
