### ISSUE TITLE
cl wedit OSError

### ISSUE THREAD

**Issue by hhexiy** [codalab/codalab-worksheets#652]
Running `cl wedit` on nlp machine and got

```python
Traceback (most recent call last):
  File "/u/nlp/data/codalab/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 116, in <module>
    cli.do_command(sys.argv[1:])
  File "/u/nlp/data/codalab/codalab-cli/codalab/lib/bundle_cli.py", line 704, in do_command
    structured_result = command_fn()
  File "/u/nlp/data/codalab/codalab-cli/codalab/lib/bundle_cli.py", line 686, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/u/nlp/data/codalab/codalab-cli/codalab/lib/bundle_cli.py", line 2319, in do_wedit_command
    lines = worksheet_util.request_lines(worksheet_info)
  File "/u/nlp/data/codalab/codalab-cli/codalab/lib/worksheet_util.py", line 204, in request_lines
    lines = editor_util.open_and_edit(suffix='.md', template=template)
  File "/u/nlp/data/codalab/codalab-cli/codalab/lib/editor_util.py", line 25, in open_and_edit
    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as form:
  File "/usr/lib64/python2.7/tempfile.py", line 462, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib64/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/u/hehe/.codalab/misc_temp/tmpvi34CT.md'
```

**Comment by kashizui** [comment]
@hhexiy is this problem still ongoing? I wasn't able to reproduce this -- which node did this occur on?

**Comment by hhexiy** [comment]
@kashizui Nope, it's working now. Thanks!
