### ISSUE TITLE
bs-health-check: AttributeError: 'JsonApiClient' object has no attribute 'model'

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#696]
codalabwstest:~% cl bs-health-check
Performing Health Check...
Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 121, in <module>
    main()
  File "/home/azureuser/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 115, in main
    cli.do_command(sys.argv[1:])
  File "/home/azureuser/codalab-cli/codalab/lib/bundle_cli.py", line 711, in do_command
    structured_result = command_fn()
  File "/home/azureuser/codalab-cli/codalab/lib/bundle_cli.py", line 693, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/home/azureuser/codalab-cli/codalab/lib/bundle_cli.py", line 2984, in do_bs_health_check
    self.manager.bundle_store().health_check(self.manager.current_client().model, args.force, args.data_hash, args.repair)
AttributeError: 'JsonApiClient' object has no attribute 'model'

**Comment by kashizui** [comment]
Just need to replace `self.manager.current_client().model` with `self.manager.model()` I think.

**Comment by fabeschan** [comment]
ah, okay. I'll try that out.

**Comment by fabeschan** [comment]
Patch merged (was in PR #711), should be live on next deploy.
