### ISSUE TITLE
Codalab automatically uncompressing files

### ISSUE THREAD

**Issue by wooters** [codalab/codalab-worksheets#708]
It appears that codalab automatically uncompresses files:
```
$ cl upload -p foo.tgz
$ cl run :foo.tgz "tar ztf foo.tgz" -n foo
```
the `run` command fails:
```
$ cl cat foo/stderr
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by kashizui** [comment]
Thanks for the report.

For us: Just tried it, the upload works, but for some reason the bundle gets unpacked when loaded as a dependency.

**Comment by kashizui** [comment]
Another related bug:
Doing this experiment with ZIP files instead of tar.gz causes an exception to be thrown on the worker:
```
Traceback (most recent call last):
  File "/Users/sckoo/Developer/codalab-cli/worker/run.py", line 163, in _start
    update_status_and_check_killed)
  File "/Users/sckoo/Developer/codalab-cli/worker/worker.py", line 197, in add_dependency
    self._store_dependency(dependency_path, fileobj, filename)
  File "/Users/sckoo/Developer/codalab-cli/worker/worker.py", line 213, in _store_dependency
    shutil.copyfileobj(un_gzip_stream(fileobj), f)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/Users/sckoo/Developer/codalab-cli/worker/file_util.py", line 96, in read
    self._buffer += self._decoder.decompress(chunk)
error: Error -3 while decompressing: incorrect header check
```
