### ISSUE TITLE
Frequent Unable to reach worker errors

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#738]
We frequently get reports of "Unable to reach worker" errors when user is trying to view bundles on website. Not sure yet why this is happening but something to keep an eye on.

```
GET /api/bundles/content/0xdae0f9b3e4dd47df8b9357862334ba1c/

Query params:
_='1493160427441'

Form params:


JSON body:
<none>

Local variables:
message='Unable to reach worker'
condition=False

Traceback (most recent call last):
  File "/u/nlp/data/codalab/codalab-cli/codalab/server/rest_server.py", line 146, in wrapper
    return callback(*args, **kwargs)
  File "/u/nlp/data/codalab/codalab-cli/venv/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/u/nlp/data/codalab/codalab-cli/codalab/server/json_api_plugin.py", line 17, in wrapper
    result = callback(*args, **kwargs)
  File "/u/nlp/data/codalab/codalab-cli/codalab/rest/legacy.py", line 753, in get_bundle_content
    info = service.get_top_level_contents((uuid, path))
  File "/u/nlp/data/codalab/codalab-cli/codalab/rest/legacy.py", line 312, in get_top_level_contents
    info = self.get_target_info(target, 1)
  File "/u/nlp/data/codalab/codalab-cli/codalab/rest/legacy.py", line 345, in get_target_info
    return local.download_manager.get_target_info(target[0], target[1], depth)
  File "/u/nlp/data/codalab/codalab-cli/codalab/lib/download_manager.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/u/nlp/data/codalab/codalab-cli/codalab/lib/download_manager.py", line 77, in get_target_info
    self._send_read_message(worker, response_socket_id, uuid, path, read_args)
  File "/u/nlp/data/codalab/codalab-cli/codalab/lib/download_manager.py", line 230, in _send_read_message
    'Unable to reach worker')
  File "/u/nlp/data/codalab/codalab-cli/codalab/common.py", line 112, in precondition
    raise PreconditionViolation(message)
PreconditionViolation: Unable to reach worker
```

**Comment by percyliang** [comment]
Seems like it should be easy to reproduce by just running jobs and calling
view bundles manically.  Would be nice to get to the bottom of this.

**Comment by kashizui** [comment]
Step 1 is really just to make sure UX is robust to these errors

**Comment by kashizui** [comment]
Also `Bundle no longer running` errors

**Comment by kashizui** [comment]
Leaning more toward better failure modes than trying to "fix" these transient errors, which will probably occur no matter what

**Comment by kashizui** [comment]
Wait for @fabeschan to merge new worker robustness changes and see what happens

**Comment by fabeschan** [comment]
@kashizui should be gone with #805

**Comment by kashizui** [comment]
Beautiful!
