### ISSUE TITLE
pip install doesn't work on some versions

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#787]
- With python2, a silent error when installing codalabworker (silent because it continued to claim that the package was successfully installed). (Log below).
- The package does not build for python3. While I guess python2 is often considered to be the norm, I think python3 support is pretty important for general use because python2 is no longer being actively developed. There are few major packages out there don't support python3 and python3 has many many benefits over python2.

LOG:

  Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/js/yjtt3xs17f35cm1l4vfbzspr0000gn/T/pip-build-M1eXyI/codalabworker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/js/yjtt3xs17f35cm1l4vfbzspr0000gn/T/tmpvZ9c0Ppip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/codalabworker
  copying codalabworker/__init__.py -> build/lib/codalabworker
  copying codalabworker/bundle_service_client.py -> build/lib/codalabworker
  copying codalabworker/dependency_manager.py -> build/lib/codalabworker
  copying codalabworker/docker_client.py -> build/lib/codalabworker
  copying codalabworker/docker_image_manager.py -> build/lib/codalabworker
  copying codalabworker/download_util.py -> build/lib/codalabworker
  copying codalabworker/file_util.py -> build/lib/codalabworker
  copying codalabworker/formatting.py -> build/lib/codalabworker
  copying codalabworker/main.py -> build/lib/codalabworker
  copying codalabworker/rest_client.py -> build/lib/codalabworker
  copying codalabworker/run.py -> build/lib/codalabworker
  copying codalabworker/worker.py -> build/lib/codalabworker
  running egg_info
  writing requirements to codalabworker.egg-info/requires.txt
  writing codalabworker.egg-info/PKG-INFO
  writing top-level names to codalabworker.egg-info/top_level.txt
  writing dependency_links to codalabworker.egg-info/dependency_links.txt
  writing entry points to codalabworker.egg-info/entry_points.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'codalabworker.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'codalabworker.egg-info/SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/js/yjtt3xs17f35cm1l4vfbzspr0000gn/T/pip-build-M1eXyI/codalabworker/setup.py", line 32, in <module>
      zip_safe=False),
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 176, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 52, in run
      self.build_package_data()
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 107, in build_package_data
      for package, src_dir, build_dir, filenames in self.data_files:
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 65, in __getattr__
      self.data_files = self._get_data_files()
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 79, in _get_data_files
      return list(map(self._get_pkg_data_files, self.packages or ()))
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 91, in _get_pkg_data_files
      for file in self.find_data_files(package, src_dir)
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 98, in find_data_files
      + self.package_data.get(package, []))
  TypeError: cannot concatenate 'str' and 'list' objects
  
  ----------------------------------------
  Failed building wheel for codalabworker

**Comment by maxwang7** [comment]
Don't do python3 support, fix the Python2 work

**Comment by maxwang7** [comment]
I can't reproduce this error. I'm pretty sure it's a problem with an out of date pip. I am finding a problem with running the cl-worker script. @percyliang Can you get me in touch with the person who filed this ticket?

**Comment by arunchaganty** [comment]
I was the originator for this comment. I've just checked it again with pip 9.0.1 and am not able to reproduce this error. I think this issue can probably be closed.

Cheers!

**Comment by maxwang7** [comment]
@arunchaganty thank you for checking! If it comes up again let us know!
