### ISSUE TITLE
Truncated worker_dependency fields angering the bundle service

### ISSUE THREAD

**Issue by krivard** [codalab/codalab-worksheets#819]
The bundle service started generating these at about 1Hz:

    Traceback (most recent call last):
      File "/usr0/codalab/codalab-cli/codalab/worker/bundle_manager.py", line 79, in run
        self._run_iteration()
      File "/usr0/codalab/codalab-cli/codalab/worker/bundle_manager.py", line 99, in _run_iteration
        self._schedule_run_bundles()
      File "/usr0/codalab/codalab-cli/codalab/worker/default_bundle_manager.py", line 25, in _schedule_run_bundles
        workers = WorkerInfoAccessor(self._worker_model.get_workers())
      File "/usr0/codalab/codalab-cli/codalab/model/worker_model.py", line 146, in get_workers
        } for row in worker_rows}
      File "/usr0/codalab/codalab-cli/codalab/model/worker_model.py", line 146, in <dictcomp>
        } for row in worker_rows}
      File "/usr0/codalab/codalab-cli/codalab/model/worker_model.py", line 94, in _deserialize_dependencies
        return map(tuple, json.loads(blob))
          File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
        obj, end = self.scan_once(s, idx)
    ValueError: Unterminated string starting at: line 1 column 65523 (char 65522)

It appears to be a problem with the `worker_dependency` table. Here's an example of a record that causes the issue (xxxxxx):

    mysql> select worker_id, RIGHT(dependencies,20) as deps from worker_dependency;
    +--------------------------+----------------------+
    | worker_id                | deps                 |
    +--------------------------+----------------------+
    | xxxxxx.xxxxxx.xxx(32079) | ",""],["0x9fae534df3 |
    | yyyyyy.yyyyyy.yyy(18668) | []                   |
    +--------------------------+----------------------+
    2 rows in set (0.00 sec)

You can see how the 0x9fae item just trails off and isn't closed properly. This could indicate a problem with the serializer on the `dependencies` field, and/or/since the dependencies list for this particular worker has become too long to store in the table.

If I quit the offending worker, the bundle service stops generating errors. When I bring that worker back up, it gets the same bad dependencies value and the errors start up again.

Is there a way to reset the dependencies for a worker? Can I clear the docker image cache, or something like that? And, any idea what might be causing these long dependency chains? We've run barely any jobs so far, and presumably you folks don't see problems like this in the primary instance even with much greater loads.

**Comment by fabeschan** [comment]
there's probably a dependency-state.json file inside your worker's working directory. See if the errors go away after deleting the file.

**Comment by krivard** [comment]
That worked! Thanks :)
