### ISSUE TITLE
cl-worker permission issues

### ISSUE THREAD

**Issue by ezliu** [codalab/codalab-worksheets#900]
I'm running cl-worker and running into the following error message... This happens after several of my jobs successfully complete:

```
IOError: [Errno 13] Permission denied: 'codalab-worker-scratch/dependencies-state.json'
Exception in thread Thread-789:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/juicier/u120/u/nlp/data/codalab/client-venv/local/lib/python2.7/site-packages/codalabworker/run.py", line 267, in _start
    self._monitor()
  File "/juicier/u120/u/nlp/data/codalab/client-venv/local/lib/python2.7/site-packages/codalabworker/run.py", line 299, in _monitor
    self._worker.finish_run(self._uuid)
  File "/juicier/u120/u/nlp/data/codalab/client-venv/local/lib/python2.7/site-packages/codalabworker/worker.py", line 372, in finish_run
    self._dependency_manager.finish_run(uuid)
  File "/juicier/u120/u/nlp/data/codalab/client-venv/local/lib/python2.7/site-packages/codalabworker/dependency_manager.py", line 249, in finish_run
    self._save_state()
  File "/juicier/u120/u/nlp/data/codalab/client-venv/local/lib/python2.7/site-packages/codalabworker/dependency_manager.py", line 71, in _save_state
    with open(self._state_file, 'w') as f:
IOError: [Errno 13] Permission denied: 'codalab-worker-scratch/dependencies-state.json'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/juicier/u120/u/nlp/data/codalab/client-venv/local/lib/python2.7/site-packages/codalabworker/dependency_manager.py", line 98, in _do_cleanup
    dependency.path))
  File "/juicier/u120/u/nlp/data/codalab/client-venv/local/lib/python2.7/site-packages/codalabworker/file_util.py", line 234, in get_path_size
    result = os.lstat(path).st_size
OSError: [Errno 13] Permission denied: 'codalab-worker-scratch/bundles/0x4f914b3bc1254e9ebfe2b0943891a825'
```

**Comment by bkgoksel** [comment]
Can you double check which user does the worker process belong to and what are the permissions on the `codalab-worker-scractch` folder? And do you have more details about on which machine this happened/were the failing runs dependent on the initial succeeding ones and whether any of the successful runs had dependencies run by the same worker?

If you don't remember these/don't have this info anymore, maybe try running a local worker again and we can debug together.

**Comment by ezliu** [comment]
Thanks for the help @bkgoksel!

Permissions of the `codalab-worker-scratch` directory:

```
$ ls -al codalab-worker-scratch/
total 28
drwxrwsrwx  3 evanliu nlp 4096 Mar 28 23:56 .
drwxrwsrwx  3 evanliu nlp 4096 Mar 28 23:56 ..
drwxrwsrwx 49 evanliu nlp 4096 Apr 30 01:31 bundles
-rwxrwxrwx  1 evanliu nlp 7370 Apr  3 06:07 dependencies-state.json
-rwxrwxrwx  1 evanliu nlp  130 Apr  3 06:07 images-state.json
-rwxrwxrwx  1 evanliu nlp   12 Apr 30 01:33 worker-state.json
```

I re-ran the worker to get the worker process info:

```
$ ps aux | grep "cl-worker"      
evanliu   7382  1.2  0.0 131396 17228 pts/2    Sl+  01:32   0:00 /juicier/u120/u/nlp/data/codalab/client-venv/bin/python /u/nlp/bin/cl-worker
```

**Comment by percyliang** [comment]
Can't reproduce...feel free to re-open if it happens again.
