### ISSUE TITLE
setup.sh doesn't work with default Python version 3.6

### ISSUE THREAD

**Issue by nikhilxb** [codalab/codalab-worksheets#965]
Current workaround:

1. Create an environment with Python 2.7:
`conda create -n python27 python=2.7`
`conda activate python27`
2. Install virtualenv (for Python 2.7) within conda environment:
`pip install virtualenv`
3. Run script to create development `venv`:
`(python27) user@host:.../codalab-cli$  ./setup.sh client`
4. Close install env:
`conda deactivate`
5. Activate development `venv`:
`source venv/bin/activate`

**Comment by bkgoksel** [comment]
We generally don't support python 3 AFAIK so the solution would be to make that clearer in the documentation and maybe make the setup script directly use python 2.7

**Comment by bkgoksel** [comment]
So I checked the setup script and it does specify python2.7 when creating the venv already. Did you hot have python 2.7 available at all when this happened?

**Comment by nikhilxb** [comment]
So the issue is not with the python in `venv` but rather the running the python 3.6 version of `virtualenv` itself, not than python 2:
```
[*] Checking for virtualenv...
/usr/local/miniconda3/bin/virtualenv

[*] Setting up a Python virtual environment (in ./venv)...
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /Users/Nikhil/Desktop/codalab-cli-2/venv/bin/python
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.6/site-packages/virtualenv.py", line 2884, in <module>
    main()
  File "/usr/local/miniconda3/lib/python3.6/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/miniconda3/lib/python3.6/site-packages/virtualenv.py", line 1233, in install_python
    copy_exe_shared_libs_and_symlinks(executable, py_executable, home_dir)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/virtualenv.py", line 2843, in copy_exe_shared_libs_and_symlinks
    of = codefile(f, rpaths)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/virtualenv.py", line 2814, in codefile
    return machofile(file, list(initial_rpaths_transitive))
  File "/usr/local/miniconda3/lib/python3.6/site-packages/virtualenv.py", line 2437, in __init__
    _, sos = zip(*mach_o_find_dylibs(file))
  File "/usr/local/miniconda3/lib/python3.6/site-packages/virtualenv.py", line 2401, in mach_o_find_dylibs
    do_file(ofile, find_lc_load_dylib, offset_size(), results, regex)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/virtualenv.py", line 2370, in do_file
    do_file(file, offset_size(offset, size), *args)
TypeError: do_file() takes at least 4 arguments (3 given)
```
The issue is with:
https://github.com/codalab/codalab-cli/blob/master/setup.sh#L41

**Comment by percyliang** [comment]
Hopefully subsumed by migration to Python 3.
